### ISSUE TITLE
pas de user dans la base de données

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#1]
Bonjour, 

l'admin de notre asso à essayer d'installer le logiciel sur un serveur dédié à cet usage. 
il a bien galéré (pourtant c'est son taff), au final, il me dit que c'est inutilisable car il n'y a pas d'utilisateur par defaut dans la base de données, qui permettrais de se connecter en admin. 
genre : 
login : admin
pass : admin

est ce que l'on peux mettre un peu de contenu dans la base par defaut pour que ca soit utilisable des l'installation finie ? 
merci.

**Comment by sylvainbx** [comment]
Bonjour,

La lecture du [fichier de seeds](https://github.com/LaCasemate/fab-manager/blob/master/db/seeds.rb) donne les identifiants de l'utilisateur par défaut : 

utilisateur : admin@fabmanager.com
mot de passe  : adminadmin

@jarod022 Peut-être devrions nous rajouter ces infos dans le fichier README.md ?

**Comment by clemclemmm** [comment]
Mettre un peu plus d'info que pas assez serait peut etre pas mal.

On es pas tous expert en ruby dans le reseau (je me demande toujours pourquoi le choix de ruby + postgresql au lieu de php/mysql)(ce qui sera un frein a une adoption massive je trouve)

ClemClem

**Comment by clemclemmm** [comment]
+ 
Le login de base est une faute de frappe : admin@fabmanager.com au lieu de fab-manager.com 
...

ClemClem
