### ISSUE TITLE
english version

### ISSUE THREAD

**Issue by lpgn** [sleede/fab-manager#10]
We are studing you project as we need a managing system for our fablab.
We have your project up on our subdomain but we weren't able to make the english vesion work.
http://fabmanager.xinfab.com/ (in french now)

Is it only on config\application.rb that we need to change?
from:    config.i18n.default_locale = :fr
to:    config.i18n.default_locale = :en
what are we missing?

Thanks a lot

**Comment by emj365** [comment]
I saw this app use AngularJS as front-end view.
Rails locale config can't work for the static template of JS app.

If you want a solution for AngularJS about multiple language support you could check:
- http://stackoverflow.com/questions/12664823/angular-js-support-for-localization
- http://jsfiddle.net/4tRBY/41/

**Comment by emj365** [comment]
https://scotch.io/tutorials/internationalization-of-angularjs-applications

**Comment by sylvainbx** [comment]
Hi @lpgn, changing `config.i18n.default_locale` is not enough. You need to translate all sentences of the fab-manager application to display the interface in english.
But this is a long work and we're currently already working on an internationalized version of the fab-manager app. Please contact @pascalmoutet for more informations about this.

**Comment by lpgn** [comment]
this is great news. I was about to start translating it all...

**Comment by lpgn** [comment]
@pascalmoutet we would like to collaborate on the international version. I have setup the vm with fab-manager, thanks to @emj365 https://github.com/LaCasemate/fab-manager/pull/11. I dont see new commits on the dev branch. Private development? Anyway we would like to help. I am about to hard code a translation anyway. cheers

**Comment by lpgn** [comment]
@sylvainbx finish translating everything I think. cant find a place to change locale settings for the calendar...
