### ISSUE TITLE
Factures à 0€

### ISSUE THREAD

**Issue by simonmacias** [sleede/fab-manager#102]
Comptablement, la génération de factures à 0€ pose un problème. Il est impossible pour notre structure de laisser passer des factures nulles, posant des doutes sur de la bidouille de compte etc...
Y'a peut être possibilité de rajouter l'option de ne pas générer de factures pour les événements gratuits, offerts... ? 
Merci d'avance !

**Comment by sylvainbx** [comment]
Bonjour, quelqu'un a déjà soulevé ce problème sur le forum ([voir ici](https://forum.fab-manager.com/t/les-factures-a-zero/289)).

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/13/open-format-for-project-exchange).
