### ISSUE TITLE
Changement de nom de domaine et SSL...

### ISSUE THREAD

**Issue by simonmacias** [sleede/fab-manager#105]
Bonjour, 
Nous avons changé le nom de domaine de notre fabmanager de fablab.lesusinesnouvelles.com à ay128.lesusinesnouvelles.com... Jusque là tout va bien ! 
Le soucis c'est que les images présentes dans la galerie de projet pointent encore vers le vieux domaine ! Et qu'aucun certificat SSL n'est actif pour ce domaine... donc les images ne s'affichent pas ! 
La solution serait donc de générer deux certifs SSL letsencrypt (ay128 et fablab) mais je n'y arrive pas ! 
Merci de votre aide ! ;)

**Comment by jarod022** [comment]
Hello,
En cas de changement de domaine et si vous utilisez la base distante OpenProjects (ce qui est votre cas), vous devez nous alerter afin que nous modifions le nom de domaine d'origine sur notre base OpenProjects centralisée (ce que je viens de faire).
Normalement tout est ok à présent.
