### ISSUE TITLE
Bug de l'upload de .stl sur certains pc

### ISSUE THREAD

**Issue by bocal-chemille** [sleede/fab-manager#109]
Bonjour à tous,

Nous avons des bugs sur l'import de fichier .stl. Sur un ordinateur cela fonctionne bien (en utilisant chrome), et sur un autre, quelque soit le navigateur (firefox, explorer et chrome testés), le projet ou le fichier importé en question, l'import ne fonctionne pas et on obtient cette ligne d'erreur : 

![capture2](https://user-images.githubusercontent.com/39460901/40535474-84bfefb4-6009-11e8-896a-b588d645b015.PNG)

L'ordinateur tourne sous windows7 (comme l'autre avec lequel ça fonctionne), et on a vérifié dans les extensions supportées qu'il y avait bien le .stl... Si quelqu'un a une idée ?

Merci d'avance,
Vincent,
Le Boc@l

**Comment by sylvainbx** [comment]
Bonjour @bocal-chemille,
Dans ton fichier de variables d'environnement [env](https://github.com/LaCasemate/fab-manager/blob/master/docker/env.example), deux variables sont à configurer : `ALLOWED_EXTENSIONS` et `ALLOWED_MIME_TYPES`. Il est possible que le type mime soit manquant pour ton fichier.

Si tu ne sais pas quel type rajouter, pourrais-tu nous mettre le fichier incriminé ici et nous préciser avec quel logiciel celui-ci a été créé ?

**Comment by bocal-chemille** [comment]
Bonjour,
je met dans la boucle la personne qui s'occupe de notre Fab-Manager. Il
pourras répondre à  cela.

J'ai aussi envoyé un message à contact@fab-manager.com, pour savoir si il
était possible d'avoir la clé pour partager les projets avec les labs,
merci de me tenir informé !

Cordialement,

*Yvan GODREAU*
Animateur Socio-Culturel
yvan.godreau@centresocial-chemille.asso.fr

[image: http://centresocial-chemille.asso.fr/]
<http://centresocial-chemille.asso.fr/>

**Comment by sylvainbx** [comment]
Pas de réponse depuis plus de 6 mois ... Je clôture ce rapport de bug. Sens toi libre de le rouvrir si besoin.

**Comment by bocal-chemille** [comment]
Ok sinon un autre bug les images ne s'affichent pas sur les galeries
lorsque une structure extérieure hébergé fabmanager.

En fait il y a un espace créé dans l'URL de l'image qui fait qu'elle ne
s'affiche pas .

Pas contre lorsque nous mettons la galerie pour notre structure c'est ok

Cordialement

**Comment by sylvainbx** [comment]
Salut, je viens de corriger le problème d'espace dans l'URL pour OpenProject. La prochaine fois, merci d'ouvrir une issue séparée pour un problème séparé (peut-être que vous devriez aller directement sur GitHub plutôt que de répondre par mail, cela éviterait les erreurs de ce type). Bonne journée.

**Comment by bocal-chemille** [comment]
Merci, je crois avoir ajouté un issu sur le git hub.

Je vais le clore si tel est le cas !

Bonne année pleine de projets !

Cordialement
