### ISSUE TITLE
Open API example

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#110]
Hi all !
I want just try the openapi fontionnality but i've got credentials errors ;-/
here is my curl command :+1: 
```bash
curl --header "Accept: application/json" --header "Authorization: Token token=my_token_copied_via_admin_interface" https://ay128.lesusinesnouvelles.com/open_api/v1/events?page=1
```
And i've got this response 
`{"errors":["Bad credentials"]}`

Could you help me to find the right curl command ?
THX

**Comment by sylvainbx** [comment]
The following should work
```bash
curl -X GET \
  https://demo.fab-manager.com/open_api/v1/users \
  -H 'accept: application/json' \
  -H 'authorization: Token token=8MnqEm158jN8Qx7kaoW8QSQC'
```
Otherwise, check your authentication token

**Comment by julienrat** [comment]
Yes ! It works like a charm
THX again !
