### ISSUE TITLE
more data in open_api

### ISSUE THREAD

**Issue by simonjamain** [sleede/fab-manager#111]
Hi,
we want to build web apps on top of fabmanager dat. Currently we want to create a slideshow with members pictures, names and jobs.

The data output from the open_api is too poor, I don't have the fields that I need for that and I can't seem to guess the image url.
It seems like [this file](https://github.com/LaCasemate/fab-manager/blob/master/app/views/open_api/v1/users/_user.json.jbuilder) is responsible for presented data, can you modify it to display more data (or maybe can I make a pull request) ?
Thank you and have a good day.

**Comment by sylvainbx** [comment]
Hi,
Thanks for your interest in fab-manager. You're welcome to make a pull request on the [dev branch](https://github.com/LaCasemate/fab-manager/tree/dev) for this feature as long as you do not make any breaking change in the current open API.

You can gather inspiration for this feature in [api/members/show.json.jbuilder](https://github.com/LaCasemate/fab-manager/blob/dev/app/views/api/members/show.json.jbuilder).

Do no forget to update the API doc accordingly in [app/doc/open_api/v1/users_doc.rb](https://github.com/LaCasemate/fab-manager/blob/dev/app/doc/open_api/v1/users_doc.rb).

Good luck ;-)

**Comment by simonjamain** [comment]
Thanks a lot I will do that
