### ISSUE TITLE
Utilisateur structure

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#115]
Il serait utile de pouvoir modifier un compte utilisateur en le transformant en structure. Actuellement on peut s'enregistrer comme structure mais il n'est pas possible de le modifier par la suite. Cela pourrait être utile par exemple pour un créateur qui ouvre son entreprise quelques temps après son inscription ou tout simplement pour corriger un oubli.

Guillaume
Les Copeaux Numériques

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/20/open-format-for-project-exchange).
