### ISSUE TITLE
Faire apparaitre les événements dans la gestion du calendrier

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#116]
Par soucis de lisibilité, il serait utile de voir les événements dans la vue gestion du calendrier. Cela éviterait les éventuels chevauchements lors de la création des créneaux machines ou formations.

Guillaume
Les Copeaux Numériques

**Comment by EmmanuelG** [comment]
Cela serait effectivement intéressant :)

Emmanuel
FabLab du Dôme

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/39/open-format-for-project-exchange).

**Comment by EmmanuelG** [comment]
Je vois que cette fonction est implémenté dans la version 4.3, cool !
Mais cela n'apparait pourtant pas dans notre instance du Dôme (v 4.3.4) : /
