### ISSUE TITLE
[Bug] Subscription with 12 monthly payments can not be created

### ISSUE THREAD

**Issue by Rojo** [sleede/fab-manager#117]
Trying to create year wide with monthly (12) payments subscription, the subscription fails to be created.

To report a bug, please describe:
- Expected behavior and actual behavior.
*Expected Behaviour:* A subscription with `Period: Month` and `Number of periods: 12` --that would be the configuration for a subscription of a duration of a year with 12 monthly payments-- is created.

*Actual  Behaviour:* The request fails with the non-specific message `unprocessable entity`. 

- Steps to reproduce the problem.

Fill the new subscription plan form with the following values (among the required ones) and try to save:
    - `Period: Month`
    - `Number of periods: 12`

- Specifications like the version of the project, operating system, or hardware.

Fablab version: 2.6.4

I think it is because of this restrains: https://github.com/LaCasemate/fab-manager/blob/master/app/models/plan.rb#L30-L31

If I'm not mistaken, the model should allow to define an `interval_count` of `12` for `month` and of `52` for weeks.

**Comment by sylvainbx** [comment]
Hi @Rojo,
thanks for reporting this but I think this is a non-issue. Indeed, stripe api for subscriptions has some restrictions ([see here](https://stripe.com/docs/api#create_plan-interval_count)). I don't exactly remember what was the problem but I think that allowing the creation of a 12 month plan made an issue with stripe payment renewal so we only allow 1 year plans created with `Period: Year, Number of period: 1`. Can you confirm this works that way? Or do you have a specific work case?

**Comment by Rojo** [comment]
@sylvainbx Thanks for your response.

Seems that I need to review the documentation to understand better how the lifecycle of subscriptions works with Stripe as what I was trying to configure may have a different result than I was expecting.

Nevertheless, from the link to these params it seems that 1 year, 12 months and 52 weeks are the maximum values permitted by Stripe for interval count on plans, but did not find notes about not using these values.

**Comment by sylvainbx** [comment]
Yes, as I said before, I don't remember what was the exact problem, but I belive it was an internal limitation in fab-manager because if you set `Month:12` or `Week:52` there was a problem with something... 
Why can't you be satisfied with `Year:1`, I don't understand what is your use case?

**Comment by Rojo** [comment]
I was trying to define a year-long subscription with monthly charges, so, I thought it would work by defining a `month` interval with an interval count of `12`.

**Comment by sylvainbx** [comment]
Hmm, no this won't work that way. 
You will need to fork the project, remove [this line of code](https://github.com/LaCasemate/fab-manager/blob/master/app/models/subscription.rb#L93), and create a 1 month subscription.
Then maybe create a new field in the subscription model (eg. will_expire_at), and extend/modify [subscription_expire_worker.rb](https://github.com/LaCasemate/fab-manager/blob/master/app/workers/subscription_expire_worker.rb) to cancel the stripe subscription at the given date. 
Anyway, creating a 12 months plan shouldn't help ... ;)

**Comment by Rojo** [comment]
OK. It is good to know about it. Then, I'm closing this issue.
Thanks, @sylvainbx
