### ISSUE TITLE
Projets du FabLab qui n'apparaissent pas

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#119]
Bonjour,

   on cosntate un problème depuis deux mises à jour, c'est que les projets du FabLab actifs n'apparaissent pas dans "Les projets du FabLab" alors que les projets de tout les autres FabLab apparaissent sans problèmes.
Il y a une commande pour re-générer cette page ?

Slts

**Comment by sylvainbx** [comment]
Salut, c'est très probablement lié à [ton problème d'elasticsearch](https://github.com/LaCasemate/fab-manager/issues/118) ...
