### ISSUE TITLE
Add ability to remove an user

### ISSUE THREAD

**Issue by Booteille** [sleede/fab-manager#120]
Hi.

We can't find where we can, as an administrator, remove or block users from our database.

Would it be possible to add those both features on FabManager, please?

Thanks!

**Comment by sylvainbx** [comment]
Hi Booteille,

We've planned to do this for the GDPR-compliance release, maybe before the end of the year. In the meantime, you can block an user to prevent him from connecting to fab-manager using the console :

```bash
docker exec -it fabmanager_fabmanager_1 bash
bundle exec rails console
User.find_by(email: "toto@gmail.com").update_attributes(is_active: false)
```

After that, he won't be able to connect anymore to the platform and his account will be invisible to anyone except admins.

**Comment by Booteille** [comment]
Hi!

Thanks for your answer. We'll wait this release, then. I hope it'll not come too late. Good luck with this work!

Just one thing. I tried your tip to block an user but I have a `Wrong number of arguments` error. Here are the logs:

```console
irb(main):002:0> User.find_by(email: "xx@xx.xx").update_attribute(is_active: false)
  User Load (1.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "xx@xx.xx"]]
  User Load (1.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "xx@xx.xx"]]
ArgumentError: wrong number of arguments (given 1, expected 2)
        from /usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/persistence.rb:237:in `update_attribute'
        from (irb):2
        from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

Any idea about why I get this one? What is the second argument expected?

**Comment by sylvainbx** [comment]
Oops, that's my fault, the correct query is:
```ruby
User.find_by(email: "toto@gmail.com").update_attributes(is_active: false)
```

(I've edited the original comment)

**Comment by Booteille** [comment]
It worked! Thanks!

**Comment by sylvainbx** [comment]
From [release 4.0.0](https://github.com/sleede/fab-manager/releases/tag/v4.0.0), you can now really delete any account. During the deployment, when you launch the command `rake fablab:maintenance:delete_inactive_users`, it will delete the users that had previously marked their account as "deleted".
