### ISSUE TITLE
Inactive subscription still appear in public page

### ISSUE THREAD

**Issue by siteswapjuggler** [sleede/fab-manager#122]
Hi,

we change our subscription formula in september, old ones are declared inactive but they still show in the public page which is quiet a mess for our user.

Is this an intended behaviour or should I consider this as unexpected, if so I could start working on a fix ?

Sincerely
Sylvain

**Comment by sylvainbx** [comment]
Hi,
This looks like a bug to me ... but strangely I cannot reproduce it.
Which version of fab-manager are you using?

**Comment by siteswapjuggler** [comment]
Good question it's the one of "Le Dome" and it should be hosted on the sleed server if my informations are good, so I assume it's the last version available. Perhaps it's related to the fact that some user are still linked to the old formulas ?

**Comment by sylvainbx** [comment]
Your informations seems correct :)
If you feel confortable with the code do not hesitate to check it for the issue, otherwise I'll take a look at it, in the next days.

**Comment by siteswapjuggler** [comment]
Ok I feel confortable enough with the code but I will be very busy in the next few days. Let's say that the first one able to found time to work on it will post updates in this thread ?

**Comment by siteswapjuggler** [comment]
Ok I feel confortable enough with the code but I will be very busy in the next few days. Let's say that the first one able to found time to work on it will post updates in this thread ?

**Comment by siteswapjuggler** [comment]
So I didn't found the time to work on the problem yet but my collegue has found out new clues : 
- when connected as user without subscription, it's ok
- when connected as admin, not connected, connected as user with a subscription, it prompt everything

**Comment by sylvainbx** [comment]
I just took a look at the issue but I wasn't able to reproduce it. It tried many scenarios : connected as admin, connected as user without subscription and connected as user with subscription. All scenarios with and without users in the hidden plan ... all works great.

**Comment by sylvainbx** [comment]
Ok, I've just looked at the configuration of https://fablab.ledome.info and maybe I'm understanding your problem now... What you're talinkg about is not the plans, I guess you're talking about the groups (titles in the subscription page). So if you want to remove them, you'll have to go to *manage users > groups* and click on *disable* on each obsolete group.
Can you confirm this answsers your issue?

**Comment by siteswapjuggler** [comment]
Ok I'm understanding better now, so definitively not a bug. I'm still trying to figure out a solution, the fact is the previously created groups are still associated with user account so we cannot deactivate them neither can we change manually each user.

Perhaps a good way to deal with it is :
- authorise group deactivation even if user are still associated with it (perhaps not so practical from a database point of view)
- dissociate "(de)activation" from a "(un)available" option

In a way or another we should find a way to facilitate migration of plans and groups when the tarifications politic change.

Perhaps a quick fix will be to make a macro to change every old groups user to new ones. Let me know the best for you.

**Comment by sylvainbx** [comment]
We cannot allow disabling a group which has any users inside it: it creates many undesirable side effets on the whole app. We also cannot automate group changing, because: changing the group of a user which has a running subscription leads to side effects and even billing errors.
The best we can do is to script the group change of users which have no subscription. This can be achieved using the rails console:
```bash
docker exec -it fabmanager_fabmanager_1 bash
RAILS_ENV=production bundle exec rails console
```
First, spot the IDs of the groups you want to disable and the destination groups
```ruby
Group.all.map{|g| "#{g.id}: #{g.name}"}
```
Then move all users without subscription to the new group (eg. from group ID 4 to group ID 1)
```ruby
User.with_role(:member).each do |u|
  if !u.subscription and u.group_id == 4
    u.update_attributes(group_id: 1)
  end
end
```
For the remaining users, you'll have to wait for their subscription to expire to change their group.
Keep me updated.

**Comment by sylvainbx** [comment]
Closing this, as there was no updates for two months. Feel free to reopen if needed.
