### ISSUE TITLE
Add possibility to cancel an event reservation

### ISSUE THREAD

**Issue by siteswapjuggler** [sleede/fab-manager#123]
The problem occure quiet often in our Fablab, People want to cancel their participation to an event but they cannot do it either could we as admin.

So our only choice is to keep a manual list of cancellation aside from Fabmanager and to add new places in the event to compensate the freed places inducing false stats and an error risk.

**Comment by sylvainbx** [comment]
Yes, I know this limitation. I started to work on the subject a year ago just before v2.4.3 but this is pretty complicated and need a lot of time to achieve this. 
If you want to try to work on this subject I can publish my work on a separate branch (it is private for the moment). Let me know if you're interested in?

**Comment by sylvainbx** [comment]
Tracking this new feature request is now done on [the website dedicated to the Fab-Manager's roadmap](https://roadmap.fab-manager.com/posts/42/open-format-for-project-exchange).
