### ISSUE TITLE
[RESOLVED] [(not a) BUG] Impossiblilité de créer une formule d'abonnement.

### ISSUE THREAD

**Issue by thewenneur** [sleede/fab-manager#124]
Bonjour, 
En tant que SysAdmin du FabLab de Vendôme, j'ai mis à jour récemment notre site avec Fab Manager. 
Voici le problème : Il est impossible de créer un nouvel abonnement. Une fois le formulaire remplis, quand on clique sur enregistrer, Une PopUp d'erreur s'affiche en haut à gauche : "L'abonnement n'a pas pu être créé. Veuillez réessayer.". Même un formatage du VPS et une réinstalation complète de Fab Manager ne résout se problème.
![image](https://user-images.githubusercontent.com/26489501/47266604-3e4ebd80-d539-11e8-9fa2-0a2d38057a75.png)

**Comment by sylvainbx** [comment]
Bonjour @thewenneur, c'est étrange, je ne reproduis pas ce problème chez moi.
Pourrais-tu me donner le résultat de la commande `tail -f /apps/fabmanager/log/app-stdout.log` lorsque tu crées une formule d'abonnement ?

**Comment by thewenneur** [comment]
Merci, grâce à ta demande, j'ai vu mon erreur : j'avais inversé la public key et la private key de stipe (les deux installs apparemment). TY :)
