### ISSUE TITLE
créneaux non visibles

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#127]
Bonjour,
Ici Emmanuel, je m'occupe du FabLab du Dôme, dont l'instance FabManager est gérée par Sleed.

Depuis 2 jours environs la vue du calendrier en mode "jour" n'affiche plus aucun contenu, alors que les vues "semaine" et "mois" sont ok.

De manière similaire mais plus gênante, quand un usager souhaite réserver une machine, les créneaux horaires ne sont plus visibles. Par exemple, pour une personne habituée à utiliser la machine A les disponibilités ou réservations de celle-ci ne s'affichent plus du tout (alors que d'autres machines apparaissent correctement).
J'ai vérifié cela avec 3 personnes différentes, essayant de réserver l'une ou l'autre de nos découpeuse laser, pour des créneaux habituellement accessibles pour eux (sans restriction d'étiquette, et ayant la formation requise).

**Comment by sylvainbx** [comment]
Bonjour,

La [version 2.8.3](https://github.com/LaCasemate/fab-manager/releases/tag/v2.8.3) qui vient d'être publiée devrait résoudre le problème. Nous allons mettre à jour les instances hébergées par Sleede dans la journée.

**Comment by karliwalti** [comment]
I would like to reopen this ticket as it is still happening on new installations (latest docker 5.1.6):

![image](https://user-images.githubusercontent.com/4565568/132642706-c19c0be9-e5a4-447e-8176-56c801edd225.png)

**Comment by gnepud** [comment]
Hi @karliwalti

Could you open a new issue with more information ?
Do you have create slot in Admin => Calendar for your machine ?

Thanks

**Comment by karliwalti** [comment]
@gnepud you are right, with reinstallation those entries were lost. please ignore my previous post
