### ISSUE TITLE
Account Deleting Error

### ISSUE THREAD

**Issue by thewenneur** [sleede/fab-manager#129]
When you try to delete an account, the email is still in database, thus we can't re-create the account (for debug/reset purposes).

Fabmanager lastet version on Ubuntu 16.04 LTS with docker 1.11.2 & docker-compose 1.23.2

**Comment by sylvainbx** [comment]
This is an expected behavior. We're working on this for the ongoing release.

**Comment by thewenneur** [comment]
Thanks.

**Comment by sylvainbx** [comment]
From [release 4.0.0](https://github.com/sleede/fab-manager/releases/tag/v4.0.0), you can now really delete any account. During the deployment, when you launch the command `rake fablab:maintenance:delete_inactive_users`, it will delete the users that had previously marked their account as "deleted".
