### ISSUE TITLE
Accepter plus de formats de fichiers

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#130]
Bonjour,

Certains usagers de notre atelier nous font remonter régulièrement que les formats de fichiers acceptés (pour publier un projet) sont trop restreints. Si l'on compare à d'autres plateforme comme Thingiverse par exemple.
Cela oblige à héberger un fichier (.ino par exemple) ailleurs et mettre un lien à la place. Ce qui éclate les données et la documentation.

**Comment by sylvainbx** [comment]
Bonjour,

Les fichiers acceptés en pièce jointe d'un projet sont configurables via les variables d'environnement ALLOWED_EXTENSIONS et ALLOWED_MIME_TYPES. [Voir la documentation relative ici](https://github.com/LaCasemate/fab-manager/blob/master/doc/environment.md#general-settings).
