### ISSUE TITLE
Statistiques dans les choux ?

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#131]
Instance : FabLab du Dôme à Caen (hébergement Sleede)

Contexte : nous cherchons à vérifier le taux d'occupation des équipements

Problème : lorsqu'on compare le calendrier aux statistiques exportées (tableau "Disponibilités"), il n'y a pas de lien logique entre ce que l'on observe et le fait qu'un créneau soit considéré comme "0" ou "1" dans la colonne "réservation".

Parfois les créneaux occupés sont à 1, parfois à 0 et inversement.
Les données exportées ne sont donc pas ou plus utilisables en l'état.

**Comment by sylvainbx** [comment]
Bonjour Emmanuel,

Je ne comprend pas du tout ton problème ...
Est-ce que tu parles de l'export des réservations (dans **Gérer les utilisateurs**) ou de l'export des statistiques (dans **Statistiques**) ?
Dans les deux les cas, il n'y a toutefois pas de colonne "réservation" et les dates sont celles de la commande et non du créneau réservé ...

Dans l'attente de ton retour,
Bonne journée,

**Comment by EmmanuelG** [comment]
Bonjour Sylvain,

Il s'agit de l'export depuis l'onglet "Gérer le calendrier" avec le bouton "Disponibilités".

Dans le cas de l'export depuis l'onglet "Statistiques" j'avais déterminé qu'il s'agissait en effet des commandes. Autrement je n'ai pas encore joué avec les exports depuis la partie "Gérer les utilisateurs".

Bien à toi :)

**Comment by sylvainbx** [comment]
Salut, je viens de pousser un correctif dans https://github.com/sleede/fab-manager/commit/26b901ebb5dad7acb29bacf0c064f600158f5619. Ce sera disponible pour la prochaine release (sans doute 3.2.0).
Merci d'avoir remonté le bug :)

**Comment by EmmanuelG** [comment]
Super :)

**Comment by EmmanuelG** [comment]
En me replongeant dans les stat hier je pense avoir trouvé un autre bug.

Cas de figure : j'avais été surpris de voir que pour le premier trimestre 2019 il y avait eu plus d'inscrits à une formation que de places ouvertes (11 inscrits, 9 places).

Déduction : en allant compter "à la main" depuis la vue calendrier j'ai pu vérifier (11 inscrits, 9 places, 2 annulations où quelqu'un s'est positionné sur la place libérée) et formuler l'hypothèse suivante : le module **Statistiques** ne soustrait pas les annulations dans son comptage de créneaux réservés (heure machine, formation).

J'ai pu confirmer ça avec plusieurs autres créneaux et périodes.
