### ISSUE TITLE
UsersExportWorker not working

### ISSUE THREAD

**Issue by flaviobogila** [sleede/fab-manager#132]
The export users proccess is not working, i can't find the problem.

The error is: ActionView::Template::Error: undefined method `name' for nil:NilClass

![image](https://user-images.githubusercontent.com/13349643/58201932-b38b9800-7cac-11e9-8998-5ba3b4f26703.png)

Could you please help me?

**Comment by alexcvcoelho** [comment]
Hi @flaviobogila 

Check if don' t have any user without `group`, this error could be generating in archive `users_members.xlsx.axlsx` on line 55.

**Comment by sylvainbx** [comment]
Can you run the following commands and report the results here:
```bash
docker exec -it fabmanager_fabmanager_1 bundle exec rails c
```
then, once in the console:
```ruby
Export.find(152)
User.with_role(:member).where(group: nil).count
```

**Comment by flaviobogila** [comment]
The results was 1, however I remove this user with empty group but the problem continues. there is something more that I could to do?

**Comment by sylvainbx** [comment]
Have you tried to update your instance to v4 or above to see if it fixes the issue?
