### ISSUE TITLE
Réservations bloquées après v3

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#135]
Bonjour,

Après mise à jour vers la dernière version 3.1.2, toutes les transactions se trouvent bloquées, pour les utilisateurs comme pour l'admin. C'est complètement paralysant.
Le déroulement de l'upgrade c'est bien passé en respectant le TODO. D'où cela peut-il venir ? 

Cordialement
Guillaume 
Les Copeaux Numériques

**Comment by Guillaume89** [comment]
Plus possible non plus d'éditer l'onglet "A propos" et "Page d'accueil" !!
Help !

**Comment by sylvainbx** [comment]
J'avais oublié de préciser qu'il fallait lancer la commande `rake db:migrate` dans la liste des commandes de migration de la version 3.0.0. J'ai corrigé les instructions.
