### ISSUE TITLE
Impossible d'ajouter un utilisateur manuellement

### ISSUE THREAD

**Issue by matteli** [sleede/fab-manager#136]
Bonjour,

J'ai installé fab manager aujourd'hui comme préconisé sur la doc donc j'imagine que j'ai la dernière version à ce jour.

L'installation s'est bien passée mais lorsque j'essaye de rajouter un simple membre par l'interface admin, j'ai une erreur 500.
Dans le log app-stdout.log j'ai

```
NoMethodError (undefined method `id' for nil:NilClass):
  app/services/members/members_service.rb:38:in `create'
  app/controllers/api/members_controller.rb:46:in `create'
```

A noter que l'ajout d'un administrateur ne pose pas de problème et que l'on peut s'inscrire par la page d'acceuil.

Merci pour votre aide et travail.

Matthieu

**Comment by matteli** [comment]
# #

**Comment by sylvainbx** [comment]
Salut @matteli ,
Peux-tu essayer de [faire la mise à jour](https://github.com/sleede/fab-manager/blob/master/docker/README.md#update-fabmanager) vers la [version 4.0.3](https://github.com/sleede/fab-manager/releases/tag/v4.0.3) ? Il est probable que cela résolve ton problème car j'ai corrigé un bug similaire dans cette version.
Tiens nous au courant,

**Comment by matteli** [comment]
Salut,
Problème résolu.
Merci
