### ISSUE TITLE
taux de TVA erroné

### ISSUE THREAD

**Issue by fablab127** [sleede/fab-manager#140]
Bonjour,

j'aimerai signaler un problème sur la partie facturation du fabmanager:

Lors de la génération d'un avoir le taux de TVA est erroné.
En effet sur la facturation le taux est bien de 20% (voir image suivante issue des paramètres de facturation):
![image](https://user-images.githubusercontent.com/29604409/62937390-c81f8e00-bdcc-11e9-83e1-edb0a10d5f64.png)

Mais lors de la génération d'un avoir il passe à 0.2%:
![image](https://user-images.githubusercontent.com/29604409/62937356-ade5b000-bdcc-11e9-8ec1-0ffbca6888d6.png)

Cela entraine un problème comptable évident, il y a t'il une configuration des paramètres d'avoir dont je ne suis pas au courant? Si non, comment faire pour résoudre le problème et corriger les avoirs antérieurs?

Merci d'avance pour votre aide.

**Comment by jarod022** [comment]
Le bug vient d'être corrigé sur la version 4.0.4
Je viens de mettre à jour votre instance et de re-générer vos avoirs/factures PDF erronés.

**Comment by fablab127** [comment]
Super, merci beaucoup pour votre réactivité.
Est-il possible de re-générer également les avoirs 190700359/A à 190700366/A sur lesquels le bug était déjà présent?

**Comment by sylvainbx** [comment]
Ces avoirs ont déjà été régénérés ;)
