### ISSUE TITLE
Update Ruby dependency from 2.3.6 to 2.3.8

### ISSUE THREAD

**Issue by Rojo** [sleede/fab-manager#143]
The latest release of this unmaintained branch of Ruby was 2.3.8. Which include [security fixes](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/).

The project should at least use this version while it is considered to make changes to use a version of Ruby that is still maintained.

**Comment by sylvainbx** [comment]
Hi Rojo, thanks for noticing us about this. I will proceed to the upgrade for the next release

**Comment by sylvainbx** [comment]
The production version already uses ruby 2.3.8, only development environement are using 2.3.6.

**Comment by Rojo** [comment]
@Rojo Nice, I'll update my PR for note sync this change with the virtual env.

**Comment by sylvainbx** [comment]
Perfect! I've merged your PR and published [a release](https://github.com/sleede/fab-manager/releases/tag/v4.1.0) with all these changes just now. Thanks for contributing ;)
