### ISSUE TITLE
Use Alpine Linux as Docker base image

### ISSUE THREAD

**Issue by Rojo** [sleede/fab-manager#144]
Alpine Linux is both smaller and faster than regular images. A lot of projects that use Docker are supporting it. It may help to improve a little the use of resources with Fab Manager.

**Comment by sylvainbx** [comment]
Thanks, i'll give it a try

**Comment by Rojo** [comment]
@sylvainbx I have some advances on this. Would you like me to share them with a PR?

**Comment by sylvainbx** [comment]
Sorry, I was occupied with strong-customer authentication these last days. Your PR is welcome, I'll give it a test from tomorrow. Keep me updated

**Comment by sylvainbx** [comment]
Starting from [release 4.2.0](https://github.com/sleede/fab-manager/releases/tag/v4.2.0) we'll be using Alpine linux thanks to your contribution. Nice job!
