### ISSUE TITLE
Crédits qui ne s'ajoutent pas suite à la prolongation d'un abonnement

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#145]
En version 3.1.2 auto-hébergé.

Un utilisateur a épuisé ses crédits d'abonnement pour des réservations d'espaces. Avant son expiration nous prolongeons son abonnement d'un mois supplémentaire mais les crédits qui y sont liés ne sont pas reporté sur le compte de l'utilisateur. La facture est bien générée cependant.
 
Étrange n'est-ce pas ?

Merci 

Guillaume
Les Copeaux Numériques

**Comment by sylvainbx** [comment]
Bonjour,

Avez-vous utilisé l'option "Prolonger l'abonnement" ou l'option "Offrir des jours gratuits" pour prolonger l'abonnement de l'utilisateur (ou autrement) ?

Merci pour ces précisions,
Bonne journée,

Sylvain

**Comment by Guillaume89** [comment]
C'est la fonction "Prolonger l'abonnement" qui a été utilisée.

Merci pour ta réactivité

Guillaume

**Comment by sylvainbx** [comment]
Bonjour, 
C'est corrigé dans la [version 4.1.0](https://github.com/sleede/fab-manager/releases/tag/v4.1.0), publiée à l'instant.
Bonne journée
