### ISSUE TITLE
Avalanche de notifications

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#148]
Bonjour,

En version 4.1 auto-hébergée.

Les notifications mentionnant les abonnements expirés ou approchant de l'expiration sont répétées 8 fois par jour. Les autres notifications ne sont pas touchées. Hormis le fil de notifications qui se trouve surchargé, ce n'est pas trop gênant en soi. Mais peut-être que les usagers sont tout autant notifiés par mail et il semble de toute façon que quelque chose tourne en rond.

Ou bien j'ai loupé une étape dans la mise à jour depuis la 3.1.2 même si je prends toujours soin de suivre les TODO DEPLOY à la lettre.

Guillaume
Les Copeaux Numériques

**Comment by sylvainbx** [comment]
Salut Guillaume, 

C'est très étrange ... est-ce que cela s'est produit une seule fois ou est-ce que ça se répète tous les jours ?

Normalement ce genre de notification est programmée pour s'exécuter une seule fois par jour, tous les jours. À minuit pour les notifications sur abonnements qui expirent dans 7 jours et à 23h pour les abonnement qui viennent d'expirer le jour même. 

Si tu pouvais me dire à quelle heure sont envoyées les notifications, ainsi que les retour de ces deux commandes :
```bash
docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_expire_in_7_days:jid_history 0 -1
docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_is_expired:jid_history 0 -1
```

**Comment by Guillaume89** [comment]
Salut Sylvain,

Par exemple hier 15 septembre : 

> L'abonnement de Cédric D.  est arrivé à expiration.
répété à 11h56, 16h04, 23h00.

`docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_expire_in_7_days:jid_history 0 -1`
renvoie
```
1) "{\"jid\":\"8af3e7233dfa4d97b17b9c48\",\"enqueued\":\"2019-09-15 22:00:04 +000
0\"}"
2) "{\"jid\":\"0a05eb5bef31c76c4ce11c4c\",\"enqueued\":\"2019-09-14 22:00:02 +000
0\"}"
3) "{\"jid\":\"8ef32caa8382d60cbd08a463\",\"enqueued\":\"2019-09-13 22:00:04 +000
0\"}"
4) "{\"jid\":\"d68b46b1fa71b505c5db5c86\",\"enqueued\":\"2019-09-12 22:00:30 +000
0\"}"
```
`docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_is_expired:jid_history 0 -1`
renvoie
```
1) "{\"jid\":\"a0fd4df038951b56593e1b03\",\"enqueued\":\"2019-09-15 21:00:21 +000
0\"}"
2) "{\"jid\":\"4e14f2fa4d4bfe255e34d947\",\"enqueued\":\"2019-09-14 21:00:05 +000
0\"}"
3) "{\"jid\":\"f71c78b2defa93e88947849e\",\"enqueued\":\"2019-09-13 21:00:15 +000
0\"}"
4) "{\"jid\":\"2d6b5826ff9ea95cb08e57ec\",\"enqueued\":\"2019-09-12 21:00:07 +000
0\"}"

```

**Comment by Guillaume89** [comment]
Salut Sylvain,

Par exemple le 15 septembre : 

> L'abonnement de Cédric D.  est arrivé à expiration.
répété à 11h56, 16h04, 23h00.

`docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_expire_in_7_days:jid_history 0 -1`
renvoie
```
1) "{\"jid\":\"8af3e7233dfa4d97b17b9c48\",\"enqueued\":\"2019-09-15 22:00:04 +000
0\"}"
2) "{\"jid\":\"0a05eb5bef31c76c4ce11c4c\",\"enqueued\":\"2019-09-14 22:00:02 +000
0\"}"
3) "{\"jid\":\"8ef32caa8382d60cbd08a463\",\"enqueued\":\"2019-09-13 22:00:04 +000
0\"}"
4) "{\"jid\":\"d68b46b1fa71b505c5db5c86\",\"enqueued\":\"2019-09-12 22:00:30 +000
0\"}"
```
`docker-compose exec redis redis-cli lrange fablab:cron_job:subscription_is_expired:jid_history 0 -1`
renvoie
```
1) "{\"jid\":\"a0fd4df038951b56593e1b03\",\"enqueued\":\"2019-09-15 21:00:21 +000
0\"}"
2) "{\"jid\":\"4e14f2fa4d4bfe255e34d947\",\"enqueued\":\"2019-09-14 21:00:05 +000
0\"}"
3) "{\"jid\":\"f71c78b2defa93e88947849e\",\"enqueued\":\"2019-09-13 21:00:15 +000
0\"}"
4) "{\"jid\":\"2d6b5826ff9ea95cb08e57ec\",\"enqueued\":\"2019-09-12 21:00:07 +000
0\"}"

```

**Comment by sylvainbx** [comment]
Salut, c'est bizarre, les tâches ont l'air de s'être exécutées au bon moment.
Peux-tu me donner le retour de la commande suivante ?
```
grep -B 4 "Subject: =?UTF-8?Q?L'abonnement_d'un_membre_est_arriv=C3=A9_=C3=A0_expira?=" /apps/fabmanager/log/worker-stdout.log | sed 's/To: [^\@]*/To: xxxxx/g'
```

**Comment by Guillaume89** [comment]
Salut,

Bizarre en effet, nous n'avons plus cette répétition de notifications. Je te joins un fichier texte avec le retour de la commande grep. J'ai fait un fichier à part vu le nombre de lignes. Peut-être qu'il y a quelque chose de louche tout de même dedans. 

Merci en tout cas d'avoir chercher. Ici le problème semble s'être résolu tout seul...
[issue notifications grep.txt](https://github.com/sleede/fab-manager/files/3690781/issue.notifications.grep.txt)

**Comment by sylvainbx** [comment]
Salut Guillaume, 
Bon c'est très étrange comme problème, peut-être quelque chose qui a foiré dans sidekiq, dans tous les cas c'est très difficile à débugger. Si ça s'est résolut chez toi, tant mieux. 
Je vais clôturer cette issue, n'hésitez pas à la rouvrir si toi ou quelqu'un d'autre rencontre ce même problème.
Bonne journée,
