### ISSUE TITLE
locale files for english not avaiable

### ISSUE THREAD

**Issue by lpgn** [sleede/fab-manager#15]
I tried to find on the directory and github. I couldn't find a english version of summernote, and select2_locale_en

Should I translate those as well?
- summernote/lang/summernote-en-US
- select2/select2_locale_en
- moment/locale/en

**Comment by sylvainbx** [comment]
No, you don't have to, English is the default translation for these plug-ins, so just removing the inclusion in `application.js` will turn the plug-ins language to English.

This was fixed in [this commit](../commit/b736e5443863a16bdbbd28115ff20828457dc8cc).
