### ISSUE TITLE
Vue calendrier incomplète

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#151]
Re,

Depuis le passage à la v4.1, la vue calendrier n'affiche plus que certains créneaux. Que ce soit comme admin ou comme utilisateur. Le calendrier est vide sur un mois avant de retrouver quelques créneaux ouverts. Et il semblerait que ce soit des créneaux ouverts avant la mise à jour vers la 4.1 qui s'affichent. 

Les vues réservations et gestion du calendrier ne sont pas affectées. Tous les créneaux sont là.

Le passage à la v4.1.1 n'a pas corrigé le soucis. 

Peut-être un oubli de commande pendant la procédure de MAJ ?

Merci pour vos retours.

**Comment by sylvainbx** [comment]
Bonjour Guillaume,
C'est bizarre car je n'ai pas du tout ce comportement chez moi, d'autant qu'aucun changement n'a été réalisé sur le calendrier ou les créneaux depuis un moment. Tu pourrais coller ici le retour de la requête à /api/availabilities/public (faire Ctrl+Maj+i dans le navigateur puis onglet Network, juste avant de visiter la page Calendrier) ?

Note que si ça te retourne juste une "erreur 500: internal server error", colle plutôt les logs serveur qui apparaissent au moment de la requête, avec `tail -f /apps/fabmanager/logs/app-stdout.log`

**Comment by Guillaume89** [comment]
Sylvain,

Effectivement : erreur 500 !

Donc dans les logs il apparait ceci pour ce qui concerne l'erreur 500 :

Completed` 500 Internal Server Error in 119ms (ActiveRecord: 50.3ms | Elasticsearch: 0.0ms)
  Reservation Load (0.2ms)  SELECT "reservations".* FROM "reservations" INNER JOIN "slots_reservations" ON "reser
vations"."id" = "slots_reservations"."reservation_id" WHERE "slots_reservations"."slot_id" = $1  [["slot_id", 369
4]]

NoMethodError (undefined method `user_id' for #<Reservation:0x0000557813010a28>):
  app/services/availabilities/status_service.rb:85:in `map'
  app/services/availabilities/status_service.rb:85:in `reserved_availability?'
  app/services/availabilities/public_availabilities_service.rb:93:in `block in public_availabilities'
  app/services/availabilities/public_availabilities_service.rb:89:in `public_availabilities'
  app/controllers/api/availabilities_controller.rb:32:in ``public'

Est-ce que ces infos te suffisent pour y voir plus clair ?

Merci à toi !

**Comment by sylvainbx** [comment]
Salut,
Tu viens de trouver un bug, félicitations :) 
C'est uniquement lié au module des espaces, que j'ai sans doute tendance à sous-tester un peu... bizarre quand même que ça soit apparu avec la 4.1, le problème aurait du survenir dès la v 4.0.
Dans tous les cas, je corrige ça et je te tiens au courant dès que le correctif est disponible.
Bonne journée

**Comment by sylvainbx** [comment]
Le problème a été corrigé avec la [release 4.2.0](https://github.com/sleede/fab-manager/releases/tag/v4.2.0).
