### ISSUE TITLE
Document Invoice Configuration Issue

### ISSUE THREAD

**Issue by Rojo** [sleede/fab-manager#152]
Recently I ran into a problem where the invoices where not being generated due to the image included in the invoice header not being supported. Fortunately, I was able to find this [thread](https://forum.fab-manager.com/t/resolu-erreur-generation-facture/428) and changing the image solved the issue, but it required a lot of research and debugging trying to identify the cause.

Therefore, I think it would be a good idea to include the problem in the `known issues` section of the README or/and in the instance set up instructions to enable payments.

**Comment by sylvainbx** [comment]
Well seen! 
I'll update the README for the next release. Thanks for the suggestion.

**Comment by sylvainbx** [comment]
This is fixed with [release 4.2.0](https://github.com/sleede/fab-manager/releases/tag/v4.2.0).
