### ISSUE TITLE
Bornage des abonnements

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#153]
Bonjour, 

Nous avons le cas d'utilisateurs qui réservent en étant abonné des créneaux d'espaces via leur crédit mais sur des périodes où ils ne seront plus abonnés. Il faudrait pouvoir borner les abonnements pour des réservations possible uniquement pendant la période de validité.

Peut-être à se rajouter dans le road-map ?

Guillaume
Les Copeaux Numériques 
v4.1.1 auto-hébergé

**Comment by sylvainbx** [comment]
Salut Guillaume, 
Je l'ajoute à la liste des évolutions demandées.

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/11/open-format-for-project-exchange).
