### ISSUE TITLE
Error in user creation

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#154]
Hello,

   we have errors in users creation : 

`==> log/app-stdout.log <==
Started POST "/api/members" for 176.145.84.138 at 2019-10-25 06:37:55 +0000
Processing by API::MembersController#create as JSON
  Parameters: {"user"=>{"profile_attributes"=>{"id"=>"", "user_avatar_attributes"=>{"id"=>""}, "gender"=>"true", "last_name"=>"CHERAMY", "first_name"=>"Guillaume", "birthday"=>"1977-08-08", "address_attributes"=>{"id"=>"", "address"=>""}, "phone"=>"0102030405", "website"=>"", "job"=>"", "interest"=>"", "software_mastered"=>"", "facebook"=>"", "twitter"=>"", "google_plus"=>"", "viadeo"=>"", "linkedin"=>"", "instagram"=>"", "youtube"=>"", "vimeo"=>"", "dailymotion"=>"", "github"=>"", "echosciences"=>"", "pinterest"=>"", "lastfm"=>"", "flickr"=>""}, "username"=>"aukfood", "email"=>"guillaume@********", "is_allow_contact"=>"", "is_allow_newsletter"=>"", "group_id"=>"2", "training_ids"=>[""], "tag_ids"=>[""]}, "authenticity_token"=>"rkxkfkchjOxOnRQqs9EhC3MbtVSXtd8w+nhOew8ybdk2CnFu/tJ+hCGLNF611IaSMsabC01eNeSMTDJUgtn//g=="}
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 1]]
  CACHE (0.0ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 1]]
  Tag Load (0.9ms)  SELECT "tags".* FROM "tags" WHERE 1=0
  CACHE (0.0ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 1]]
  CACHE (0.0ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 1]]
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT 1  [["status", "active"]]
Completed 500 Internal Server Error in 101ms (ActiveRecord: 4.2ms | Elasticsearch: 0.0ms)

NoMethodError (undefined method `email=' for nil:NilClass):
  app/services/members/members_service.rb:34:in `create'
  app/controllers/api/members_controller.rb:46:in `create'`

How can we resolv this ?

Regards

**Comment by guidtz** [comment]
Just for information I upgraded from 2.8 to 4.2 step by step with all procedures to upgrade.

Regards

**Comment by sylvainbx** [comment]
Hi, it seems that you are missing a `rake db:migrate` or that an error have occurred while running that command and you did not noticed it. Please ran it again and report the resulting log here

**Comment by guidtz** [comment]
I join you the long result 
[result.txt](https://github.com/sleede/fab-manager/files/3783010/result.txt)

**Comment by sylvainbx** [comment]
The commands seems to pass correctly. Are you still experiencing the issue?

**Comment by guidtz** [comment]
yes no change, already errors on users creation

**Comment by sylvainbx** [comment]
Well... I have no idea how `invoicing_profile` can be `nil`at [members_service.rb:34](https://github.com/sleede/fab-manager/blob/master/app/services/members/members_service.rb#L34). There was certainly an issue with your upgrade process, as the user-creation API is working without any issue, on many instances using v4.2.3... I'm sorry but I don't know how to help you more with that... :/

**Comment by guidtz** [comment]
:( if a copy the members_service.rb from another instance to this one ? Or there is an issue to export all data from a fabmanager to import in a new one reinstall from sratch installation ?

**Comment by sylvainbx** [comment]
Hmm... I don't now any easy way to migrate the data without migrating the issue at the same time... But I'm almost certain that the issue is coming from the database migration process which may silently fails, for a reason I can't determine... 

Anyway, you can verify this hypothesis by running the following in the rails console:
```ruby
User.first.invoicing_profile
InvoicingProfile
```
report the results here, if you have a doubt about their interpretation

**Comment by guidtz** [comment]
`# docker-compose run --rm fabmanager bundle exec rake User.first.invoicing_profile
Starting fabm-bocal_postgres_1 ... done
Starting fabm-bocal_redis_1         ... done
Starting fabm-bocal_elasticsearch_1 ... done
rake aborted!
Don't know how to build task 'User.first.invoicing_profile' (See the list of available tasks with `rake --tasks`)
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
`
??

**Comment by sylvainbx** [comment]
Ha non, non, pardon, il faut faire :
```bash
docker-compose exec fabmanager bundle exec rails console
```
puis de là, lancer les commandes au dessus

**Comment by guidtz** [comment]
Sorry no, results are here : 
`irb(main):001:0> User.first.invoicing_profile
  User Load (2.1ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  InvoicingProfile Load (0.9ms)  SELECT  "invoicing_profiles".* FROM "invoicing_profiles" WHERE "invoicing_profiles"."user_id" = $1 LIMIT 1  [["user_id", 1]]
=> #<InvoicingProfile id: 29, user_id: 1, first_name: "admin", last_name: "admin", email: "email_user_admin", created_at: "2019-10-21 19:17:14", updated_at: "2019-10-21 19:17:14">


irb(main):002:0> InvoicingProfile
=> InvoicingProfile(id: integer, user_id: integer, first_name: string, last_name: string, email: string, created_at: datetime, updated_at: datetime)
`

**Comment by sylvainbx** [comment]
Ok, so I was wrong, your database seems to be in the correct state...

**Comment by sylvainbx** [comment]
But, wait... the parameters provided by your API call are completly wrong... this is probably way this is not working! You should retry after having [rebuilt the assets](https://github.com/sleede/fab-manager/tree/master/docker#update-fab-manager), this may fix the issue...

**Comment by guidtz** [comment]
arg .... again this assets rebuild .... je vais m'en souvenir à force ...
