### ISSUE TITLE
Paid bouton don't work

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#155]
Hello,

   in another fabmanager installation we have the pad button which do nothing. No logs, no errors ...

![payer_ligne](https://user-images.githubusercontent.com/952410/67557141-c94a3100-f714-11e9-9908-68ba284ec981.png)

How to correct and debug that ?

Regards

**Comment by guidtz** [comment]
Just for info is a fresh FabManager installation.

Regards

**Comment by sylvainbx** [comment]
This issue is tracked [on the forum](https://forum.fab-manager.com/t/payer-en-ligne-ne-fait-rien/512/)

**Comment by guidtz** [comment]
@sylvainbx sorry I didn’t know the two were related so I posted on both

**Comment by sylvainbx** [comment]
Well, I would love that someone else make some user support for fab-manager, but for now, posting here or there always finish in my mailbox :)
