### ISSUE TITLE
unable to download invoices

### ISSUE THREAD

**Issue by fablab127** [sleede/fab-manager#156]
Bonjour, 
Quand nous souhaitons télécharger **une facture récente**  à partir du 23 octobre 2019, nous avons le message suivant qui apparait dans un navigateur web : {"status":"500","error":"Internal Server Error"}
Pas de téléchargement de PDF non plus .
Le téléchargement des factures plus anciennes fonctionnent.

Nous restons à votre disposition .

**Comment by Guillaume89** [comment]
Bonjour,

Exactement le même cas de figure chez nous.

Guillaume
Les Copeaux Numériques

**Comment by sylvainbx** [comment]
Corrigé avec la [version 4.2.4](https://github.com/sleede/fab-manager/releases/tag/v4.2.4)
