### ISSUE TITLE
Modification des messages envoyés automatiquement par mail

### ISSUE THREAD

**Issue by Guillaume89** [sleede/fab-manager#160]
Bonjour tous,

Via l'interface admin on peut configurer les messages affichés lors des différentes réservations. Mais peut-on avoir la main sur les modèles de mails envoyés (expiration d'abonnement, création de compte, réservations...) ? Peut-être qu'il suffit d'aller chercher le bon fichier sur l'instance et l'éditer ? Est-ce si simple ?

Merci de vos éclairages.

Guillaume
Les Copeaux Numériques

**Comment by sylvainbx** [comment]
Bonjour Guillaume,

En effet, ce n'est pas si simple car les templates de mail sont compilés à l'intérieur de l'image Docker et donc, même si tu modifiait les fichiers en question, les changements serait perdus à chaque redémarrage, mise à jour, etc.

Néanmoins, c'est vrai que cela pourrait être intéressant de permettre à chaque fab de personnaliser les mails, je le note dans la liste des demandes d'évolutions.

Bonne journée

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/59/open-format-for-project-exchange).
