### ISSUE TITLE
Calendar view does not change the first day of the week according to WEEK_STARTING_DAY

### ISSUE THREAD

**Issue by SimonePDA** [sleede/fab-manager#169]
I live in a country where the first day of the week is Sunday,

I have been changing the setting in application.yam and the locale is also en-US. No matter what is the day I put in the setting, the calendar shown on the page always starts on Monday.

# I18N configuration
RAILS_LOCALE: 'en'
APP_LOCALE: 'en'
MOMENT_LOCALE: 'en'
SUMMERNOTE_LOCALE: 'en-US'
ANGULAR_LOCALE: 'en-en'
MESSAGEFORMAT_LOCALE: 'en'
FULLCALENDAR_LOCALE: 'en'

TIME_ZONE: 'Asia/Dubai'
WEEK_STARTING_DAY: 'sunday'
D3_DATE_FORMAT: '%d/%m/%y'
UIB_DATE_FORMAT: 'dd/MM/yyyy'
EXCEL_DATE_FORMAT: 'dd/mm/yyyy'

Maybe this setting is supposed to affect something else, or the change in the calendar view needs some other change in the code.

Thanks

**Comment by sylvainbx** [comment]
Hi, thanks for reporting this issue. I'll take a look into this and keep you updated.

**Comment by SimonePDA** [comment]
Thanks a lot!

**Comment by sylvainbx** [comment]
Fixed in https://github.com/sleede/fab-manager/commit/d0be17073b950e44de54208d7cbc88cb094d0ba1

**Comment by SimonePDA** [comment]
Hello Sylvain, applied directly your change in the js file and it works great, finally.
I also understood the reason if this behavior (a constant instead of the config variable) that was probably used for some testing.

Thanks a lot for this fix that is now making my setup much more usable for this country.

Simone

**Comment by sylvainbx** [comment]
Great ! :)

You can upgrade your installation to the new [v4.3.0 release](https://github.com/sleede/fab-manager/releases/tag/v4.3.0) which fixes this issue and provides a lot of new features.

Have a nice day
