### ISSUE TITLE
crash when uploading file to an event

### ISSUE THREAD

**Issue by lpgn** [sleede/fab-manager#17]
Tested on both http://demo.fab-manager.com and http://fabmanager.xinfab.com in two different machines with firefox, chrome and IE. English and French versions both show the issue.

https://github.com/xinfab/fab-manager/issues/7

<img width="1188" alt="screenshot 2016-01-18 17 08 10" src="https://cloud.githubusercontent.com/assets/2556951/12397744/0b508946-be07-11e5-8977-5fca058f93dd.png">

**Comment by sylvainbx** [comment]
I just fixed an issue, preventing the user from editing an event, on the [dev](../tree/dev) and [english](../tree/english) branches. Could you try and tell me if it fixes your issue ?

**Comment by lpgn** [comment]
it is fixed thanks.
