### ISSUE TITLE
Statistiques / Inscriptions / Pas de données pour cette période

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#196]
Instance FabManager : Le Dôme

Passé le 13 juin 2019 le module statistique ne montre plus d'inscriptions (création de compte) alors qu'elles sont bien effectives, et présentes dans l'export de la liste des membres.

**Comment by EmmanuelG** [comment]
Autre chose que j'ai remarqué, peut-être en lien avec ce non-affichage : le module statistique précise "1928" entrées pour le critère "inscriptions" avec l'intervalle de temps complet (alors que plus de 2000 entrées dans la liste).

Ayant tout juste commencé à faire le tri des comptes inactifs depuis plus de 3 ans (RGPD), je viens de procéder à la suppression d'un compte, et cela affiche toujours 1928 entrées (au lieu de 1927 après 1 suppression).

**Comment by sylvainbx** [comment]
Merci pour ces infos, nous allons regarder ça.

**Comment by sylvainbx** [comment]
Je viens de trouver un bug dans la génération journalière des statistiques. Il est reproductible à partir de vos données. Je corrige ça dès que possible et vous tient au courant.

**Comment by sylvainbx** [comment]
Résolu avec la [version 4.3.3](https://github.com/sleede/fab-manager/releases/tag/v4.3.3).

**Comment by sylvainbx** [comment]
Je viens de mettre à jour votre instance. Normalement le problème est désormais résolu, je vous laisse vérifier. Bonne journée

**Comment by EmmanuelG** [comment]
Bonjour @sylvainbx merci d'avoir regardé ça :)
Cependant je viens d'essayer et l'affichage ne montre toujours aucune inscriptions, passée la même date du 13 juin 2019 (alors que devraient apparaître un peu plus de 300 entrées).

Uniquement pour l'onglet "inscription", en vue "données"
![Capture](https://user-images.githubusercontent.com/710674/79874747-043dd080-83e9-11ea-9fa9-fbd2abf4b18b.PNG)

Ou en vue "évolution", est affiché cette fois "pas de données pour cette période" (c'est amusant d'ailleurs quand on élargie la date de début d'intervalle de voir l'interruption brutale de la courbe)
![Capture2](https://user-images.githubusercontent.com/710674/79875362-d86f1a80-83e9-11ea-812a-ee7beb63443a.PNG)

**Comment by sylvainbx** [comment]
Corrigé avec la [version 4.4.2](https://github.com/sleede/fab-manager/releases/tag/v4.4.2)

**Comment by EmmanuelG** [comment]
En effet l'information apparait à nouveau, super !
