### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#2]
Connecté en version mobile sur mon smartphone, 
Il n'y a pas de bouton pour se deconnecter, et donc changer d'utilisateur, 
Idem version non mobile ?

**Comment by sylvainbx** [comment]
Effectivement il semblerait que le bouton soit manquant sur la version mobile. Sur la version desktop, il est accessible en cliquant sur son nom d'utilisateur en haut à droite de l'application.

**Comment by sylvainbx** [comment]
Bug corrigé sur la branche "dev"
