### ISSUE TITLE
Bootstrap import issue

### ISSUE THREAD

**Issue by JMMolenaar** [sleede/fab-manager#20]
I get this:
`ActionView::Template::Error (Undefined variable: "$dl-horizontal-breakpoint".
15:52:10 web.1    |   (in /Users/JMM/Documents/web/fabmanager/fab-manager/app/assets/stylesheets/application.scss:210)):
15:52:10 web.1    |     50:       Fablab.d3DateFormat = "<%= Rails.application.secrets.d3_date_format %>";
15:52:10 web.1    |     51:   </script>
15:52:10 web.1    |     52:
15:52:10 web.1    |     53:   <%= stylesheet_link_tag 'application', media: 'all' %>
15:52:10 web.1    |     54:   <%= stylesheet_link_tag 'app.printer', media: 'print' %>
15:52:10 web.1    |     55:   <% if !Stylesheet.first.nil? %>
15:52:10 web.1    |     56:     <link rel="stylesheet" media="all" href="<%= stylesheet_path(Stylesheet.first.id) %>-<%=Stylesheet.first.updated_at.to_i.to_s%>.css" />
15:52:10 web.1    |   app/assets/stylesheets/bootstrap_and_overrides.scss:941
15:52:10 web.1    |   app/assets/stylesheets/application.scss:23
15:52:10 web.1    |   app/views/application/index.html.erb:53:in`_app_views_application_index_html_erb___1104466589295152000_70211720105620'`

When I do a setup of the system without altering any files. 

A working solution is to add 
@import "bootstrap";
to the top of /app/assets/stylesheets/application.scss

But I don't think that should be necessary. 

Guessing it's either not loading the correct bootstrap assets, or it's loading them too late..

**Comment by sylvainbx** [comment]
I've installed an instance of the fab-manager from stratch but I was unable to reproduce the issue. 
Please, can you specify the steps you take to get into this issue so that we can get a reproduction scenario?

**Comment by JMMolenaar** [comment]
If you cannot reproduce, it's probably a local linkages issue.. and since I can actually simply add a bootstrap import the the assets, it does not cause any problem. Not worth the time investigating. 

Trying to slap a version on heroku now, we'll deploy at least one here at Tufts, and I might do a setup at the CIC in Boston. 

Sleede all over the world.

**Comment by pmoutet** [comment]
Hello JM :)

Thanks for your feedback. Let us know when you have Fab Manager up and running at Tufts !

See you

Pascal

**Comment by JMMolenaar** [comment]
Will do :)

How's life in France?

_Jean-michel Molenaar_

Phone +1 617 639 7435
Skype - geelblokje

*GMT + 1 (mostly)  *+45° 19' 76.15"  -5° 73' 24.43"
