### ISSUE TITLE
Suppression de créneau de validation impossible

### ISSUE THREAD

**Issue by matteli** [sleede/fab-manager#201]
Salut,

Nous utilisons la dernière version de fab manager (4.3.4).
Quand un créneau de réservaton est réalisé, il est possible de le supprimer. Normal.
Si quelqu'un réserve une machine dans le créneau, ce dernier devient impossible à supprimer. Normal.

Par contre quand on supprime la réservation et que le créneau se trouve libéré de toutes réservations, il est impossible de le supprimer. Un message indique qu'un membre a probablement posé une réservation alors que toutes les réservations ont été annulés. Est-ce volontaire ou est-ce un bug ?

Merci

Matthieu

**Comment by sylvainbx** [comment]
Salut,

Effectivement cela peut sembler étrange au premier abord mais il n'est pas possible de supprimer un créneau dans lequel au moins une réservation a été effectuée. Même si ces réservations sont annulées, elles ne sont pas supprimées et donc la relation avec le créneau doit être conservée => du coup, impossible de supprimer le créneau.

Pour palier à ça, on a introduit la notion de "bloquer les réservations"  sur un créneau, ce qui revient à peu près au même, puisqu'il devient invisible pour les membres et que plus personne ne peut réserver dessus.

J'espère que ça répond à ta question.
Bonne journée,

Sylvain

**Comment by matteli** [comment]
Ok
Merci pour ta réponse.
