### ISSUE TITLE
Problème avec durée créneau

### ISSUE THREAD

**Issue by mipslab** [sleede/fab-manager#204]
Bonjour,

Version Fabmanager : 4.3.4
Paramétrage du créneau minimal de réservation d'une machine : 30 minutes
Lorsqu'on réserve la machine, le coût indiqué est le prix d'une heure pour un créneau de 30 minutes (voir copie d'écran jointe).
Merci d'avance pour votre réponse.

Guillaume (MIPS Lab)

![Bug créneau 30min](https://user-images.githubusercontent.com/64592510/80714170-cfbaca80-8af4-11ea-9b73-10bcc045ee23.png)

**Comment by sylvainbx** [comment]
Salut,
Effectivement il y a un problème de wording à cet endroit. La prochaine version permettra une gestion plus fine des durées des créneaux. Dans le cadre de cette évolution, on a tout revu, le problème devrait donc être corrigé à ce moment.

**Comment by mipslab** [comment]
Bonjour Sylvain,
Merci pour ce retour.
C'est un peu plus qu'un pb de wording : on réserve une heure mais on paye 2 heures :-)
Quelle est la date approximative de livraison de la prochaine version ? En attendant, on ne peut donc définir que des créneaux multiples de l'heure ?
Guillaume

**Comment by sylvainbx** [comment]
Ah oui, en effet, c'est assez gênant alors !
La prochaine version ne devrait pas tarder, il ne reste plus que quelques corrections et de la traduction. En attendant, je ne peux pas te proposer mieux que de créer des créneaux d'une heure pour éviter le problème.

**Comment by mipslab** [comment]
Ça marche, merci.

**Comment by mipslab** [comment]
En attente de la prochaine version...

**Comment by sylvainbx** [comment]
@mipslab Si tu le veux bien, je peux te proposer tester la prochaine version en avance de phase: tu peux modifier ton fichier docker-compose.yml en y mettant `image: sleede/fab-manager:dev`, les modifications relatives à la durée du créneau y ont été publiées.  Je serais curieux d'avoir ton retour à ce propos, pour savoir si cela correspond bien à tes attentes.

**Comment by sylvainbx** [comment]
Corrigé dans la [version 4.4.0](https://github.com/sleede/fab-manager/releases/tag/v4.4.0)
