### ISSUE TITLE
mise à jour 4.4.0 / page abonnement / stats inscriptions

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#208]
Instance : Le Dôme / Relais D'Sciences
Version : 4.4.0 depuis quelques minutes

Voyant qu'une mise à jour venait de se faire, je suis allé voir le changelog et _"Fix a bug: do not show disabled groups and plans during availability creation"_ a notamment retenu mon attention.

Cependant à la page des [abonnements](https://fablab.ledome.info/#!/plans) il s'affiche 
> {{ 'app.public.plans.subscriptions' }}

J'ai parfois vu des variables en clair à la place du texte donc peut-être que ça va se remettre en place mais dans le doute je me suis dis que j'allais le signaler.

Autrement le [bug concernant les inscriptions dans le module statistique](https://github.com/sleede/fab-manager/issues/196#issuecomment-617202425) est toujours valable.

**Comment by sylvainbx** [comment]
Vous avez bien fait de le signaler, il semblerait qu'une erreur de frappe ait introduit un bug dans le code. Je corrige ça de suite.

**Comment by sylvainbx** [comment]
Corrigé dans la [version 4.4.1](https://github.com/sleede/fab-manager/releases/tag/v4.4.1). 

Concernant le bug dans les statistiques, ça semble plus compliqué que prévu, je vais continuer d'investiguer et je vous tient au courant.

**Comment by EmmanuelG** [comment]
La partie abonnement est résolue, merci :D
