### ISSUE TITLE
[feature] Admin page for checking configuration, test email sending, etc

### ISSUE THREAD

**Issue by vikbez** [sleede/fab-manager#21]
It's actually a pain to test email sending, a page with at least this feature would be really useful.

**Comment by sylvainbx** [comment]
Hello @vikbez,
You can preview the emails by browsing to [localhost:3000/rails/mailers/](http://localhost:3000/rails/mailers/).
But please, consider that this will work **only if** you have, at least, 1 notification record in database, of the type you are trying to preview.

_Eg._ for testing `notifications_mailer/notify_member_subscribed_plan`, a member must have took a subscription before you can preview the mail from the address above.
