### ISSUE TITLE
Paimement carte indisponible, uniquement dans la partie "événements"

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#229]
Hello :)

Instance FabManager : Dôme / Relais d'Sciences
Version 4.5.5

Un utilisateur me signal un soucis que j'arrive à reproduire : 
Alors que le paiement par carte fonctionne pour la partie "Réserver une machine" il est dit indisponible dans la partie "Inscription aux événements" au moment de régler le nombre de places voulu.
La dernière réservation avec succès d'un événement a été faite le 20 juillet 15:18, c'est donc apparut relativement récemment.

![Capture_paiement_carte_indispo](https://user-images.githubusercontent.com/710674/91730115-d1c98e80-eba5-11ea-85f3-1739f4dfea69.JPG)

J'ai d'abord songé à Stripe mais les info sont toujours là et surtout le fait qu'une partie fonctionne toujours me fais dire que le problème est ailleurs.
Je le signal ici au cas où ça serait un bug.

**Comment by sylvainbx** [comment]
Merci Emmanuel, je vais regarder ça

**Comment by sylvainbx** [comment]
Corrigé dans la [version 4.5.6](https://github.com/sleede/fab-manager/releases/tag/v4.5.6)
