### ISSUE TITLE
Fonction recherche dans galerie de projets

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#230]
Hello :)

Instance : Relais D'Sciences - Le Dôme
Version : 4.5.6

On me signal le bug suivant (sur tout navigateurs), que j'ai pu reproduire sur Firefox : dans la Galerie de Projets, l'utilisation du champ "recherche" n'a plus d'effets. Bien que l'adresse url reflète la requête souhaitée.

![2020-09-15 Capture FM](https://user-images.githubusercontent.com/710674/93183093-d7dd7480-f73a-11ea-8080-5edc4f4fec11.JPG)

**Comment by sylvainbx** [comment]
Résolu dans la [version 4.5.7](https://github.com/sleede/fab-manager/releases/tag/v4.5.7)
