### ISSUE TITLE
Petit bug, mail automatique lors du déplacement d'une réservation

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#234]
Instance FabManager v.4.5.9 de Relais D'Sciences.

Depuis quelques temps j'observe un petit bug dont je viens d'avoir la certitude : dans le mail automatique envoyé lorsqu'un utilisateur déplace un créneau, la date de l'ancien créneau est identique à la date du nouveau créneau.

![Capture_date-resa_doublon](https://user-images.githubusercontent.com/710674/96023544-e363ae80-0e52-11eb-800b-cf853e531846.JPG)
(pour cet exemple récent j'avais en tête la date de l'ancien créneau ce qui me permet de comparer, mais ça rejoins d'autres mails similaires)

:)

**Comment by sylvainbx** [comment]
Merci Emmanuel, je regarde ça

**Comment by sylvainbx** [comment]
Corrigé dans la [version 4.6.0](https://github.com/sleede/fab-manager/releases/tag/v4.6.0)
