### ISSUE TITLE
boot fab-manager in a openstack instance

### ISSUE THREAD

**Issue by Gambiit** [sleede/fab-manager#24]
Thanks a lot for your nice job :)
I wish to contribute but i don't have skill over angular.js . However, i think i could do a simple docker-compose file and some post-install script to boot one coreOs instance in a openstack cloud like ovh.
How do you think about?

**Comment by sylvainbx** [comment]
Hi @Gambiit, thanks for your proposal. Wa had this on our TODO list, but we lack of time for the moment, so your contribution will be welcome !

Do not forget to look at the [docker folder](https://github.com/LaCasemate/fab-manager/tree/master/docker) in case you have missed it.

**Comment by sylvainbx** [comment]
This has been implemented in [d0461f0a817](https://github.com/LaCasemate/fab-manager/commit/d0461f0a817bb200d7b71f2235e0260aa8ccf6b7) and will be included in the next release.
