### ISSUE TITLE
Problème de somme de contrôle invalide sur des factures

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#243]
Bonjour,
  pour valider la période comptable de 2020 un utilisateur à une erreur de la sorte : 

```
2006002/A : la somme de contrôle de la facture est invalide 2012001/A : la somme de contrôle de la facture est invalide
```
Comment faire ?

Merci

**Comment by sylvainbx** [comment]
Salut,

Il va falloir trouver ce qui a été modifié pour que la comme de contrôle soit devenue invalide. Pour ce faire :
```bash
cd /apps/fabmanager/
docker-compose exec fabmanager bundle exec rails c
```
Puis dans le prompt ruby qui s'affiche, copie/colle le code suivant :
```ruby
item = Invoice.find_by(reference: "2006002/A")
columns = FootprintService.footprint_columns(Invoice)
current = FootprintService.footprint_data(Invoice, item)
saved = FootprintDebug.find_by(footprint: item.footprint)
puts "Debug footprint for Invoice [ id: #{item.id} ]"
puts '-----------------------------------------'
puts "columns: [ #{columns.join(', ')} ]"
puts "current footprint: #{current}"
puts "  saved footprint: #{saved&.data}"
puts '-----------------------------------------'
```
Compare les données entre les lignes `current footprint` et `saved footprint` pour voir ce qui diffère et reporte le ici.
Ensuite, merci de refaire la même chose en remplaçant la référence par `2012001/A` dans le code ruby.

D'autre part, peux-tu nous dire quelle est la version de fab-manager que tu utilises ?

**Comment by guidtz** [comment]
@sylvainbx voici les résultats ... je vois pas de différence : 

```
irb(main):009:0> puts "current footprint: #{current}"
current footprint: 221WalletTransaction20002020-06-12 00:00:00 +02002006002/Awallet2020-06-12 00:00:00 +0200Avoirfalseproduction24242645eada9ee70a9c7bca2116405eb1deb63172496eea51100bb66804f25340b1
=> nil
irb(main):010:0> puts "  saved footprint: #{saved&.data}"
  saved footprint: 221WalletTransaction20002020-06-12 00:00:00 +02002006002/Awallet2020-06-12 00:00:00 +0200Avoirfalseproduction24242645eada9ee70a9c7bca2116405eb1deb63172496eea51100bb66804f25340b1
```

Au niveau de la version c'est celle que tu avais upgradé lors de ton intervention en décembre.

Merci

**Comment by sylvainbx** [comment]
Je ne me souviens plus de la version que j'ai installé :), mais tu peux l'obtenir avec 
```bash
docker-compose exec fabmanager bundle exec rails fablab:maintenance:version
```

Effectivement, il n'y a pas de différence, peux-tu du coup vérifier (de la même façon) les sous-éléments de la facture, avec le code ci-dessous :
```ruby
items = Invoice.find_by(reference: "2006002/A").invoice_items
columns = FootprintService.footprint_columns(InvoiceItem)
current = FootprintService.footprint_data(InvoiceItem, items.first)
saved = FootprintDebug.find_by(footprint: items.first.footprint)
puts "items count: #{items.count}"
puts "Debug footprint for InvoiceItem [ id: #{items.first.id} ]"
puts '-----------------------------------------'
puts "columns: [ #{columns.join(', ')} ]"
puts "current footprint: #{current}"
puts "  saved footprint: #{saved&.data}"
puts '-----------------------------------------'
```

**Comment by guidtz** [comment]
Version : 4.6.5

Les résultats des requêtes  qui me semblent identique : 
```
=> nil
irb(main):010:0> puts "current footprint: #{current}"
current footprint: 282220002020-06-12 15:24:13 +0200Crédit du porte-monnaie039412f0445563cceb3b279d7bcabf864d8a56b118c87ee86868db85ea867aef
=> nil
irb(main):011:0> puts "  saved footprint: #{saved&.data}"
saved footprint: 282220002020-06-12 15:24:13 +0200Crédit du porte-monnaie039412f0445563cceb3b279d7bcabf864d8a56b118c87ee86868db85ea867aef
```

**Comment by sylvainbx** [comment]
Hmm bigre!
Peux-tu faire un dump de ta base de données [en suivant cette procédure](https://github.com/sleede/fab-manager/blob/master/doc/postgresql_readme.md#dumping-the-database) et me l'envoyer par mail pour que j'essaie de déboguer le problème ?

**Comment by guidtz** [comment]
@sylvainbx j'ai pas eu de retours on peut fermer

**Comment by sylvainbx** [comment]
OK, n'hésite pas à rouvrir si le problème apparaît de nouveau, c'est une fonctionnalité importante à débugger !
