### ISSUE TITLE
FabLabML & Ontology

### ISSUE THREAD

**Issue by AmauryVanEspen** [sleede/fab-manager#26]
Bonjour/Good afternoon,

Avez vous déjà pris connaissance de cette ressource et disposez vous d'une ontologie publiée pour la structuration de vos données ?

https://fablabo.net/wiki/WorkshopDocumentation/FabmlOntologies

Have you ever read something about this ontology and does your data schema is publicly available ?

Thank you for your kind collaboration

Amaury

**Comment by sylvainbx** [comment]
Bonjour,

Cette ontologie (FablabML) ne semble ni très normalisée, ni très largement utilisée ... je doute que nous l'intégrions dans fab-manager. 

Concernant la publication des données de projet, nous avons lancé la plate-forme [OpenLab-Projects](https://github.com/LaCasemate/openlab-projects) qui permet à tous les fablab utilisant fab-manager de mettre en commun leur base de donnée de projets. Tu peux consulter les sources de ce projet (notamment [project.rb](https://github.com/LaCasemate/openlab-projects/blob/master/app/models/project.rb)) ou encore [le schéma de documentation des modèles](https://github.com/LaCasemate/fab-manager/blob/master/doc/models_complete.svg) pour obtenir plus de détails sur la structuration des données de projet.

En espérant que cela réponde à ta question.
Cordialement

**Comment by AmauryVanEspen** [comment]
Bonjour Sylvain,

merci de votre message,
je suis en lien avec Pascal Moutet à ce sujet
je met également en copie Xavier Belka de "OuiAreMakers" ainsi que Tibor
Katelbach du projet "Communecter" de la CommonsDev team notamment que vous
pourrez retrouver sur GitHub.

nous avons lancé une discussion concernant une potentielle coopération.
Aussi, je vous invite à échanger avec Pascal pour reprendre l'échange et/ou
vous y intégrer plus largement.

Je vous remercie de votre aimable coopération.
Merci également des liens suggérés.

Cordialement

Amaury

2016-07-25 10:52 GMT+02:00 Sylvain notifications@github.com:

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/24/open-format-for-project-exchange).
