### ISSUE TITLE
Impossible to attach a dxf to my project

### ISSUE THREAD

**Issue by rlomba** [sleede/fab-manager#261]
When trying to attach a dxf file to my project, I get an error message
![Capture](https://user-images.githubusercontent.com/29277965/117315371-ede5a400-ae87-11eb-952b-78ec3edd40d0.PNG)

This issue tracker is **reserved** for bug reports.

The place to ask a question or call for help is at [Fab-manager forums](https://forum.fab-manager.com)

The place to request or vote for new feature is on the [feedback website](https://feedback.fab-manager.com)

To report a bug, please describe:
- Expected behavior and actual behavior.
- Steps to reproduce the problem.
- Specifications like the version of the project, operating system, or hardware.

The following elements may help to quickly resolve your issue:
- Server logs `tail -f /apps/fabmanager/log/app-stdout.log` on the server
- Client logs `Ctrl`+`Maj`+`i` > `Console` in the browser

**Comment by sylvainbx** [comment]
Hi, have you tried to add the appropriate mime type to the authorized attachments list?
You can do it while logged as admin, going to Projects > Settings > CAD files > Allowed MIME types. Check the MIME type to add using the field "test file" below.

**Comment by rlomba** [comment]
Le format dxf fait bien partie de la liste des fichiers autorisés.
Ainsi que le MIME application/dxf

Ici, j'essaie de mettre un dxf généré par Freecad.

**Comment by sylvainbx** [comment]
Can you send me a sample DXF file so I can make some tests?

**Comment by rlomba** [comment]
here it is

**Comment by sylvainbx** [comment]
I guess you are answering by mail with an attachment. This won't work with github I'm afraid...
Can you send it by mail at support [à] fab-manager.com ?
Thanks

**Comment by sylvainbx** [comment]
Using a sample dxf file found [on the internet](https://people.math.sc.edu/Burkardt/data/dxf/bridge.dxf), I was not able to reproduce the issue with fab-manager v5.0.3:

![image](https://user-images.githubusercontent.com/5102799/122012166-2a78b980-cdbd-11eb-8670-52cda9623d74.png)

My configuration in Projects > Settings > CAD files was:
Allowed extension:  dxf
Allowed MIME type: application/octet-stream

Please feel free to reopen this issue if you are still experiencing the issue.
