### ISSUE TITLE
[docker install] [WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.

### ISSUE THREAD

**Issue by phd0** [sleede/fab-manager#27]
Lors de la mise en place d'une installation "_façon docker_" 
sur une base Debian 8 neuve, avec **Docker version 1.11.2**
la création des 3 image de base est correcte 

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
1e9e0745b495        elasticsearch:1.7   "/docker-entrypoint.s"   58 minutes ago      Up 29 minutes       9200/tcp, 9300/tcp   fabmanager-elastic
fe182718b8ab        postgres:9.4        "/docker-entrypoint.s"   58 minutes ago      Up 29 minutes       5432/tcp             fabmanager-postgres
92a8a09aeead        redis:3.0           "docker-entrypoint.sh"   58 minutes ago      Up 29 minutes       6379/tcp             fabmanager-redis
```

la création de la table se passe bien avec un `rake db:create`. le drop aussi avec un `rake db:drop`. le pb est sur le _migrate_ avec un message `[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.`

est t'il possible de mettre a jour les sources des conteneur Docker pour permettre une installation sans soucis ?
Cordialement

**Comment by phd0** [comment]
y'a t'il un rapport avec  [RolifyCommunity/rolify #250](https://github.com/RolifyCommunity/rolify/issues/250)

**Comment by phd0** [comment]
finalement, le Pb semble venir du fait que mon fichier `/fabmanager/config/env` qui n'avait pas une valeur _SECRET_KEY_BASE_ correct. un `rake secret` permet d'en créer une correcte, d'une longueur suffisante

EDIT : oui, ca n'était que ça. Ca fonctionne
Remarque la commande `rake assets:precompile` est super longue ...

**Comment by nflorentin** [comment]
Bonjour,

pour les problèmes d'installation, il faudrait passer par le [forum Fab-manager](https://forum.fab-manager.com/).

merci
