### ISSUE TITLE
Cancelling or postposing reservation not possible while personalisation parameters says so

### ISSUE THREAD

**Issue by rlomba** [sleede/fab-manager#271]
In the Admin PArameters, I set to 
![Capture](https://user-images.githubusercontent.com/29277965/118976903-dae9ce00-b975-11eb-8f56-5a257a2c6ca6.PNG)

But in the user view, I don't have access to any option to either cancel or postpone:
![Capture](https://user-images.githubusercontent.com/29277965/118977023-010f6e00-b976-11eb-8a88-e4d0cd35a4ed.PNG)

This doesn't match the user manual..

**Comment by sylvainbx** [comment]
Hi,

Moving or cancelling bookings is not handled from the public agenda but from the resource-specific agenda. For example, when logged as a user, you can go to `Reserve a Machine` > click on the `Reserve` button for any machine, then you'll see the machine-specific agenda. From this view, clicking on the already booked slot will open a dialog allowing the user to move or cancel his reservation, if this is allowed in the settings (as your first picture shows).

**Comment by sylvainbx** [comment]
I have reviewed the user's manual about cancelling or postponing reservations but I found nothing about doing such a thing in the public agenda.
Please feel free to reopen the issue if you have more details about the passage concerned.
