### ISSUE TITLE
Error 500 / internal error / tentative de paiement par Stripe

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#275]
Depuis mercredi 26 mai matin (suite à la mise à jour ?), un bug semble être apparut sur notre instance du Dôme :

**Describe the bug**
En fin de procédure de paiement, par carte, via Stripe, après vérification avec le code de la banque, la tentative n’aboutis pas.
Un message "Internal server error" s'affiche.

Nous avons rencontré ce problème trois fois avec trois personnes différentes (et probablement d'autres qui n'ont pas signalé le bug).

**Screenshot**
La deuxième personne a avoir rencontré le problème m'a fait parvenir cette capture d'écran, quand lui-même essayait de nous fournir le plus d'informations possible.
![Screenshot from 2021-05-26 17-23-24](https://user-images.githubusercontent.com/710674/119985342-cedbbd00-bfc2-11eb-84a2-f40122a2d41c.png)

**Server**
 - LeDôme @ Sleede
 - Fab-manager version 4.7.10

**Browser**
 - Firefox
 - Version: 88.0.1

**Comment by sylvainbx** [comment]
Merci de l'avoir signalé, je regarde ça au plus vite

**Comment by sylvainbx** [comment]
Note pour le débogage
--------------------

From app-stdout.log.1
```
Stripe::InvalidRequestError (No such PaymentMethod: 'pi_1IyBEOJ8nx9QemzCWZUiehZm'):

app/controllers/api/payments_controller.rb:26:in `confirm_payment'
app/controllers/application_controller.rb:69:in `switch_locale'
```
[Related code](https://github.com/sleede/fab-manager/blob/master/app/controllers/api/payments_controller.rb#L28)

**Comment by sylvainbx** [comment]
Corrigé dans la [version 4.7.12](https://github.com/sleede/fab-manager/releases/tag/v4.7.12)
