### ISSUE TITLE
Modification d'un Stages et ateliers 

### ISSUE THREAD

**Issue by phd0** [sleede/fab-manager#28]
lors de la modification d'un stage ou atelier par un admin, la vue oublie quel "Type d'évènement" c'est. On est obligé de le re sélectionner pour pouvoir enregistrer.

**Comment by sylvainbx** [comment]
Problème fixé dans le commit référencé ci-dessus.
Le correctif est disponible immédiatement dans la branche [dev](https://github.com/LaCasemate/fab-manager/tree/dev) or dans la prochaine version stable (2.4.0)
