### ISSUE TITLE
Potential xss vulnerability

### ISSUE THREAD

**Issue by gsbm** [sleede/fab-manager#293]
Hi, I worked on Fab Manager for a client for a while and noticed that users could freely inject javascript when writing an article (in the HTML editor), causing what seems to be (legitimately) a security hole. It might be a good idea to block script tags in the HTML editor or give the possibility to disable the HTML editor for casual users.

**Comment by gnepud** [comment]
Hi @boardens 
Thanks for report this issue. We will fix it and release a new version as soon as possible.

best regards

**Comment by sylvainbx** [comment]
This issue has been addressed in [Fab-manager v5.1.10](https://github.com/sleede/fab-manager/releases/tag/v5.1.10).
