### ISSUE TITLE
Docker installation fails during yarn install

### ISSUE THREAD

**Issue by karliwalti** [sleede/fab-manager#299]
**Describe the bug**
The installation throws an error and continues

**To Reproduce**
1. follow instructions on https://github.com/sleede/fab-manager/blob/master/doc/production_readme.md
2. Call `\curl -sSL setup.fab.mn | bash`
3. See error after entering all configs

**Expected behavior**
No error thrown. If error is thrown then abort. 

**Screenshots**
`yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Kernel: 5.4.0-29-generic 33-Ubuntu
 - Fab-manager version 5.1.6

**Additional context**
git is installed

**Comment by karliwalti** [comment]
https://github.com/yarnpkg/yarn/issues/2083
does suggest to add `RUN apk add --no-cache git`

but this is already added here https://github.com/sleede/fab-manager/blob/73558399d9ea7ba14234b043f05051f059a49cdc/Dockerfile#L29

**Comment by gnepud** [comment]
Hi @karliwalti

You must install git in your OS.
Check git with `which git`, if git no found, please install it by
```
sudo apt update
sudo apt install git
```

thanks

**Comment by karliwalti** [comment]
Hi @gnepud 
thanks. 
This I checked. it is installed:
```
>which git
/usr/bin/git
```

**Comment by karliwalti** [comment]
BTW:
same issue with 
```
> \curl -sSL upgrade.fab.mn | bash -s --
Checking user...
ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd docker
Checking installation...


:: Proceed with upgrading to version 5.1.7 ? (Y/n)
Pulling fabmanager ... done
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
Compiling...
```

**Comment by gnepud** [comment]
You can ignore this error `error Couldn't find the binary git `

Do you have any others errors after compile the assets has done ?

**Comment by karliwalti** [comment]
No that was the only error. thank you
