### ISSUE TITLE
gestion des admins

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#3]
Bonjour, 

il y a un admin par defaut, mais il est imposssible de definir dans la gestion des utilisateurs d'autres admin (genre creer un compte admin pour l'asso, avec les bons contacts, se connecter en admin par defaut, attribuer le compte precedement crée en admin, et supprimer le compte par defaut via le nouvel admin). 

notamment aussi dans le but de deleguer la gestion du lab par d'autre personne que le fabmanager, ou de dispatcher entre les multiples fabmanageur, ou une gestion collaborative avec des collaborateurs de confiance

tout ca, sans passer en dur dans la base de données, bien sure.

**Comment by jarod022** [comment]
A ce jour, seule la version Premium dispose de cette fonctionnalité.
Les comptes admins doivent être paramétrés via la console de Ruby on Rails (rails console) au lancement du projet ou ultérieurement.
