### ISSUE TITLE
[docker install] comment changer la verbosité des logs ?

### ISSUE THREAD

**Issue by phd0** [sleede/fab-manager#30]
Dans la version docker, comment changer la verbosité des logs ?
en quelques minutes, le fichier `app-stdout.log` est déjà à 1Mb

**Comment by nflorentin** [comment]
Bonjour,

Nous ne traitons que les bugs via Github, pour les interrogations/questions/demandes d'aide, il faut passer par le [forum Fab-manager](https://forum.fab-manager.com/).

merci
