### ISSUE TITLE
supprimer une etape

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#31]
Bonjour,
je suis en train de documenter un projet, avec un lonnnng texte, et je clic par erreur sur "supprimer cette étape" : il n'y a aucun message de confirmation, 
et aucune possibilité de revenir en arrière sur cette fausse manipulation. 

je confirme que c'est un problème très handicapant ...

**Comment by sylvainbx** [comment]
Bonjour,
La confirmation de la suppression d'une étape d'un projet a été ajoutée dans le prochaine version du fab-manager (voir [48a90bb7](https://github.com/LaCasemate/fab-manager/commit/48a90bb7b4d1071797b0250bf65898664b11416d#diff-8f4fd8d77533e635131e6f50d03b4c66R141)). 
Vous pouvez d'ores et déjà tester cette fonctionnalité sur la branche [dev](https://github.com/LaCasemate/fab-manager/tree/dev) (non stable) ou attendre la sortie de la prochaine version stable prévue pour la rentrée de septembre qui contiendra cette amélioration.

**Comment by clemclemmm** [comment]
Merci pour cette modification importante ! 

est ce que ce comportement a ete ajoute aussi pour la suppression d'un projet ?
(rajouter une confirmation avant suppression)

**Comment by sylvainbx** [comment]
Oui, dans la [version 2.3.0](https://github.com/LaCasemate/fab-manager/blob/v2.3.0/CHANGELOG.md)
