### ISSUE TITLE
Deploy issue to Heroku

### ISSUE THREAD

**Issue by kyleevert** [sleede/fab-manager#32]
Thank you for the great material, first.
I have installed this open source on my local and it works fine.
But when I tried to deploy to the heroku, I have got the issue during pushing the code to the heroku.
The log is like the below:

-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.0
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Installing aasm 4.1.0
       Installing i18n 0.7.0
       Installing rake 11.1.2
       Using json 1.8.3
       Installing thread_safe 0.3.5
       Installing minitest 5.9.0
       Installing builder 3.2.2
       Installing mini_portile2 2.0.0
       Installing erubis 2.7.0
       Installing rack 1.6.4
       Installing mime-types 2.99
       Installing arel 6.0.3
       Installing addressable 2.3.8
       Installing api-pagination 4.3.0
       Installing execjs 2.4.0
       Installing ice_nine 0.11.1
       Installing bcrypt 3.1.10 with native extensions
       Installing sass 3.4.13
       Installing buftok 0.2.0
       Installing camertron-eprun 1.1.0
       Installing hitimes 1.2.2 with native extensions
       Installing chroma 0.0.1
       Installing chunky_png 1.3.4
       Installing cldr-plurals-runtime-rb 1.0.1
       Installing coffee-script-source 1.9.1
       Installing thor 0.19.1
       Installing multi_json 1.12.1
       Installing rb-fsevent 0.9.4
       Installing ffi 1.9.8 with native extensions
       Installing hike 1.2.3
       Installing tilt 1.4.1
       Installing connection_pool 2.2.0
       Installing orm_adapter 0.5.0
       Installing unf_ext 0.0.6 with native extensions
       Installing multipart-post 2.0.0
       Installing hashie 3.4.2
       Installing equalizer 0.0.11
       Installing elasticsearch-rails 0.1.7
       Installing forgery 0.6.0
       Installing http_parser.rb 0.6.0 with native extensions
       Installing multi_xml 0.5.5
       Installing jwt 1.5.1
       Installing kgio 2.9.3 with native extensions
       Installing libv8 3.16.14.11
       Installing mini_magick 4.2.0
       Installing naught 1.0.0
       Using bundler 1.11.2
       Installing netrc 0.10.3
       Installing oj 2.12.8 with native extensions
       Installing pdf-core 0.5.1
       Installing pg 0.18.1 with native extensions
       Installing ttfunk 1.4.0
       Installing prawn-table 0.2.1
       Installing rails_serve_static_assets 0.0.4
       Installing rails_stdout_logging 0.0.3
       Installing raindrops 0.13.0 with native extensions
       Installing redis 3.2.1
       Installing ref 2.0.0
       Installing rolify 4.0.0
       Installing simple_oauth 0.3.1
       Installing apipie-rails 0.3.6
       Installing rdoc 4.2.0
       Installing tzinfo 1.2.2
       Installing descendants_tracker 0.0.4
       Installing memoizable 0.4.2
       Installing nokogiri 1.6.7.2 with native extensions
       Installing rack-test 0.6.3
       Installing warden 1.2.3
       Installing rack-protection 1.5.3
       Installing mail 2.6.3
       Installing autoprefixer-rails 5.1.8
       Installing uglifier 2.7.1
       Installing compass-import-once 1.0.5
       Installing coffee-script 2.3.0
       Installing timers 4.0.1
       Installing figaro 1.1.0
       Installing compass-core 1.0.3
       Installing elasticsearch-api 1.0.12
       Installing sprockets 2.12.4
       Installing faraday 0.9.1
       Installing omniauth 1.2.2
       Installing rb-inotify 0.9.5
       Installing httparty 0.13.7
       Installing unf 0.1.4
       Installing http 0.6.4
       Installing prawn 2.0.1
       Installing rails_12factor 0.0.3
       Installing redis-namespace 1.5.2
       Installing therubyracer 0.12.0 with native extensions
       Installing sdoc 0.4.1
       Installing activesupport 4.2.5
       Installing twitter_cldr 3.2.1
       Installing rufus-scheduler 3.0.9
       Installing axiom-types 0.1.1
       Installing coercible 1.0.0
       Installing sinatra 1.4.6
       Installing bootstrap-sass 3.3.4.1
       Installing unicorn 4.8.3 with native extensions
       Installing celluloid 0.16.0
       Installing elasticsearch-transport 1.0.12
       Installing oauth2 1.0.0
       Installing compass 1.0.3
       Installing domain_name 0.5.25
       Installing twitter-text 1.11.0
       Installing openlab_ruby 0.0.4
       Installing twitter 5.14.0
       Installing rails-deprecated_sanitizer 1.0.3
       Installing globalid 0.3.6
       Installing activemodel 4.2.5
       Installing jbuilder 2.5.0
       Installing pundit 1.0.0
       Installing recurrence 1.3.0
       Installing message_format 0.0.3
       Installing loofah 2.0.3
       Installing virtus 1.0.5
       Installing sidekiq 3.3.4
       Installing elasticsearch 1.0.12
       Installing omniauth-oauth2 1.3.1
       Installing http-cookie 1.0.2
       Installing rails-dom-testing 1.0.7
       Installing activejob 4.2.5
       Installing activerecord 4.2.5
       Installing carrierwave 0.10.0
       Installing protected_attributes 1.1.3
       Installing rails-observers 0.1.2
       Installing jbuilder_cache_multi 0.0.3
       Installing rails-html-sanitizer 1.0.3
       Installing sidekiq-cron 0.2.0
       Installing elasticsearch-model 0.1.7
       Installing rest-client 1.8.0
       Installing friendly_id 5.1.0
       Installing has_secure_token 1.0.0
       Installing seed_dump 3.2.2
       Installing actionview 4.2.5
       Installing elasticsearch-persistence 0.1.7
       Installing stripe 1.30.2
       Installing actionpack 4.2.5
       Installing actionmailer 4.2.5
       Installing actionpack-page_caching 1.0.2
       Installing sprockets-rails 2.3.3
       Installing railties 4.2.5
       Installing coffee-rails 4.1.0
       Installing kaminari 0.16.3
       Installing sass-rails 5.0.1
       Installing responders 2.1.0
       Installing font-awesome-rails 4.6.3.0
       Installing jquery-rails 4.0.3
       Installing rails 4.2.5
       Installing compass-rails 2.0.4
       Installing devise 3.4.1
       Installing devise-async 0.9.0
       Installing notify_with 0.0.2
       Bundle complete! 72 Gemfile dependencies, 152 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from rdoc:
       Depending on your version of ruby, you may need to install ruby rdoc/ri data:
       <= 1.8.6 : unsupported
       = 1.8.7 : gem install rdoc-data; rdoc-data --install
       = 1.9.1 : gem install rdoc-data; rdoc-data --install
       >= 1.9.2 : nothing to do! Yay!
       Post-install message from httparty:
       When you HTTParty, you must party hard!
       Post-install message from rufus-scheduler:
       ***
       Thanks for installing rufus-scheduler 3.0.9
       It might not be 100% compatible with rufus-scheduler 2.x.
       If you encounter issues with this new rufus-scheduler, especially
       if your app worked fine with previous versions of it, you can
       A) Forget it and peg your Gemfile to rufus-scheduler 2.0.24
       and / or
       B) Take some time to carefully report the issue at
       https://github.com/jmettraux/rufus-scheduler/issues
       For general help about rufus-scheduler, ask via:
       http://stackoverflow.com/questions/ask?tags=rufus-scheduler+ruby
       Cheers.
       ***
       Post-install message from compass:
       Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
       Bundle completed (85.57s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
# sh: 2: Syntax error: Unterminated quoted string

sh: 2: Syntax error: Unterminated quoted string
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     NoMethodError: undefined method `dump' for nil:NilClass
 !     (erb):22:in`<main>'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in`result'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:391:in `secrets'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/config/application.rb:30:in`class:Application'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/config/application.rb:22:in `<module:Fablab>'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/config/application.rb:21:in`<top (required)>'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/Rakefile:4:in `require'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/Rakefile:4:in`<top (required)>'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in`load_rakefile'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:94:in`block in load_rakefile'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:93:in`load_rakefile'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:77:in `block in run'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in`standard_exception_handling'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
 !     /tmp/build_4d435dc90c7cdce66b51fccdf7ffd6c0/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/bin/rake:33:in`<top (required)>'
 !     vendor/bundle/bin/rake:16:in `load'
 !     vendor/bundle/bin/rake:16:in`<main>'
 !
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/helpers/rake_runner.rb:102:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
....

I tried to find the issue, but I am not sure about the reason.
So please let me know how to deploy to the heroku.

Many thanks

**Comment by sylvainbx** [comment]
Hi @calemyers723 ,
It looks like your `D3_DATE_FORMAT` env variable is not set in your `config/application.yml` configuration file.
Have a look at [README.md#configuration](https://github.com/LaCasemate/fab-manager#configuration) for details about how to set it

**Comment by kyleevert** [comment]
Hi @sylvainbx 
Thank you for your quick reply.
D3_DATE_FORMAT is inside config/application.yml file.
I just copied from config/application.yml.default and it works fine on my local.
And the issue is come out when pushing the code to heroku.

Thanks.

**Comment by sylvainbx** [comment]
I do not know much about Heroku, maybe @jarod022 does ...
But I've seen this error

> ! NoMethodError: undefined method dump' for nil:NilClass ! (erb):22:in

many times and I'm pretty sure it comes from the mis-configured `D3_DATE_FORMAT` variable.
Maybe on Heroku you should take a different way to configure your environment variables ... I'm sorry but I don't think I can help you further from here. Good luck.

**Comment by kyleevert** [comment]
Thank you very much, @sylvainbx

@jarod022 
Could you help me about this issue?

Regards

**Comment by nflorentin** [comment]
Hi @calemyers723 

In `secrets.yml` file, on line 22, there is this line of code "<%= ENV["D3_DATE_FORMAT"].dump %>".

I'm almost 100% sure that D3_DATE_FORMAT is not set like @sylvainbx said, so ENV["D3_DATE_FORMAT"] returns `nil` so the error `undefined method dump for nil:NilClass is raise` on **line 22** as you can see.

On heroku, if you are trying to run the app in production mode, make sure that your env variables are correctly set.

I'd add that fab-manager cannot be run on Heroku with a free plan because the app need various workers to run, just in case you are not aware of it.

Regards

**Comment by kyleevert** [comment]
Hi @nflorentin 
Thank you for your reply.
I suspect the on line 22 of the secret.yml file last time, so I commented out or removed this line and tried to push to the heroku.
But the error is same.

Have you ever tried to deploy the code to the heroku before?

**Comment by nflorentin** [comment]
It's a bit difficult to help you as we never tried to deploy the app to heroku before and we are not planning to do so in a near future.
I'd suggest you to try to look at the error stack in more depth and find the origin of the error.
