### ISSUE TITLE
espace disque limité 

### ISSUE THREAD

**Issue by gabriel-alex** [sleede/fab-manager#321]
Bonjour, 

J’ai déjà installé FabManager sur des VM à plusieurs reprises et à chaque fois j'ai des problèmes d'espace disque sur FabManager VM. Je n'arrive pas à identifier d’où vient cette quantité de données car pour le moment, nous ne sommes qu’en phase de test, il n'y a quasiment personne qui l'utilise. 

Que dois-je faire pour arrêter / limiter cette production de données ? 1 semaines --> 200 Mo c'est quand même beaucoup.

![image](https://user-images.githubusercontent.com/25355176/152314013-1c78db5a-2af2-4fe9-8971-476e864e1804.png)

Cordialement,

**Comment by sylvainbx** [comment]
Salut, ce sont sûrement les logs qui prennent de la place.
Tu peux vérifier ça en faisant `du -hd 1` depuis le dossier d'installation de fab-manager.
Si ce sont bien les logs, tu peux baisser le niveau de verbosité en changeant [LOG_LEVEL](https://github.com/sleede/fab-manager/blob/master/doc/environment.md#LOG_LEVEL) à `error` (par exemple).
Tiens nous au courant ;)

**Comment by sylvainbx** [comment]
Je clôture cette issue. Si tu rencontres encore le problème ou si tu as d'autres infos sur la raison qui font que les logs augmentent si vite en taille, n'hésite pas à la rouvrir.
