### ISSUE TITLE
Calendar ICS CalDAV

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#33]
Hello, 

most of fablab use open protocol calendars, mostly the .ICS and CalDAV
(self host (owncloud), or google calendar, or whatever) 
to manage a lot of things 
(daily open times, machines availability, benevoles avaibility, training session, events, and so on), 
sometimes on differents calendars, to don't make a big mess, 
and the ability to write and see these calendar on multiple support 
(own website with plugins, other website, smartphone, heavy mail client, cross posting calendar, different page for different calendars, ... )
(for example, wordpress plugin which doesn't support this protocol, for us, are banned for integration in our website/workflow), 
an it's not an annecdotic use of a calendar, it's the main tool of the management of the lab, and of our daily life (with other calendars for work...).
for us, it's a major function, a big need for fab-manager. 
i understand that's it's easy to code with "php calendars" from reading a database, 
but it's not a efficient solution for time managing, if it's not crossplatform, or if you need to connect to the fab-manager website to see this calendar, and on the other hands, to deal with all your real calendars. 

how it's possible to implement it ? 
thanks.

**Comment by matbgn** [comment]
Hi @clemclemmm,

Is such feature still requested by yours ? 

As a small non-profit organisation we're (Fab Lab At3flo) ready to pay a part of the development estimated by the team of development : 2 days of pure dev (conceptualization, maintenance, and so on would be free). The price for one day of dev is also fair (400/day).

Can you imagine that we support together and maybe others for the dev of this feature ?

**Comment by ioknox** [comment]
+1
There is a schedule for that feature ?

**Comment by sylvainbx** [comment]
Tracking this new feature request is now done on [the website dedicated to the Fab-Manager's roadmap](https://roadmap.fab-manager.com/posts/5/open-format-for-project-exchange).
