### ISSUE TITLE
Les créneaux d'une machine ne sont plus visibles dans son agenda de réservation

### ISSUE THREAD

**Issue by EmmanuelG** [sleede/fab-manager#337]
**Describe the bug**
Les créneaux d'une machine (dans notre inventaire c'est "Imprimante 3D - Mark Two") n'apparaissent plus dans la vue agenda quand on souhaite placer des réservation.
La machine est bien "active", et c'est l'ensemble des blocs de temps où elle devrait apparaitre qui ne sont plus affichés.

Toutes les autres machines sont ok autrement.

**Server (please complete the following information):**
 - Instance gérée par Sleed
 - Fab-manager version : 5.3.8

**Browser (please complete the following information):**
 - Name: Firefox
 - Version: 98.0.2

**Comment by gnepud** [comment]
Bonjour @EmmanuelG 

Ce bug est corrigé. On va déployer une nouvelle version sur touts les instances de Fab-Manager.

Merci,
Peng
