### ISSUE TITLE
Problème après mise à jour

### ISSUE THREAD

**Issue by aukfood** [sleede/fab-manager#343]
@sylvainbx ça recommence après la dernière mise à jour, je suis passé de la 4.7.10 à la 5.3.8 sans problèmes et sur la dernière 5.3.12 j'ai la même erreur

Completed 500 Internal Server Error in 36ms (ActiveRecord: 7.0ms | Elasticsearch: 0.0ms)
  
ActionView::Template::Error (Webpacker can't find application.css in /usr/src/app/public/packs/manifest.json. Possible causes:
1. You forgot to install node packages (try `yarn install`) or are running an incompatible version of Node
2. Your app has code with a non-standard extension (like a `.jsx` file) but the extension is not in the `extensions` config in `config/webpacker.yml`
3. You have set compile: false (see `config/webpacker.yml`) for this environment
   (unless you are using the `bin/webpacker -w` or the `bin/webpacker-dev-server`, in which case maybe you aren't running the dev server in the background?)
4. webpack has not yet re-run to reflect updates.
5. You have misconfigured Webpacker's `config/webpacker.yml` file.
6. Your webpack configuration is not creating a manifest.

Your manifest contains:
{
}
):
    67:       Fablab.sessionTours = [];
    68:   </script>
    69: 
    70:   <%= stylesheet_pack_tag 'application', 'plugins', 'printer' %>
    71:   <% unless Stylesheet.theme.nil? %>
    72:   <link rel="stylesheet" media="all" href="<%= stylesheet_path(Stylesheet.theme.id) %>-<%= Stylesheet.theme.updated_at.to_i.to_s %>.css" />
    73:   <%  end %>
  
app/views/application/index.html.erb:70:in `_app_views_application_index_html_erb__271918096445431371_70313379800600'
app/controllers/application_controller.rb:69:in `switch_locale'

J'ai déjà fait le docker-compose exec fabmanager bundle exec rails assets:precompile

**Server (please complete the following information):**
 - OS:  debian 10
 - Kernel: 4.19.0-19-cloud-amd64
 - Fab-manager version 5.3.12

Slts

**Comment by sylvainbx** [comment]
Salut Guillaume,

Est-ce que tu peux poster ici les logs de sortie lorsque tu lances la comande `docker-compose exec fabmanager bundle exec rails assets:precompile`, stp ?

**Comment by aukfood** [comment]
$ docker-compose exec fabmanager bundle exec rails assets:precompile
```
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.88s.
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (1.6ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
D, [2022-05-03T08:17:36.638715 #468] DEBUG -- : Everything's up-to-date. Nothing to do
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.91s.
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.84s.
```

**Comment by sylvainbx** [comment]
Étrange !
Et si, avant de lancer cette commande, tu supprimes le dossier `public/packs`, est-ce que le résultat de la commande est le même ?

Autre question, est-ce que ton utilisateur système est `root` ou autre  ?

**Comment by aukfood** [comment]
Voici ce que j'ai fait :
```
$ rm -rf public/packs/
```

Ensuite : 
```
$ docker-compose exec fabmanager bundle exec rails assets:precompile
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.04s.
  AuthProvider Load (0.6ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.2ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
D, [2022-05-04T08:55:18.645978 #636] DEBUG -- : Everything's up-to-date. Nothing to do
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.75s.
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.86s.
```

Après le répertoire n'existe toujours pas : 
```
$ ls -la public/packs
ls: impossible d'accéder à 'public/packs': Aucun fichier ou dossier de ce type
```

Et les droits : 
```
l$ ls -la
total 140
drwxr-xr-x 15 debian           debian           4096 avril 29 23:41 .
drwxr-xr-x 14 debian           debian           4096 mai    3 11:04 ..
drwxr-xr-x  6 debian           debian           4096 avril 29 22:15 accounting
drwxr-xr-x  3 debian           debian           4096 mai    2 21:50 config
-rw-r--r--  1 debian           debian           2674 mai    2 21:55 docker-compose.yml
-rw-r--r--  1 debian           debian           1996 oct.  21  2019 docker-compose.yml~
-rw-r--r--  1 debian           debian           1357 sept.  5  2018 docker-compose.yml.bak
drwxr-xr-x  4 systemd-timesync systemd-journal  4096 sept.  5  2018 elasticsearch
drwxr-xr-x  4 debian           debian           4096 mars  14  2019 exports
drwxr-xr-x  2 debian           debian           4096 oct.  21  2019 imports
drwxr-xr-x 50 debian           debian           4096 avril 13 17:11 invoices
drwxr-xr-x  3 debian           debian           4096 mars  12  2018 letsencrypt
drwxr-xr-x  2 debian           debian          12288 avril 11 03:01 log
drwxr-xr-x  2 debian           debian           4096 mars  12  2018 plugins
drwx------ 19 systemd-coredump debian           4096 mai    2 22:05 postgresql-9.6
drwxr-xr-x  5 debian           debian           4096 mai    4 10:54 public
drwxr-xr-x  2 systemd-coredump debian           4096 mai    4 10:52 redis
-rw-r--r--  1 debian           debian          49970 oct.  29  2019 result.txt
drwxr-xr-x  2 debian           debian           4096 déc.   9  2019 tmp
-rwxr--r--  1 debian           debian           5284 déc.   7  2020 upgrade.sh
```

**Comment by aukfood** [comment]
@sylvainbx des idéeS ?

**Comment by aukfood** [comment]
@sylvainbx j'ai remplacé packs par new_packs 
```
      - ${PWD}/public/new_packs:/usr/src/app/public/packs
```
Donc FabManager à pu redémarer par contre j'ai une page blanche sur la partie **#!/machines** est-ce qune conséquence ou un autre problème ?

**Comment by sylvainbx** [comment]
Salut Guillaume,

Alors il y a plusieurs choses, dont un truc très étrange :)

Déjà, lorsqu'on fait la mise à jour de Fab-manager via le script de mise à jour, les assets sont compilés dans un dossier séparé (public/news_packs) qui vient ensuite remplacer le dossier des assets (public/packs), ce qui évite d'avoir un temps de coupure trop important. Le dossier à configurer dans le fichier docker-compose est donc bien public/packs, faute de quoi, à la prochaine mise à jour plus rien ne va fonctionner.

Ensuite, lorsque tu lance la commande `rails assets:precompile`, cela doit relancer la compilation des assets dans le dossier courrant des assets (public/packs, par défaut monté sur public/packs sur ton serveur). Il est très étrange que cette commande te réponde `Everything's up-to-date. Nothing to do` alors que tu as supprimé le dossier `public/packs`...

Ce que j’essaierai :  supprimer le dossier public/packs, et recréer un dossier vide. Redémarrer fab-manager avec un `... down && ... up -d`. Relancer la compilation des assets (normalement tu ne dois pas avoir de message "nothing to do") et enfin ouvrir un prompt dans le context du container et , depuis ce prompt, aller vérifier ce qui se trouve dans le dossier public/packs et dans le fichier manifest.json qui ne doivent pas être vides (et doivent correspondre à ce qui se trouve dans le file system de ton serveur).

**Comment by aukfood** [comment]
@sylvainbx c'est mieux, par contre la page machine est toujours vide il y a juste le "+" en haut et le calendrier 
![fabmanager](https://user-images.githubusercontent.com/67263702/170024112-e48ce4b5-2d72-49d3-bc0d-6aecfff18630.png)

**Comment by sylvainbx** [comment]
Est-ce que tu as des erreurs dans la console Javascript (Ctrl+Maj+i dans le navigateur) et/ou dans l'onglet "réseau" ?

**Comment by aukfood** [comment]
@sylvainbx côté réseau pas de soucis.

Côté console JS : 
```


Uncaught RangeError: invalid language tag: ""
    time format.ts:18
    l pending-training-modal.tsx:24
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    P scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    60053 scheduler.production.min.js:12
    Webpack 21
format.ts:18:16
    CanonicalizeLocaleList self-hosted:5763
    InitializeDateTimeFormat self-hosted:6190
    time format.ts:18
    l pending-training-modal.tsx:24
    React 6
    bl self-hosted:1165
    Gi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    P scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Asynchrone : EventHandlerNonNull)
    60053 scheduler.production.min.js:12
    Webpack 23
```

**Comment by sylvainbx** [comment]
Tu peux me faire voir ce qu'il y a dans ton fichier `config/env` ?

Tu peux me l'envoyer par mail si tu préfères

**Comment by aukfood** [comment]
J'ai enlevé les infos sensibles
```
POSTGRES_HOST=postgres
REDIS_HOST=redis
ELASTICSEARCH_HOST=elasticsearch
POSTGRES_USERNAME=postgres

SECRET_KEY_BASE=*******************************

DEFAULT_HOST=URL
DEFAULT_PROTOCOL=https

DELIVERY_METHOD=smtp
SMTP_ADDRESS=mx*****
SMTP_PORT=587
SMTP_USER_NAME=email
SMTP_PASSWORD=password
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# I18N configuration
RAILS_LOCALE=fr
APP_LOCALE=fr
MOMENT_LOCALE=fr
SUMMERNOTE_LOCALE=fr-FR
ANGULAR_LOCALE=fr-fr
FULLCALENDAR_LOCALE=fr
FORCE_VERSION_CHECK=false
ALLOW_INSECURE_HTTP=false

ELASTICSEARCH_LANGUAGE_ANALYZER=french
POSTGRESQL_LANGUAGE_ANALYZER=french

TIME_ZONE=Paris
WEEK_STARTING_DAY=monday
D3_DATE_FORMAT=%d/%m/%y
UIB_DATE_FORMAT=dd/MM/yyyy
EXCEL_DATE_FORMAT=dd/mm/yyyy

LOG_LEVEL=debug
# 10485760 = 10 megabytes
MAX_IMAGE_SIZE=10485760
```

**Comment by sylvainbx** [comment]
J'ai l'impression qu'il te manque ces deux variables (introduites dans la v4.7.0) :
```
INTL_LOCALE=fr-FR
INTL_CURRENCY=EUR
```

**Comment by aukfood** [comment]
:) ça à l'air mieux je valide avec les utilisateurs

**Comment by sylvainbx** [comment]
@aukfood ça fonctionne  ? :-)

**Comment by aukfood** [comment]
j'ai pas eu de retour des utilisateurs donc oui je penses
