### ISSUE TITLE
backPrevLocation button on Notification Center opens reset password page

### ISSUE THREAD

**Issue by gus-abreu** [sleede/fab-manager#348]
After clicking the return button (backPrevLocation), on the Notification Center (https://demo.fab-manager.com/#!/notifications), instead of going back, we are presented with the CHANGE YOUR PASSWORD modal.

1. Go to ['Demo'](https://demo.fab-manager.com/#!/)
2. Click Sign In
3. Fill user admin@example.com and password adminadmin
4. Click confirm
5. Click Notification Center Bell 
6. Click on Return (backPrevLocation)
7. See "CHANGE YOUR PASSWORD" modal.

**Expected behavior**
Go back to main page

**Screenshots**
<img width="700" alt="Screen Shot 2022-05-11 at 11 22 06" src="https://user-images.githubusercontent.com/16217546/167872883-359d8dc5-cb8f-429e-a369-849efa663e8f.png">
<img width="866" alt="Screen Shot 2022-05-11 at 11 22 12" src="https://user-images.githubusercontent.com/16217546/167872900-25ff3d15-fc72-469a-aafc-e07f063cd9d1.png">

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Kernel: 5.4.0-109-generic
 - Fab-manager version 5.3.13

**Browser (please complete the following information):**
 - Name: Safari
 - Version: 14.1.2

Others tried: Chrome 101.0.4951.54, Firefox 100.0 and different computers.

**Additional context**
Error happened on my environment and is replicable on demo.fab-manager.com. Tried Safari and Chrome with same results.

**Comment by gus-abreu** [comment]
Tried on a different computer with the same results. Updated steps to reproduce.

**Comment by sylvainbx** [comment]
Thanks for the update, I  was able to reproduce the issue successfully. I will check that and fix it.
