### ISSUE TITLE
Mac OSX: FATAL:  database "fabmanager_development" does not exist

### ISSUE THREAD

**Issue by Vincent14** [sleede/fab-manager#35]
In [this](https://github.com/LaCasemate/fab-manager#general-guidelines) documentation section, at step 8:

> $ rake db:setup
> WARNING: Use strings for Figaro configuration. 587 was converted to "587".
> /Users/user/.rvm/gems/ruby-2.3.0@fab-manager/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "fabmanager_development" does not exist

It's because your specific postgres documentation don't use the same database. In [this](https://github.com/LaCasemate/fab-manager#setup-fabmanager-in-postgresql) section we have:

> CREATE DATABASE fablab_development OWNER sleede;

By modifying config/database.yml with "fablab_development" instead of "fabmanager_development", it works!

**Comment by sylvainbx** [comment]
Well noticed! Thanks for signaling it and sorry for the inconvenience. This is an old relic of the firsts developments of the fab-manager. We will update the doc ASAP.

**Comment by sylvainbx** [comment]
This was fixed in commit referenced above on the [dev](https://github.com/LaCasemate/fab-manager/tree/dev) branch. These changes will be released with next stable version (probably 2.4.0).
