### ISSUE TITLE
User import is a bit confusing when you didn't read the manual

### ISSUE THREAD

**Issue by mmuman** [sleede/fab-manager#364]
We had an intern here who overwrote the admin password because he used the example CSV file without reading the manual and thought the accounts were actually described by 2 separate lines. The user import page could use some phrasing explicating that the example file actually has both new user and user modification.

Also, the import button I only found after looking at all the page, as it's the only thing without a text. Maybe a tooltip would help?

**Comment by sylvainbx** [comment]
This should be fixed in [v5.4.8](https://github.com/sleede/fab-manager/releases/tag/v5.4.8)
