### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by leMedi** [sleede/fab-manager#37]
Bonjours
j'ai suivie les instrustions dans [https://github.com/LaCasemate/fab-manager/blob/master/docker/README.md](https://github.com/LaCasemate/fab-manager/blob/master/docker/README.md)
 mais quand je execute la command dans 'DB MIGRATE', je recois l'erreur suivant:
[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'xxxxxxxxxx'

j'utilise d'une virtual machine Ubuntu 16.04 sur azure
merci

**Comment by nflorentin** [comment]
Bonjour,

juste au dessus de la ligne `config.secret_key =` dans le fichier `config/initializers/devise.rb`, 
il est écrit:

```
# Devise will use the `secret_key_base` on Rails 4+ applications as its `secret_key`
# by default. You can change it below and use your own secret key.
```

Il n'est donc pas nécessaire de configurer cette variable, du moins pas directement. Il faut par contre configurer la variable `secret_key_base` de fab-manager, pour que devise puisse l'utiliser.
