### ISSUE TITLE
After upgrading to newest version, unable to create user account using manager, administrator or super administrator account. 

### ISSUE THREAD

**Issue by andresrivero** [sleede/fab-manager#374]
**Describe the bug**
After upgrading to newest version, unable to create user account using manager, administrator or super administrator account. 
Previously, managers and admins were able to go to Users section, click on add new user, enter data in form and save to create a new user. Now /api/members post call returns a 500 error. Still able to create a user using the new account form while logged out. Just not as a manager/admin. After doing the most recent update, I did notice that I had to do a ruby rails assets:recompile and docker restart for the app to load, otherwise I got the ruby error splash screen. I am able to create manager and admin accounts but not simple user accounts. I also tried removing the manager, admin and readding them to see if it would fix the user creation not working
**To Reproduce**
1. Go to 'Users' as a manager
2. Click on 'add a new member' button
3. Fill out fields and click save
4. Browser makes a POST call to /api/members but receives a 500 error, {"status":500,"error":"Internal Server Error"}
5. Payload and Error from fabmanager/logs/app-stdout.log
Payload to backend:
user[plan_interval]: 
user[invoicing_profile_attributes][address_attributes][id]: 
user[invoicing_profile_attributes][address_attributes][address]: 999 999
user[invoicing_profile_attributes][organization]: false
user[statistic_profile_attributes][gender]: true
user[statistic_profile_attributes][birthday]: 2022-07-01T00:00:00.000Z
user[statistic_profile_attributes][training_ids][]: 7
user[profile_attributes][user_avatar_attributes][id]: 
user[profile_attributes][last_name]: TEST
user[profile_attributes][first_name]: TESTZ
user[profile_attributes][phone]: 9999999999
user[profile_attributes][website]: 
user[profile_attributes][job]: 
user[username]: test999
user[email]: test99@test.com
user[group_id]: 6
user[password]: testing99
user[password_confirmation]: testing99

fabmanager/logs/app-stdout.log, snippet:
Started GET "/api/trainings?disabled=false" for 66.123.45.67 at 2022-07-14 08:12:16 +0000
Processing by API::TrainingsController#index as JSON
  Parameters: {"disabled"=>"false"}
  Rendering api/trainings/index.json.jbuilder
Started POST "/api/members" for 66.123.45.67 at 2022-07-14 08:12:16 +0000
Processing by API::MembersController#create as JSON
  Parameters: {"user"=>{"plan_interval"=>"", "invoicing_profile_attributes"=>{"address_attributes"=>{"id"=>"", "address"=>"999 999"}, "
organization"=>"false"}, "statistic_profile_attributes"=>{"gender"=>"true", "birthday"=>"2022-07-01T00:00:00.000Z", "training_ids"=>["7
"]}, "profile_attributes"=>{"user_avatar_attributes"=>{"id"=>""}, "last_name"=>"TEST", "first_name"=>"TESTZ", "phone"=>"9999999999", "w
ebsite"=>"", "job"=>""}, "username"=>"test999", "email"=>"test99@test.com", "group_id"=>"6", "password"=>"[FILTERED]", "pass
word_confirmation"=>"[FILTERED]"}}
Started GET "/api/tags" for 66.123.45.67 at 2022-07-14 08:12:16 +0000
Processing by API::TagsController#index as JSON
  Rendering api/tags/index.json.jbuilder
  User Load (3.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["
id", 1], ["LIMIT", 1]]
  User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["
id", 1], ["LIMIT", 1]]
  Tag Load (1.8ms)  SELECT "tags".* FROM "tags"
  Setting Load (1.2ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "conf
irmation_required"], ["LIMIT", 1]]
  Setting Load (1.9ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "conf
irmation_required"], ["LIMIT", 1]]
  Rendered api/tags/index.json.jbuilder (3.2ms)
Completed 200 OK in 7ms (Views: 4.5ms | ActiveRecord: 1.8ms | Elasticsearch: 0.0ms)
  HistoryValue Load (1.3ms)  SELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1
 ORDER BY "history_values"."created_at" DESC LIMIT $2  [["setting_id", 51], ["LIMIT", 1]]
  Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" 
WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL))) 
 [["user_id", 1]]
  HistoryValue Load (1.2ms)  SELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1
 ORDER BY "history_values"."created_at" DESC LIMIT $2  [["setting_id", 51], ["LIMIT", 1]]
  CACHE Role Load (0.0ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."rol
e_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)
))  [["user_id", 1]]
Completed 500 Internal Server Error in 122ms (ActiveRecord: 4.9ms | Elasticsearch: 0.0ms)
  
ActiveRecord::AssociationTypeMismatch (Organization(#70231888511680) expected, got "false" which is an instance of String(#702320200739
60)):
  Role Load (108.1ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id
" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))
  [["user_id", 1]]
  
app/controllers/api/members_controller.rb:43:in `create'
app/controllers/application_controller.rb:70:in `switch_locale'
  Training Load (1.0ms)  SELECT "trainings".* FROM "trainings" WHERE (  Training Load (1.0ms)  SELECT "trainings".* FROM "trainings" WHERE ("trainings"."disabled" = $1 OR "trainings"."disa
bled" IS NULL)  [["disabled", false]]
Started GET "/api/tags" for 66.123.45.67 at 2022-07-14 08:12:16 +0000

**Expected behavior**
New user is created in the system

**Screenshots**

**Server (please complete the following information):**
 - OS: Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
 - Kernel: Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 - Fab-manager version [  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
5.4.12
]

**Browser (please complete the following information):**
 - Name: Tried with both Chrome and Firefox Developer Edition
 - Version: [e.g. 88.0.1, please refer to the About menu of your browser]

**Additional context**
Any help or guidance would be appreciated

**Comment by sylvainbx** [comment]
This should be fixed in [v5.4.13](https://github.com/sleede/fab-manager/releases/tag/v5.4.13)
