### ISSUE TITLE
Projects not appearing on the Gallery page

### ISSUE THREAD

**Issue by Vincent14** [sleede/fab-manager#38]
I followed the [documentation](https://github.com/LaCasemate/fab-manager) and just created two "test" projects:
![1](https://cloud.githubusercontent.com/assets/1963080/18144096/43f239c8-6fc5-11e6-8343-4df587aabbf5.png)

Then, when I open the galery, nothing appear, even after a long time:
![2](https://cloud.githubusercontent.com/assets/1963080/18144095/43ee84c2-6fc5-11e6-8794-c61719dcb65d.png)

By the way, there isn't any button to select if I want to display projects from my fablab or from the whole community:
![3](https://cloud.githubusercontent.com/assets/1963080/18144180/97c88de0-6fc5-11e6-9c7e-a28591f5d5d1.png)

**Comment by sylvainbx** [comment]
Have you "published" your projects or saved them as "draft"? In the second case, this is normal that you don't see them in the public gallery. Anyway, can you report if you see them in your dashboard (just click on your name in the top right corner and select "My projects")?

Your ElasticSearch instance may also be down, if you're running Ubuntu 16.04, you can check it with

``` bash
sudo systemctl status elasticsearch.service
```

Concerning the button to search for projects in the whole network, you must register to [OpenProjects](https://github.com/LaCasemate/openlab-projects) to enable this feature, as specified in [this documentation section](https://github.com/LaCasemate/fab-manager/blob/master/README.md#open-projects). Otherwise, you will only be able to see projects from your own fablab.

**Comment by Vincent14** [comment]
I can confirm that I've published the projects and not only saved them as drafts. They are on the dashboard:
![4](https://cloud.githubusercontent.com/assets/1963080/18175749/d056e78a-7072-11e6-8d40-4e907fdb48e3.png)

I haven't installed ElasticSearch, here is the problem. I don't know why, I was sure to read somewhere this configuration was optional. I'll try then close this issue, thanks =)

**Comment by Vincent14** [comment]
Well, I'm very unfortunate because I encounter a new error :( I'm following [this section](https://github.com/LaCasemate/fab-manager#install-elasticsearch-on-ubuntudebian) of the documentation. I performed the Java installation, adding the repo to APT, upgraded it then installed elasticesearch without any problem.

At step 5, I need to start the server. Basically, as an occasional developer, I would start the server when I need it. Whatever, I've followed the doc, here is the result:

> $ sudo /bin/systemctl daemon-reload
> $ sudo /bin/systemctl enable elasticsearch.service
> elasticsearch.service is not a native service, redirecting to systemd-sysv-install
> Executing /lib/systemd/systemd-sysv-install enable elasticsearch

Next step in the tutorial failed (lot of more lines, same error on each):

> $ rake fablab:es_build_stats
> WARNING: Use strings for Figaro configuration. 587 was converted to "587".
> DELETE stats
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 9200: Connexion refusée

I tried many other ways:

> $ sudo /etc/init.d/elasticsearch start
> [ ok ] Starting elasticsearch (via systemctl): elasticsearch.service.

or:

> $ sudo service elasticsearch start

**Comment by Vincent14** [comment]
I tried:

> sudo lsof -iTCP -sTCP:LISTEN | grep elasticsearch
> sudo lsof -i TCP | grep 9200

Both return an empty line ='(

**Comment by Vincent14** [comment]
This problem seems specific to Ubuntu 16.04. Strangely, only one topic give the solution. If you can reproduce it, again please, add a note in the documentation =) https://discuss.elastic.co/t/cant-start-elasticsearch-with-ubuntu-16-04/48730/9

**Comment by Vincent14** [comment]
I also strongly recommand you to add this inline command to refresh ES for developers:

> rails r "StatisticService.new.generate_statistic({start_date: 0.day.ago
> .beginning_of_day,end_date: 0.day.ago.end_of_day})"

**Comment by Vincent14** [comment]
Just another good trick to get the DB updating while developing (every 10 seconds here):

> watch -n 10 'rails r "StatisticService.new.generate_statistic({start_date: 0.day.ago.beginning_of_day,end_date: 0.day.ago.end_of_day})"'
