### ISSUE TITLE
Calendar slots and machines linked to user groups

### ISSUE THREAD

**Issue by oscgonfer** [sleede/fab-manager#393]
Hi!

I would like to ask (first) if this type of usage is possible: is it possible to have calendar slots for each machine, and eventually machines, which booking can be limited for different user groups?

To specify, in case that my question is not clear: imagine you have three user groups A, B, and C. You also have three machines, X, Y, and Z. The functionality would include that, for instance, users from group A can only book machine X, and not Y, Z. Users from group B can book machine Y and Z in the mornings, and users from group C can book machine Y and Z in the afternoons. 

If not, would you consider something like that as a funcionality?

**Comment by sylvainbx** [comment]
Hi @oscgonfer,

Your question is absolutely clear. For now, this kind of behavior is managed using "tags" (admin > Users > Tags). You can assign tags to members and to slots. If a slot (machine or anything else) has a tag, only members with the same tag will be able to book the resource on this slot.

Does that solves your use case? Otherwise, maybe we can simply add an auto-tag feature that add a configurable tag to people in a group and remove it when the member leaves the group? This would be easier to do than adding a restriction by group.

**Comment by oscgonfer** [comment]
Hi @sylvainbx !

In terms of functionality, the tags are perfect. This is a great feature!

> If a slot (machine or anything else) has a tag, only members with the same tag will be able to book the resource on this slot.

I am able to have tags in slots and users, but I haven't been able to tag machines - where should I look at?

> Does that solves your use case? Otherwise, maybe we can simply add an auto-tag feature that add a configurable tag to people in a group and remove it when the member leaves the group? This would be easier to do than adding a restriction by group.

I think this makes sense, but I have not spent yet that much time using fab-manager to be able to respond in terms of practicality.

**Comment by sylvainbx** [comment]
> I am able to have tags in slots and users, but I haven't been able to tag machines - where should I look at?

You can't tag machines, it is pointless. A slot is necessarily for one (or many machines), so when you create a slot, you associate it with a machine, then you add it some tags. Only people with that tag will be able to book that machine for that slot. A machine without slots cannot be booked anyway.

If you change your mind later, you can always create new slots for the same machine with another tag or no tags at all.

**Comment by oscgonfer** [comment]
Understood! Thanks!
