### ISSUE TITLE
Problème lors de la mise à jour

### ISSUE THREAD

**Issue by gabriel-alex** [sleede/fab-manager#406]
Bonjour,

J'ai fait plusieurs installation propre sur le serveur suite à des problèmes lors de mise à jour. J'ai fais une installation propre il y a quelques jours et je viens d'essayer de faire la mise à jour de 5.4.21 à 5.4.22. 
Pour ce faire, je fais la commande \curl -sSL upgrade.fab.mn | bash -s -- -c "rails fablab:maintenance:regenerate_statistics[2021,06]" comme indiqué sur github. 
Cela se passe plutôt bien mais lorsque la commande fablab:maintenance:regenerate_statistics[2021,06] est effectuée, il y a une erreur à la suite d'une requête SQL:
Role Load (2.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 LIMIT $2  [["name", "member"], ["LIMIT", 1]]
rails aborted!
NoMethodError: undefined method `id' for nil:NilClass

**Expected behavior**
Finalement, la mise à jour est annulée et la version reste sur 5.4.21. 

**Server :**
 - OS: Ubuntu 20.04.5 LTS 
 - Kernel: GNU/Linux 5.4.0-126-generic x86_64
 - Fab-manager version: 5.4.21

Je ne sais pas si j'ai oublié quelque chose, ou si c'est un problème généralisé. Du coup, je n'ose pas remettre les données.

Merci d'avance. 

Cordialement.

**Comment by sylvainbx** [comment]
Salut,

Il y a eu un problème avec la version 5.4.22 qui a empêché la création des images docker de cette version ([comme indiqué ici](https://github.com/sleede/fab-manager/releases/tag/v5.4.22)). D'autre part, dans la version 5.2.21, c'est justement cette commande (maintenance:regenerate_statistics) qui était buguée, d'où l'erreur que tu rencontres. Réessaye une mise à jour avec une version >= 5.4.23 et tout devrait bien se passer :wink:
