### ISSUE TITLE
Error 500 when create a new event with missing fields

### ISSUE THREAD

**Issue by dsmrs** [sleede/fab-manager#409]
**Describe the bug**
A really small bug =) When creating a new event, if the "all day" yes/no radio button never had been selected, I can still push the button to create the event, but I have a error 500, with no clear advice.

**To Reproduce**
1. create a new event
2. fill the required fields acccept for the all day radio button
3. try to clic to create the event

**Expected behavior**
We souldn't be able to clic on the create button if the radio button haven't been selected, or we should have a clear error in return (a catch error on the server).

**Server (please complete the following information):**
 - OS: Yunohost 11
 - Fab-manager version 5.4.20

**Comment by sylvainbx** [comment]
Hello, this should be fixed with [fab-manager v5.6.0](https://github.com/sleede/fab-manager/releases/tag/v5.6.0). Please feel free to reopen this issue if this is not the case.
