### ISSUE TITLE
ergonomic : edit button and remove

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#41]
1/ edit button
when i document a project, 
i save the project each 5 minutes 
(because we don't know if the system save it each seconds, or not),
and i must go back on the top of the page to clic on the edit button, to add new steps

for the ergonomic use, it would be better if the "edit" button is at the top AND at the end of the last step (so at the bottom of the page too)

2/ delete button
when we are logged in, 
the delete button is just next to the edit button, 
and it's very dangerous 
(more other because there is yet no confirmation message to delete a project).
it would be less dangerous, and more logical to allow user to delete their own project only in edit mode, not just in "logged in" mode.

**Comment by sylvainbx** [comment]
There is no auto-saving for projects, it is your own responsability to save your project periodically.

I didn't get what you mean about the ergonomy, perhaps I can suggest you to use one of those key for an easier navigation inside the page:
<img src="http://origin.arstechnica.com/journals/hardware.media/logitechillumkg-2-ars.jpg" alt="keyboard"/>

Concerning the delete button, we added a confirmation before deleting a project in commit https://github.com/LaCasemate/fab-manager/commit/d5b06d08ad2326bfc4e9119815dd49eee183bc1e.
witch was released with [version 2.3.0](https://github.com/LaCasemate/fab-manager/blob/v2.3.0/CHANGELOG.md), two months ago. Thanks to update your fab-manager instance before reporting bugs.

**Comment by clemclemmm** [comment]
i'm using the fab manager of la casemate, 
so i'm sorry if this one is not up to date to the latest release, 
but i can't do it by myself, as a user.

i thought it was the most up to date fabmanager in france, 
as a showcase,
but can't really know (see other issue on this topic).

thanks for the changelog, i will see it more often now.
