### ISSUE TITLE
OpenSSL wrong number version

### ISSUE THREAD

**Issue by Corenb** [sleede/fab-manager#410]
Hello !
Since few weeks, my fabmanager won't send SMTP mails... I get this error :

`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number`

FYI I use Office365 as mail provider and here are my env SMTP settings :

> DELIVERY_METHOD=smtp
> SMTP_ADDRESS=smtp.office365.com
> SMTP_PORT=587
> SMTP_USER_NAME=fablab-admin@*****.fr
> SMTP_PASSWORD=********
> SMTP_AUTHENTICATION=login
> SMTP_ENABLE_STARTTLS_AUTO=true
> SMTP_OPENSSL_VERIFY_MODE=
> SMTP_TLS=true

Thanks for your help !

**Comment by sylvainbx** [comment]
Hello,
Can you try setting `SMTP_TLS=false` and retry to send an email with that configuration?
Please keep me updated!

**Comment by Corenb** [comment]
Hello,
It seems to work fine, thank you !
