### ISSUE TITLE
Cancel reservations via the "My Reservations" dashboard area.

### ISSUE THREAD

**Issue by Norde** [sleede/fab-manager#419]
Hello Fab-manager team and thank you for all your work on this great tool!

The"My reservation" user dashboard show a useful list of reserved spaces and machines.
However, this list is not interactive.
Would it be possible to allow users to cancel or modify their reservation via this interface?

- For the cancellation a simple confirmation dialog would be enough.
- For the modification the user would be redirected to the calendar of the corresponding machine or room

This suggestion also applies to trainings and events.

PS: It is impossible to login on https://feedback.fab-manager.com using github account, hence I made my feature request here

**Comment by sylvainbx** [comment]
Hi @Norde ,
Thanks for your feedback. I just fixed the GitHub login issue on https://feedback.fab-manager.com/. Can you please post your feature request there? We want to keep GitHub for issues tracking, thanks.

**Comment by Norde** [comment]
Thanks for the quick fix @sylvainbx, I have transferred my feature request on Fider.
