### ISSUE TITLE
add more than only one picture per step

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#42]
in the documentation tool, 
we can add only one picture per step. 
but depending on how we document, 
and how much information we give, 
we need to add more than one.
thanks.

**Comment by sylvainbx** [comment]
Maybe you havn't noticed that the WYSIWYG editor for steps description allows you to include images, in addition to the step's main image.

You can either upload a max 4KB image or link an external image without any limitation.

As an example, check out this project: https://fablab.lacasemate.fr/#!/projects/livre-de-cuisine

**Comment by Vincent14** [comment]
Hi, I have the same problem as @clemclemmm I need more pictures (in particular for description). When selecting picture from the WYSIWYG toolbar, the picture is not added, nothing happen. Perhaps is it because of loading time? Or the picture size? It miss a UX/UI notice

edit: I'll open a dedicated issue for the picture size problem.

**Comment by clemclemmm** [comment]
we have our own server, we teach our user to be owner of there data, not to use google or others, it's not a possibility for us to store our image on third party service like imgur.

it's not possible for our user to store there data somewhere else (than on our server), and put just a link in the description. 
our users (and a lot of people) are not very confortable with tools/technology, and are not technician. 
the first reason why they don't documentate is "i'm not good with computers".
if they document' (and it's not the case of all...), they just want to put picture, and that it's works. it's has to be simple, and efficient. not complexe has store image somewhere else, and put a link in the description.

what is that 4kb-base64-stored-in-the-database-image for ?

**Comment by pmoutet** [comment]
@clemclemmm Au passage, tu pourras communiquer stp l'URL de ton Fab Manager que je puisse le rajouter sur la carte des déploiements ? http://u.osmfr.org/m/104665/

Comme vous avez l'air au taquet sur la documentation, je peux aussi te fournir des clés pour mutualiser vos projets avec le réseau Fab Manager.

Merci pour tes retours :)

**Comment by sylvainbx** [comment]
This feature was implemented in commit ba5e5752a4beeb16fb85bce33295889cbe1f6a24.
The stable [release 2.4.2](https://github.com/LaCasemate/fab-manager/releases/tag/v2.4.2) now contains this improvement.
