### ISSUE TITLE
Powered by witch version

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#43]
hello, 
when you go on a fabmanager website, 
it's not possible to know witch version is setup on the server we are going to use. (the last or not)
for exemple, on the one at la casemate, at the bottom right hand corner, it's just written "Powered by Fab Manager"
it would be great to add the version number here : "Powered by Fab Manager 2.3.0"
thanks

**Comment by Vincent14** [comment]
For security reasons, it should not be displayed on the frontoffice but only on the backoffice

**Comment by sylvainbx** [comment]
This will be resolved, starting from fab-manager's release 2.4.0.
When **logged as admin**, the following item will be available:
![fabmanager-version](https://cloud.githubusercontent.com/assets/5102799/18753083/a1cdc488-80e4-11e6-9301-a5ff3ff1c0c8.png)
