### ISSUE TITLE
Invalid email or password on fresh install

### ISSUE THREAD

**Issue by Tbwan** [sleede/fab-manager#430]
I am testing out Fab Manager on my own linux PC to see if it will work for my purposes. Installation went smoothly, and the site displays at "localhost" in the browser. However, I cannot log in to the admin account that was created during installation via the terminal.

First, I had the "Unprocessable Entity" issue, which was fixed by changing the env file to "ALLOW_INSECURE_HTTP=true"
Now, when I try to log in, I get a different error: "Invalid email or password."

Since this is just a test environment, I left all smtp related options blank or default, since I am not testing online yet. Does the database require confirmation of the admin email account before allowing it? or is there something else I may be missing?

**Comment by sylvainbx** [comment]
Hi @Tbwan and thanks for your report. This may be a bug related to some special configuration ... or not, let's investigate!

Please can you report here any logs for the JS console and from the server output (in log/app-stdout.log) when the error occurs?

**Comment by Tbwan** [comment]
I don't see any error listed in the app-stdout.log file, but this is what the web console shows on a failed login (please note I have replaced my actual email with the text "THISISMYEMAIL" for privacy):

Authentication failed: {"data":{"error":"Invalid email or password."},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/users/sign_in.json","data":{"user":{"email":"THISISMYEMAIL","password":"Admin-admin1234"}},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-XSRF-TOKEN":"2Oq3IplwEf6KqmF0LTlgdUzTYHHsAG/Hog2l1UC249ItL6hodPKEuujYwGobzr8lfiPo+1zd1ah3Z+jSG8Hxjw=="},"cached":false},"statusText":"Unauthorized","xhrStatus":"complete"} application.js:457:24
    login application.js:457
    Angular 7
        d
        d
        $digest
        $apply
        z
        _
        onload

**Comment by Tbwan** [comment]
If I try to log in a second time, the message is slightly different, but mostly similar:

Authentication failed: {"data":{"error":"Invalid email or password."},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/users/sign_in.json","data":{"user":{"email":"THIS ISMYEMAIL","password":"Admin-admin1234"}},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-XSRF-TOKEN":"2Oq3IplwEf6KqmF0LTlgdUzTYHHsAG/Hog2l1UC249ItL6hodPKEuujYwGobzr8lfiPo+1zd1ah3Z+jSG8Hxjw=="},"cached":false},"statusText":"Unauthorized","xhrStatus":"complete"} application.js:457:24
    login application.js:457
    Angular 15
        d
        d
        $digest
        $apply
        z
        _
        onload
        (Async: EventHandlerNonNull)
    get
        k
        k
        d
        d
        $digest
        $apply
        compile
    jQuery 2
        dispatch
        handle

**Comment by sylvainbx** [comment]
Thanks for your answer. The browser logs doesn't says anything special. Please can you report here the content of ` tail -f /apps/fabmanager/log/app-stdout.log` when the login request is made (event if there's no error, it may say something usefull for debugging)?

Moreover, can you try starting an application console (with `curl -sSL run.fab.mn | bash`) and run the following command to see if your admin was created at setup:

```ruby
User.find_by(email: "THIS ISMYEMAIL")
```

**Comment by Tbwan** [comment]
Since we last spoke, I reinstalled my entire server, and now it works fine. So good news! Unfortunately, this means that I can't tell any more info about what happened. I suspect that something may have been wrong with the docker container running postgres db, but I am not sure.
