### ISSUE TITLE
rake aborted

### ISSUE THREAD

**Issue by GrazianoC** [sleede/fab-manager#446]
t**Describe the bug**
When i try to install fab  manager on step to install database, i have this issue 
rake aborted!
Errno::EISDIR: Is a directory @ io_fillbuf - fd:5 config/auth_provider.yml
/usr/src/app/lib/provider_config.rb:7:in `initialize'
/usr/src/app/config/application.rb:79:in `new'
/usr/src/app/config/application.rb:79:in `<class:Application>'
/usr/src/app/config/application.rb:27:in `<top (required)>'
/usr/src/app/Rakefile:6:in `require_relative'
/usr/src/app/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)

- Current value: DISK_SPACE_MB_ALERT=1024
- New value? (leave empty to keep the current value)
  >
[+] Running 3/0
 ✔ Container fabmanager-redis-1          Created0.0s
 ✔ Container fabmanager-postgres-1       Created0.0s
 ✔ Container fabmanager-elasticsearch-1  Created0.0s
[+] Running 3/3
 ✔ Container fabmanager-redis-1          Started0.6s
 ✔ Container fabmanager-postgres-1       Started0.5s
 ✔ Container fabmanager-elasticsearch-1  Started0.5s
rake aborted!

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/71138294/230789548-acc9d716-3639-43e8-993f-9a425ed29f71.png)
![image](https://user-images.githubusercontent.com/71138294/230789571-25f6acd5-eb97-442d-a8b6-08314134773e.png)
![image](https://user-images.githubusercontent.com/71138294/230789622-602934af-af59-42ca-b01b-dbdafae8faec.png)

**Server (please complete the following information):**
 Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-69-generic x86_64)
 Linux fabmanager 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 service "fabmanager" is not running container #1

**Comment by gnepud** [comment]
Hi @GrazianoC 

I would like to inform you that the issue has been fixed in the latest release [v6.0.3](https://github.com/sleede/fab-manager/releases/tag/v6.0.3).

Thanks
