### ISSUE TITLE
Week calendar broken

### ISSUE THREAD

**Issue by Guichaguri** [sleede/fab-manager#449]
**Describe the bug**
The "week" calendar is broken. No reservations show up.

**To Reproduce**
1. Open the calendar, both the public and the admin are broken.
2. Click on "week"
3. Nothing shows up, the API returns the reservations as expected but there is an error in the console from Fullcalendar.

**Expected behavior**
The weekly reservations show up as expected.

**Screenshots**
![image](https://github.com/sleede/fab-manager/assets/1813032/d923dbc6-e817-4feb-95c4-9ed34ed8de8e)

**Server (please complete the following information):**
 - OS: `Ubuntu 20.04.4 LTS`
- Kernel: `Linux ip-172-31-83-71 5.15.0-1020-aws #24~20.04.1-Ubuntu SMP Fri Sep 2 15:29:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Fab-manager version: `6.0.6`

**Browser (please complete the following information):**
 - Name: Google Chrome
 - Version: 113.0.5672.127

**Additional context**
The error can also be reproduced on the official demo: https://demonstration.fab-manager.com/#!/calendar

Error logs:
```
fullcalendar.js:6211 Uncaught TypeError: Cannot read properties of null (reading 'top')
    at e.getTopPosition (fullcalendar.js:6211:50)
    at a.computeTimeTop (fullcalendar.js:13112:36)
    at a.computeInitialDateScroll (fullcalendar.js:12611:33)
    at a.applyScroll (fullcalendar.js:4128:35)
    at a.applyQueuedScroll (fullcalendar.js:4116:18)
    at a.popScroll (fullcalendar.js:4111:14)
    at a.onRenderQueueStop (fullcalendar.js:3835:18)
    at a (fullcalendar.js:1631:28)
    at a.dispatch (jquery.js:5430:27)
    at f.handle (jquery.js:5234:28)
```

**Comment by Guichaguri** [comment]
The "day" calendar is also broken, but the "month" is not.

**Comment by gnepud** [comment]
Hi @Guichaguri 

Thank you for reporting this issue. It has been fixed.
