### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by leMedi** [sleede/fab-manager#46]
Hi
I made a stable CoreOs virtual machine on azure
and went on to execute commands in 
[https://github.com/LaCasemate/fab-manager/tree/master/docker](https://github.com/LaCasemate/fab-manager/tree/master/docker)
i am using docker (no composer)
when i get to the **DB MIGRATE** step
and i run the command 
`docker run --rm \
           --link=fabmanager-postgres:postgres \
           --link=fabmanager-redis:redis \
           --link=fabmanager-elastic:elasticsearch \
           -e RAILS_ENV=production \
           --env-file /home/core/fabmanager/config/env \
           sleede/fab-manager \
           bundle exec rake db:migrate`

i get this error 

> [WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.
> rake aborted!
> Devise.secret_key was not set. Please add the following to your Devise initializer:
> 
>  config.secret_key = 'e0d147938ae81b79d220f530ea084385bbe14d1801b116e428053c1302000f6bcfa2dcab68cd5cce5a4dcbf56e90830f07f79729aa9fedba1f53f286ce2b6bbc'
> 
> Please ensure you restarted your application after installing Devise or setting the key.

any help??
thanks

**Comment by jarod022** [comment]
Hello,

Have you created the file env in /home/core/fabmanager/config
The environment variable "SECRET_KEY_BASE" is it configured?
See the file "env.example" in /docker

**Comment by leMedi** [comment]
i did something different.
i added the SECRET_KEY_BASE as an environment variable in docker

```
docker run --rm \
 --link=fabmanager-postgres:postgres \
 --link=fabmanager-redis:redis \
 --link=fabmanager-elastic:elasticsearch \
 -e RAILS_ENV=production \
 -e SECRET_KEY_BASE=e0d147938ae81b79d220f530ea084385b.....
 --env-file /home/core/fabmanager/config/env \
 sleede/fab-manager \
 bundle exec rake db:migrate
```

and it worked
but your solution seems to be better
thanks
