### ISSUE TITLE
GET /open_api/v1/subscriptions

### ISSUE THREAD

**Issue by XavETS** [sleede/fab-manager#465]
Hello!
In the event when an API read is requested, the "expiration_date" seems to give faulty results in some cases.
The 'expiration date' from OpenAPI reads the date of expiration of the subscription but does not add additionnal free days.
(FYI, the subscription export from FabManager does not carry this issue)
Thanks!

Bonjour!
Dans le cas où une requête API est demandée, la "date_d'expiration" semble donner des résultats erronés dans certains cas.
La 'date d'expiration' d'OpenAPI lit la date d'expiration de l'abonnement mais n'ajoute pas de jours gratuits supplémentaires.
(Pour information, l'exportation d'dinformations d'abonnement depuis FabManager n'a pas ce problème)
Merci!

**Comment by XavETS** [comment]
> Hello! In the event when an API read is requested, the "expiration_date" seems to give faulty results in some cases. The 'expiration date' from OpenAPI reads the date of expiration of the subscription but does not add additionnal free days. (FYI, the subscription export from FabManager does not carry this issue) Thanks!
> 
> Bonjour! Dans le cas où une requête API est demandée, la "date_d'expiration" semble donner des résultats erronés dans certains cas. La 'date d'expiration' d'OpenAPI lit la date d'expiration de l'abonnement mais n'ajoute pas de jours gratuits supplémentaires. (Pour information, l'exportation d'dinformations d'abonnement depuis FabManager n'a pas ce problème) Merci!

@sylvainbx @gnepud pourriez-vous me dire si ce bogue sera considéré ? Nous avons mis en place un 'workaround' mais nous apprécierons grandement d'utiliser l'API
Merci!

**Comment by gnepud** [comment]
Hello @XavETS 

Thank you for reporting this issue. I have already fixed it and will release a new version today.
