### ISSUE TITLE
dev (docker) install

### ISSUE THREAD

**Issue by phd0** [sleede/fab-manager#48]
installation _from scratck_ avec docker sur machine Debian 8 "bac a sable" dans le but de jouer au béta testeur. (version avec nginx en conteneur séparé)
installation OK mais page principale presque vide : 
![bug01](https://cloud.githubusercontent.com/assets/1939211/19050378/97abc9aa-89ae-11e6-9455-447679d3872a.PNG)

sur la log app-stdout : 

```
ActionController::RoutingError (No route matches [GET] "/stylesheets/app.printer.css")
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js")
ActionController::RoutingError (No route matches [GET] "/angular-i18n/angular-locale_fr-fr.js")
ActionController::RoutingError (No route matches [GET] "/fullcalendar/dist/lang/fr.js")
```

et ainsi de suite ... j'ai pourtant bien exécuté la commande `rake assets:precompile`
si je _restart_ le conteneur : pareil. 
si je tue le conteneur et le recréé : pareil. 

contenu de mon `docker ps`

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
1ec2ce2b2f5b        sleede/fab-manager:dev   "/usr/bin/supervisord"   21 minutes ago      Up 21 minutes       3000/tcp                                   fabmanager
5e8898f65d57        nginx:1.9                "nginx -g 'daemon off"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
69e5dd1b62c0        elasticsearch:1.7        "/docker-entrypoint.s"   2 hours ago         Up 2 hours          9200/tcp, 9300/tcp                         fabmanager-elastic
fbf9bde538e0        redis:3.0                "docker-entrypoint.sh"   2 hours ago         Up 2 hours          6379/tcp                                   fabmanager-redis
c559e47d3323        postgres:9.4             "/docker-entrypoint.s"   2 hours ago         Up 2 hours          5432/tcp                                   fabmanager-postgres
```

**Comment by phd0** [comment]
La commande `docker restart nginx` donne : 
`Error response from daemon: Cannot restart container nginx: Cannot link to a non running container: /fabmanager AS /nginx/fabmanager`
... ca peux aider là

du coup un docker ps donne : 

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                NAMES
1ec2ce2b2f5b        sleede/fab-manager:dev   "/usr/bin/supervisord"   33 minutes ago      Up 5 minutes        3000/tcp             fabmanager
69e5dd1b62c0        elasticsearch:1.7        "/docker-entrypoint.s"   2 hours ago         Up 2 hours          9200/tcp, 9300/tcp   fabmanager-elastic
fbf9bde538e0        redis:3.0                "docker-entrypoint.sh"   2 hours ago         Up 2 hours          6379/tcp             fabmanager-redis
c559e47d3323        postgres:9.4             "/docker-entrypoint.s"   2 hours ago         Up 2 hours          5432/tcp             fabmanager-postgres
```

**Comment by jarod022** [comment]
hello,

D'après ton dernier Docker ps, nginx n'est pas lancé.
Il faut donc bien le relancer et vérifier que la conf dans config/nginx est ok (voir model nginx.conf.example).

De plus, il est conseillé d'utiliser docker-compose si ce n'est pas déjà le cas pour facilement gérer le lancement des containers avec les différentes dépendances.

De quel façon as-tu lancer le rake assets:precompile ? 
Avec docker-compose il faut lancer cette commande : 
`docker-compose run --rm fabmanager bundle exec rake assets:precompile`

**Comment by phd0** [comment]
effectivement la version docker-compose est plus facile a utiliser : merci
