### ISSUE TITLE
after upgrade, emails are not sent anymore

### ISSUE THREAD

**Issue by maximelehericy** [sleede/fab-manager#494]
**Describe the bug**
after fabmanager upgrade last week, emails are not sent anymore. Sidekiq shows this error many times in the retries tab:
```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=185.245.249.202:587 state=error: certificate verify failed (unable to get local issuer certificate)
```

A bit of history:
I am new to fabmanager, but have a bit of IT background, and therefore helping the local fablab with its new project: fabmanger deployment.

A few weeks ago, I struggled configuring properly fabmanager so the email go out. But I finally succeded. There was the same error as above in sidekiq:

Back then, I had managed to overcome it by following the environnement variables guidelines about SMTP [here](https://github.com/sleede/fab-manager/blob/master/doc/environment.md#general-settings)

The config/env file looked like this:

```
DELIVERY_METHOD=smtp
SMTP_ADDRESS=smtpauth.infini.fr
SMTP_PORT=587
SMTP_USER_NAME=***************
SMTP_PASSWORD=**************
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=peer
```

and I had added a volume to fabmanager docker container, by adding under `services > fabmanager > volumes`  in to the docker-compose.yml:
`./letsencrypt/etc/live/fabmanager.konkarlab.bzh/:/etc/ssl/my-certs/`

So far, it had solved my problem.

Last week, I upgraded fabmanager from v6.3.16 to v6.3.33 with
```
## from v6.3.16 to v6.3.33
\curl -sSL upgrade.fab.mn | bash -s --  -c "rails fablab:maintenance:regenerate_statistics[2014,1]" -c "rails fablab:openlab:bulk_export" -c "rails fablab:openlab:bulk_update"
```

Since this upgrade, emails are not sent anymore (we've noticed just today). And the same error as before appears in sidekiq.

NB: After that upgrade, I had the ruby error page, lookked at the logs, browsed a bit the forum, ran `docker-compose run --rm fabmanager bundle exec rails assets:precompile`, but in the end false alert, I think I had cache issue in the browser and a ctrl+F5 seemed to solve my issue: fabmanager was back online. I don't know if that command can impact or not on today's problem.

I spent a few hours today trying to solve this, but I am now clueless :(

Any help would be greatly appreciated here 🙏

**Comment by gnepud** [comment]
Hi @maximelehericy 

Do you have `SMTP_CA_FILE` and `SMTP_CA_PATH` defined in your `config/env`?
I believe the application cannot load the certificate file, based on the error.

Thanks

**Comment by maximelehericy** [comment]
@gnepud thanks for answering.
So I initially I did not have them.
I tried to set only one of these, and both, but I still have the same error. Now I have this:
```
SMTP_CA_PATH=/etc/letsencrypt/live/fabmanager.konkarlab.bzh/
SMTP_CA_FILE=/etc/letsencrypt/live/fabmanager.konkarlab.bzh/fullchain.pem
```
With this `- ./letsencrypt/etc/:/etc/letsencrypt` in fabmanager volumes.

When in the container, 
`cat $SMTP_CA_FILE` shows the certificate (I choose to set the fullchain)
and `cd $SMTP_CA_PATH` navigates to the certifcate folder where I have cert.pem, chain.pem, fullchain.pem and privkey.pem files.

**Comment by maximelehericy** [comment]
NB: I tried to set SMTP_CA_FILE to simply fullchain.pem, but then I have another error `OpenSSL::SSL::SSLError: SSL_CTX_load_verify_file: system lib` which I believe says that the application can't load the file. So I reverted to full path.

**Comment by gnepud** [comment]
> @gnepud thanks for answering. So I initially I did not have them. I tried to set only one of these, and both, but I still have the same error. Now I have this:
> 
> ```
> SMTP_CA_PATH=/etc/letsencrypt/live/fabmanager.konkarlab.bzh/
> SMTP_CA_FILE=/etc/letsencrypt/live/fabmanager.konkarlab.bzh/fullchain.pem
> ```
> 
> With this `- ./letsencrypt/etc/:/etc/letsencrypt` in fabmanager volumes.
> 
> When in the container, `cat $SMTP_CA_FILE` shows the certificate (I choose to set the fullchain) and `cd $SMTP_CA_PATH` navigates to the certifcate folder where I have cert.pem, chain.pem, fullchain.pem and privkey.pem files.

I think the file `fullchain.pem` appears to be the certificate for your domain name fabmanager.konkarlab.bzh, not for your SMTP server. 

My question is your SMTP server has SSL enabled? 

If it is not, you don't need to configure SSL in the SMTP settings; you can set:
```
SMTP_OPENSSL_VERIFY_MODE=
SMTP_TLS=false
```

If it is SSL enabled, you'll need to configure SSL in the SMTP settings as follows:
```
SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_TLS=true
SMTP_CA_PATH=/path/to/certificate_folder
SMTP_CA_FILE=/path/to/certificate_folder/certificate.pem
```

**Comment by maximelehericy** [comment]
> If it is not, you don't need to configure SSL in the SMTP settings; you can set:
> 
> ```
> SMTP_OPENSSL_VERIFY_MODE=
> SMTP_TLS=false
> ```

oh, thank you !!
so the correct configuration is:

```
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_TLS=false
```

so I probably had done a change to my config prior the upgrade that I did not applied back then and that applied when recreating the containers after the upgrade...

thank you for your help 🙏
