### ISSUE TITLE
edition du texte de presentation du fab lab

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#5]
il n'est pas possible d'editer le texte par defaut de presentation du fablab, sans rentrer dans la BDD.

**Comment by jarod022** [comment]
Bonjour,

Le texte présent sur la page "A propos" n'est pas présent en BDD, mais dans un fichier template : 
fab-manager/app/assets/templates/shared/about.html.erb

Pour rappel, Fab Manager dans sa version OpenSource est une extraction limitée de la version Premium, pouvant servir de point de départ à un Fab Lab. Mais cela requiert de l'adapter à ses besoins.
Nous compléterons la documentation pour faciliter sa reprise.
