### ISSUE TITLE
Machine booking/reservation not working

### ISSUE THREAD

**Issue by kennethlimcp** [sleede/fab-manager#50]
1.) Unable to select any slot in the machine booking screen

<img width="996" alt="screen shot 2016-10-07 at 16 47 17" src="https://cloud.githubusercontent.com/assets/6760914/19184055/dd82dafc-8cad-11e6-8b98-e5f966b0af9c.png">

**Comment by sylvainbx** [comment]
I'm sorry but we cannot help you without any further information ...
Can you specify, for exemple, a reproduction scenario ?

**Comment by kennethlimcp** [comment]
What is the original behavior like? I should be able to click on the boxes?

It's not clear what need to be done to setup machine planning. The page looks like it displays a calendar without any feature.

Can you explain what should an admin do in this page? :)

**Comment by sylvainbx** [comment]
First, you should log as an admin, then click on "manage the calendar", in admin's section:
![image](https://cloud.githubusercontent.com/assets/5102799/19186166/3b6329de-8c85-11e6-9b55-def9e3c427b5.png)

Then, you can draw rectangles on the calendar to create "availabilities". Note that these slots must be multiples of 1 hour (you can adjust afterwards, if you select **link a training** in the modal that opens).
![image](https://cloud.githubusercontent.com/assets/5102799/19186213/7e66c222-8c85-11e6-87de-8c8caa4f2ee9.png)

**Comment by sylvainbx** [comment]
Please note too, that the [forum](https://forum.fab-manager.com/) is a best place to ask for help. The bug tracker is reserved for **bug reports**
