### ISSUE TITLE
Dates évènements sur facture

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#53]
Lorsqu'un évènement s'étale sur plusieurs jours la facture ne mentionne que le premier. Ceci alerte les usagers qui pensent ne s'être inscrits que sur une partie de l'évènement. Dans l'exemple joint, l'évènement se déroule les 22 et 23 novembre. [Relais-Sciences-FabLab-facture-806_26102016.pdf](https://github.com/LaCasemate/fab-manager/files/555375/Relais-Sciences-FabLab-facture-806_26102016.pdf)

**Comment by sylvainbx** [comment]
Ceci vient d'être corrigé dans le commit 99cca406d513bc340a4dc2534ffef7368304d93f.
La [release 2.4.2](https://github.com/LaCasemate/fab-manager/releases/tag/v2.4.2) est la première version stable à contenir cette correction.
