### ISSUE TITLE
Export des réservations, variable non valide

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#54]
A partir de l'onglet "gérer les utilisateur" et en faisant un export "réservations" le contenu de la colonne  "Nombre de créneaux (heures/places)", n'est pas le bon. Dans notre cas, toutes les valeurs sont à 1 alors que certaines réservations sur des évènements sont à 2 ou 3 lorsque que l'on consulte les réservations à partir de l'onglet "gérer les évènements".

**Comment by sylvainbx** [comment]
Je confirme : il s'agit d'un bug qui semble uniquement concerner les événements

**Comment by sylvainbx** [comment]
Bug corrigé dans la [version 2.4.3](https://github.com/LaCasemate/fab-manager/releases/tag/v2.4.3).
