### ISSUE TITLE
Incohérence des critères d'exports

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#56]
Dans l'onglet statistiques, les dates de référence qui bordent les résultats d'exports sont celles des inscriptions et non celles des évènements, formations, heures machines, ... 

Ceci est incohérent par rapport aux résultats attendus. La date d'inscription est une donnée importante mais pas en critère de tri. Je suggère vivement de relier la question des dates à la donnée "date évènement, date formation, etc".

**Comment by sylvainbx** [comment]
Le suivi de cette demande de nouvelle fonctionnalité s'effectue désormais sur [le site dédié à la roadmap de Fab-Manager](https://roadmap.fab-manager.com/posts/47/open-format-for-project-exchange).
