### ISSUE TITLE
Docker README missing a step

### ISSUE THREAD

**Issue by Plou** [sleede/fab-manager#58]
Hi,

While first setting up nginx configuration file, it is needed to comment out the ssl part.
(https://github.com/LaCasemate/fab-manager/tree/master/docker#setup-folders-and-env-file)

You mention it on the last step : 
> If the certificate was successfully generated then update the nginx configuration file and activate the ssl port and certificate
(https://github.com/LaCasemate/fab-manager/tree/master/docker#generate-ssl-certificate-by-letsencrypt-app-must-be-run-before-start-letsencrypt)

To ease the process it could be nice that the example file[nginx_with_ssl.conf.example](https://github.com/LaCasemate/fab-manager/blob/master/docker/nginx_with_ssl.conf.example)  has the SSL parts commented so the newcomers don't feel lost as nginx crashes.

I could try to do a PR with an updated conf file and README if needed, as I'm part of the newcomers  I don't feel that confident to do so.

Thanks anyway for the docker installation procedure, it works great and feel really easy I learned a great deal about docker and let's encrypt while setting it up.

Cheers,
Plou

**Comment by sylvainbx** [comment]
This makes sense to me.
 @jarod022 , maybe you can give your opinion about this.

**Comment by jarod022** [comment]
Yes I totally agree

The best would be to use a first template without ssl, then a second template with ssl.
The objective is to have a first configuration on port 80 in order to allow the validation and the generation of the first certificate.
Once ok, switch to 443 with ssl directives.

**Comment by raqqun** [comment]
I installed fab-manager today for one of our internal teams at simplon.co and i was stubbed upon the same incoherence on the docker readme. So i requested a PR here https://github.com/LaCasemate/fab-manager/pull/92

**Comment by sylvainbx** [comment]
This should be fixed with [release 2.6.1](https://github.com/LaCasemate/fab-manager/releases/tag/v2.6.1). Feel free to re-open if you encounter the same problem again.
