### ISSUE TITLE
vue Calendrier - navigation mois/mois

### ISSUE THREAD

**Issue by phd0** [sleede/fab-manager#59]
Sur la vue Calendrier, et en affichage mois la navigation : 
  * le bouton < fait reculer de 6 mois au lieu de un
  * le bouton > ne fait rien (régénération du calendrier au même mois)

**Comment by sylvainbx** [comment]
Corrigé dans la [version 2.5.0](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.0)
