### ISSUE TITLE
site web

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#6]
ne serait il pas interessant de mettre en démo 
1/ la version "libre" (celle actuellement dispo), pour ce rendre compte des fonctionalités de base et dire que cest la version libre, de base.
2/ mettre en démo la version "complete" (car cest celle la qui interesse plus les fabmanageur) pour pouvoir se faire une idée des differences entre les versions, et "vendre" plus facilement cette version. (inciter plus facilement les gens a basculer sur cette version)

**Comment by jarod022** [comment]
Merci pour votre suggestion.
Nous allons prochainement communiquer sur les offres concernant la version Premium.
Nous en profiterons pour mettre en ligne une démo de cette dernière.
