### ISSUE TITLE
Bug Formulaire d'inscription

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#60]
Sous "Ubuntu" avec le navigateur "Chromium" le menu déroulant "Votre profil utilisateur" ne propose aucun choix et la case à cocher "J'ai lu et j'accepte la charte d'utilisation du Fab Lab" est inexistante.
donc pas de bouton "Valider" actif.

**Comment by sylvainbx** [comment]
Si j'ai bien compris, ceci se produit dans la boite de dialogue de création de compte. Pouvez-vous me le confirmer ?
Quelle est la version d'Ubuntu et de Chromium ?

Une capture d'écran serait éventuellement bienvenue car je n'arrive pas à reproduire le problème ...

**Comment by modulaire** [comment]
Après enquête, voici la réponse :

OS : Ubuntu v. 16.04
Navigateur : Firefox (et pas chromium) dernière version.

Nb. Merci de modifier mon adresse mail. L’ancienne ne sera bientôt plus opérationnelle (cf. ci-dessous).

Cordialement.
Matthieu DEBAR
FabLab Manager

ATTENTION JE CHANGE D’ADRESSE MAIL.
Mon nouveau mail : mdebar@ledome.info

Relais d’sciences
Le Dôme
Esplanade Stéphane Hessel
14000 Caen
Tél. : 02 31 06 60 55
Web : www.relais-sciences.org <http://www.relais-sciences.org/>
 

 <http://relais-sciences.org/index.php?page=liste_actus_mri>
 <http://relais-sciences.org/index.php?page=liste_actus_mri>

**Comment by sylvainbx** [comment]
Je n'arrive toujours pas à reproduire avec la configuration indiquée ...

![image](https://cloud.githubusercontent.com/assets/5102799/21859431/e15b31c2-d82c-11e6-97ce-bef78ba87e54.png)

Concernant votre adresse email, je vous suggère plutôt de mettre à jour votre profil GitHub car c'est de là que partent les emails.

Cordialement

**Comment by modulaire** [comment]
Ok Sylvain. Merci. Le bug était peut-être lié à un add-ons ou un pilote obsolète sur le pc concerné

Cordialement.
Matthieu DEBAR
FabLab Manager

ATTENTION JE CHANGE D’ADRESSE MAIL.
Mon nouveau mail : mdebar@ledome.info

Relais d’sciences
Le Dôme
Esplanade Stéphane Hessel
14000 Caen
Tél. : 02 31 06 60 55
Web : www.relais-sciences.org <http://www.relais-sciences.org/>
 

 <http://relais-sciences.org/index.php?page=liste_actus_mri>
 <http://relais-sciences.org/index.php?page=liste_actus_mri>
