### ISSUE TITLE
Suppression Événements

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#61]
Bonjour,
Souhaitant supprimer un tarif préférentiel sur un évènement je me suis aperçu que cette fonctionnalité n'était pas disponible (alors que l'évènement n'enregistre aucun inscrit). J'ai donc créé une deuxième fiche pour le même évènement. Et la impossible de supprimer l'événement initial...

**Comment by sylvainbx** [comment]
Deux choses à faire :
- `DELETE /api/events/:id` renvoie une erreur 500
- Ajouter la possibilité de supprimer un tarif supplémentaire sur un événement (si aucune réservation pour cette combinaison)

**Comment by sylvainbx** [comment]
Corrigé dans la [version 2.5.0](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.0)
