### ISSUE TITLE
Facturation pour une structure

### ISSUE THREAD

**Issue by simonmacias** [sleede/fab-manager#64]
Lorsqu'une structure prend un abonnement, l'objet de la facture éditée est au nom de la personne qui s'est inscrite, et non pas au nom de sa structure... ce qui peut poser des soucis de compta ! 

Exemple : Abonnement de Michel Dupont pour un an à compter du 14/03/2017

Alors qu'il faudrait plutôt : Abonnement de AZERTY (Michel Dupont) pour un an à compter du 14/03/2017

**Comment by jarod022** [comment]
Bonjour Simon,

L'entête de la facture utilise bien le nom de la structure.
Et jusqu'à présent, cela n'a pas posé de problème d'un point de vue comptable de ne pas avoir également le nom de la structure dans l'objet de la facture.
Ceci dit, si c'est un vrai problème de votre côté, je fais remonter la demande pour modification.

**Comment by sylvainbx** [comment]
La [release 2.5.6](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.6) fournit désormais cette fonctionnalité.
