### ISSUE TITLE
Image size management (responsive)

### ISSUE THREAD

**Issue by Plou** [sleede/fab-manager#66]
Hello,

On small screens the projects images are cropped on the right side, they don't scale as the window do. A quick and efficient fix would be to limit the width of all images. (ex: https://avlab-manager.com/#!/projects/flipper-virtuel)

```scss
img {
  max-width: 100%;
  height: auto;
}
```
I did a small test and it didn't seems to break anything, is there any caveat I don't know about which would prevent us to do that ?

The only one I can think of is in some (rare) cases ie8 would not display an image (null width).

**Comment by jarod022** [comment]
Hello,

In fact, it is only external images that are not responsive.
I just fixed this here https://github.com/LaCasemate/fab-manager/commit/d1a1b63db57adff98726b9b3a6dc4a601df4235b
This fix will be available in the next release

**Comment by sylvainbx** [comment]
Fixed in [release 2.5.3](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.3)
