### ISSUE TITLE
Problème de devises sur les factures PDF

### ISSUE THREAD

**Issue by matbgn** [sleede/fab-manager#67]
- Sur les factures PDF la devise ne suit pas le paramètrage exemple CHF. En effet contrairement à ce qui est visualisé dans les paramètres de facturation, la facture sors en Euros.
- Il suffit d'installer une autre devise (ici CHF) et sortir le PDF d'ue transaction pour reproduire le bug.
- Version utilisée : 2.5.1

![2017-04-26_21h43_06](https://cloud.githubusercontent.com/assets/13169819/25453475/5f491a06-2ac9-11e7-8146-8c6a2bb14f9c.png)

**Comment by sylvainbx** [comment]
Salut,

le paramétrage de la devise pour l'affichage dans l'application (1) et pour la génération de factures (2) dépend de deux paramètres distincts :
- (1) `ANGULAR_LOCALE` pour l'affichage dans l'application web 
- (2) `RAILS_LOCALE` pour la génération de facture PDF 


La devise affichée dans les factures (2) est lue dans le fichier `config/locales/rails.XX.yml` où `XX`correspond à la valeur configurée dans `RAILS_LOCALE`. Si ta valeur est `fr` et que tu as utilisé le fichier par défaut, normal que tu obtiennes des €. Je t'invites à vérifier le contenu de ce fichier sur ton instance, à la clef `XX.number.currency.format.unit`.

Note qu'il existe un fichier pré-configuré pour la suisse que tu peux récupérer [à cette adresse](https://github.com/svenfuchs/rails-i18n/blob/rails-4-x/rails/locale/fr-CH.yml), tu n'as ensuite plus qu'à le déposer dans `config/locales/rails.fr-CH.yml` et à configurer `RAILS_LOCALE = fr-CH`.

Outre la devise, il apporte quelques autres différences de localisation, par exemple :
![image](https://cloud.githubusercontent.com/assets/5102799/25476998/4cd3fb16-2b3c-11e7-82d2-0a8fdb376752.png)


N'hésite pas à faire un retour après toutes ces vérifications.

**Comment by matbgn** [comment]
Je ne sais pour quelle raison je n'arrive plus à redémarrer mon instance. Après avoir entrer les commandes suivantes : 

1°
```
docker rm -f fabmanager
```

2°
Modification des variables d'environnement

3°
```
docker run --rm \
           --link=fabmanager-postgres:postgres \
           --link=fabmanager-redis:redis \
           --link=fabmanager-elastic:elasticsearch \
           -e RAILS_ENV=production \
           --env-file /home/core/fabmanager/config/env \
           -v /home/core/fabmanager/plugins:/usr/src/app/plugins \
           sleede/fab-manager \
           bundle exec rake db:migrate
```

4°
```
rm -Rf public/assets
``` 

5° 
```
docker run --rm \
             --link=fabmanager-postgres:postgres \
             --link=fabmanager-redis:redis \
             --link=fabmanager-elastic:elasticsearch \
             -e RAILS_ENV=production \
             --env-file /home/core/fabmanager/config/env \
             -v /home/core/fabmanager/public/assets:/usr/src/app/public/assets \
             -v /home/core/fabmanager/plugins:/usr/src/app/plugins \
             sleede/fab-manager \
             bundle exec rake assets:precompile
```

6°
```
docker run --restart=always -d --name=fabmanager \
             -p 3000:3000 \
             --link=fabmanager-postgres:postgres \
             --link=fabmanager-redis:redis \
             --link=fabmanager-elastic:elasticsearch \
             -e RAILS_ENV=production \
             -e RACK_ENV=production \
             --env-file /home/core/fabmanager/config/env \
             -v /home/core/fabmanager/public/assets:/usr/src/app/public/assets \
             -v /home/core/fabmanager/public/uploads:/usr/src/app/public/uploads \
             -v /home/core/fabmanager/invoices:/usr/src/app/invoices \
             -v /home/core/fabmanager/exports:/usr/src/app/exports \
             -v /home/core/fabmanager/plugins:/usr/src/app/plugins \
             -v /home/core/fabmanager/log:/var/log/supervisor \
             sleede/fab-manager
```

Je n'accède pas container dans les logs j'obtiens :

2017-04-27 11:02:03,289 INFO exited: app (exit status 1; not expected)
2017-04-27 11:02:04,293 INFO spawned: 'app' with pid 3377
2017-04-27 11:02:05,300 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-27 11:02:10,252 INFO exited: worker (exit status 1; not expected)
2017-04-27 11:02:11,258 INFO spawned: 'worker' with pid 3382
2017-04-27 11:02:12,262 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Dans tous les cas je ferme ce ticket, mais je veux bien votre assistance sur ce bug.

**Comment by sylvainbx** [comment]
Alors après en avoir discuté, il apparaît qu'avec docker, les choses ne sont pas si simple car la configuration va disparaître à chaque redémarrage du container, à moins de construire ta propre image.

Je ne sais pas si ton problème est lié à ça, mais du coup je viens de produire une nouvelle release de fab-manager ([release 2.5.3](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.3)) qui inclus directement tous les fichiers de localisation rails. Cela te permet de configurer la locale dans les variables d'environnement sans te soucier de la présence et de la validité du fichier.

Si tu peux essayer avec cette nouvelle version et me dire si ça résout ton problème ...

PS: L'image docker est en cours de construction ([voir ici](https://hub.docker.com/r/sleede/fab-manager/builds/)), tu vas devoir attendre quelques minutes avant de pouvoir tester.

**Comment by matbgn** [comment]
EXCELLENT !!! Merci infiniment mon instance est à nouveau Up! Par contre j'ai toujours mon bug en Euros. Une idée ?

**Comment by sylvainbx** [comment]
Tu as bien configuré `RAILS_LOCALE` sur `fr-CH` ?

Pour être sûr que ta configuration a bien été prise en compte, tu peux lancer les commandes suivantes :
```bash
docker exec -it fabmanager_fabmanager_1 bash
bundle
rails c
I18n.locale
```

**Comment by matbgn** [comment]
Oui tout bien :
```
Loading production environment (Rails 4.2.5)
irb(main):001:0> I18n.locale
=> :"fr-CH"
irb(main):002:0>
```

**Comment by sylvainbx** [comment]
Bon, je suis en train de faire des tests et je crois que c'est un peu plus compliqué que ce que j'avais imaginé initialement. Je te tiens au courant.

**Comment by sylvainbx** [comment]
Je viens de faire un commit sur la branche `dev` qui devrait, j'espère, résoudre ton problème.

Est-ce que tu pourrais tester d'utiliser l'image docker de dev en utilisant `sleede/fab-manager:dev` dans tes commandes docker et me dire si ça résout ton problème avant que je fasses une nouvelle release ?

Avant de lancer l'application il faut juste que tu rajoutes la variable d'environnement `APP_LOCALE=fr` dans ton fichier `env`. Penses aussi à recompiler les assets.

Tiens moi au courant.

**Comment by matbgn** [comment]
Malheureusement rien y fait... :_(

Le PDF sort toujours en €

Après avoir répété la séquence décrite plus et en ayant ajouté la variable APP_LOCALE au point 2.

**Comment by sylvainbx** [comment]
Ok est-ce que tu peux lancer les commandes suivantes et reporter ici les résultats :

#### 1. Lancer la console rails
 ```bash
docker exec -it fabmanager_fabmanager_1 bash
bundle
rails c
```

#### 2. Unité monétaire (rails)
```ruby
I18n.t 'number.currency.format.unit'
```

#### 3. Conversion d'un montant en devises
```ruby
include ActionView::Helpers::NumberHelper
number_to_currency(12)
```

Merci.

**Comment by matbgn** [comment]
Petit up, et pour info il semblerait que les nouvelles factures soient OK pour du CHF (sFR). Comment écraser les précédentes (au minimum pour les membres qui font la demande explicite d'avoir leur preuve de paiement en CHDF) ?

**Comment by matbgn** [comment]
Je fais ça tout de suite

**Comment by sylvainbx** [comment]
Ah mais ... attend ! Quand tu me dis que la devise ne change pas ... tu veux parler des factures déjà générées, pas des nouvelles ?

**Comment by matbgn** [comment]
Tout à fait, quand j'appuie sur télécharger pour les factures établies jusqu'ici elles sont en Euros. Par contre, comme dit, les nouvelles sont ok depuis la dernière image docker en dev je dirais.

**Comment by sylvainbx** [comment]
Haa ... mais il fallait le dire, car ça change tout :-)

En effet, le changement de locale ne déclenche pas la régénération de toutes les factures (et heureusement !), donc celles qui ont été générés précédemment restent tels quels (c'est un principe de compta il me semble).

Par contre tu peux forcer la régénération manuellement si tu le souhaites. Pour ça :
```bash
docker exec -it fabmanager_fabmanager_1 bash
bundle
rake fablab:regenerate_invoices[year,month]
# par exemple rake fablab:regenerate_invoices[2017,1] va régénéré toutes les factures de janvier 2017 (et seulement celles-là).
```

**Comment by matbgn** [comment]
A fonctionné comme sur des roulettes ! Merci beaucoup.

**Comment by sylvainbx** [comment]
Je ré-ouvre l'issue pour mémo. Elle sera clôturée quand la correction sera intégrée dans la prochaine release stable (probablement 2.5.4)

**Comment by matbgn** [comment]
Ok, du coup je profite, Est-ce qu'il est possible de créer une facture de toute pièce en CLI ?

**Comment by sylvainbx** [comment]
Non ce n'est pas possible pour le moment (enfin pas de manière simple). Quel est ton besoin ?

**Comment by matbgn** [comment]
J'aurais besoin des pouvoir faire une simple vente matière (e.g. vente de MDF, plexi, etc.). Et surtout faire une facture manuelle pour les heures des visiteurs de passage. Une idée ?

**Comment by sylvainbx** [comment]
Je t'ai répondu en partie [sur le forum](https://forum.fab-manager.com/t/mode-de-paiement/41/4). 

Concernant les ventes de matières, ce n'est pas malheureusement pas possible pour le moment, même en essayant d'outrepasser l'interface, en la créant directement en ligne de commande, ... tu seras bloqué par des bugs, notamment à la génération du pdf car le pour le moment une facture doit nécessairement être associée soit à une réservation soit à un abonnement, soit à des jours d'abonnement offerts. Sans compter que je n'ai pas tout vérifié mais il est également possible qu'il y ai des problèmes lors de la génération des statistiques, entre autres ...

Tout ça pour dire que quelques développements sont nécessaires pour pouvoir gérer ce cas, donc ce n'est pas possible dans l'état actuel du projet.

**Comment by matbgn** [comment]
Ok merci beaucoup pour toutes ces réponses. Vous faites un job juste incroyable et si je peux ne serait-ce que scripter une partie ce sera avec plaisir. Sinon il y a également ce projet open source fait par un ami ici en Suisse qui peut être intéressante à étudier : https://github.com/gaetancollaud/fablab-manager

Au plaisir de vous aider.

**Comment by sylvainbx** [comment]
Corrigé dans la [release 2.5.4](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.4).

@matbgn dans 10 minutes, tu pourras reconfigurer ton image docker pour pointer vers `sleede/fab-manager`

**Comment by matbgn** [comment]
Merci @sylvainbx ! Top 👍 Tu as vu ma question sur le [forum](https://forum.fab-manager.com/t/mode-de-paiement/41/4)? 

En résumé, est-ce qu'il serait possible de permettre aux admins de créer des réservations à des dates antérieurs à celle du jour ? Cela permettrait de résoudre un certain nombre de cas pour la facturation des visiteurs de passage seulement (création de la facture à posteriori).
