### ISSUE TITLE
login et mot de passe admin par defaut

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#7]
Bonjour, 

il y a une erreur dans le fichier de creation de la base (le seeds comme vous l'appellez), 
le login de base est une faute de frappe : 
admin@fabmanager.com au lieu de fab-manager.com

afin de faciliter la prise en main, 
le login : admin
et 
le mot de passe : adminadmin
serait plus approprié pour un usage standard, ne neccessitant pas un acces au mail "admin@fab-manager.com" et ainsi eviter de recevoir des demandes d'oubli de mot de passe de la version de démo.

**Comment by jarod022** [comment]
Nous allons documenter cette partie pour inviter le sys admin a bien modifier et customiser le fichier de seed avant installation de l'application en environnement de production.

Cependant, le système repose sur un login par email. Il n'est pas prévu à ce jour d'en changer.
Nous pourrons éventuellement rajouté le support du login par username, mais cela ne change pas la nécessité d'avoir une adresse email par compte utilisateur.

**Comment by lespacedunmatin** [comment]
Au FacLab, j’avais reçu quelques personnes qui n’avaient pas d’adresse email.
