### ISSUE TITLE
[Docker] After update, nothing is translated

### ISSUE THREAD

**Issue by Booteille** [sleede/fab-manager#70]
I just updated the docker image and now nothing is translated.

Here is an example of what looks login/subscribe buttons: 
![example](https://cloud.githubusercontent.com/assets/2203721/26724775/7591eab0-479b-11e7-92e5-ca7725c7ae56.png)

**Comment by alexcvcoelho** [comment]
Hi @Booteille 
Can you give more information? What's language you use?

**Comment by sylvainbx** [comment]
have you followed the instructions shown on [this page](https://github.com/LaCasemate/fab-manager/releases), marked by `[TODO DEPLOY]`, for each intermediate version from the one you-ve upgraded ?

**Comment by Booteille** [comment]
Hey. I didn't followed instructions and now I did everything run smooth. Thanks and sorry! I was not sure about what did mean the "TODO Deploy" (even if now it seems obvious) and forgot about afterthought.

**Comment by sylvainbx** [comment]
You're welcome :)
