### ISSUE TITLE
json gem is missing

### ISSUE THREAD

**Issue by emj365** [sleede/fab-manager#73]
After bundle still got `json` missing.
Fixed after adding `gem 'json', '~> 1.8'` to Gemfile.

**Comment by sylvainbx** [comment]
I'm sorry but I cannot reproduce this issue. Please, can you specify which version you're using (v2.x.x / dev / master) AND which method (docker / docker-compose / from sources)?

**Comment by sylvainbx** [comment]
Closing this as it isn't reproductible yet, and the needed infos were not provided. Feel free to re-open it, providing more infos.
