### ISSUE TITLE
use command line ENV instead of ENV in secret for db:seed

### ISSUE THREAD

**Issue by emj365** [sleede/fab-manager#74]
Are `ADMIN_EMAIL`, `ADMIN_PASSWORD` only for `db:seed`?

Suggestion just write readme like 
```
ADMIN_EMAIL=user@gmail.com ADMIN_PASSWORD=passwd bin/rake db:seed RAILS_ENV=development
```

to run `db:seed`.

**Comment by sylvainbx** [comment]
This makes sense to me, I will confirm this with the team, and update the documentation as suggested if this is confirmed.

**Comment by sylvainbx** [comment]
This was changed in [2.5.10](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.10)
