### ISSUE TITLE
How to get fabmanager's nginx working with root nginx?

### ISSUE THREAD

**Issue by Booteille** [sleede/fab-manager#76]
Hi.

I've installed Fabmanager through docker and a wordpress showcase website without it.
I would like to know if there is a way to get fabmanager on a subdomain (fabmanager.domain.com) and my showcase website on the main domain (domain.com).

Actually, domain.com is redirecting to the fabmanager instead of the showcase website.

Has someone clues about how to solve it?

Thanks.

**Comment by sylvainbx** [comment]
Hi @Booteille,
This issue tracker is **reserved** for bug reports and feature requests.
The good place to ask a question or call for help is at [Fab-manager forums](https://forum.fab-manager.com/). 
Thanks
