### ISSUE TITLE
Soucis avec changement d'heure (décalage)

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#77]
Lorsque l'on fait une récurrence et que l'on passe en heure d'hiver, le créneau horaire se décale d'une heure (cela se produit à partir du 28 octobre 2017) ...

**Comment by sylvainbx** [comment]
Bonjour,
Effectivement, je constate moi aussi un bug à ce niveau. Je vais essayer de le corriger pour la prochaine version. Merci de l'avoir remonté.

**Comment by sylvainbx** [comment]
Corrigé dans la [release 2.5.11](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.11)
