### ISSUE TITLE
Soucis lors de la suppression d'un creneau de réservation d'espace

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#78]
Lorsqu'un espace a eu une réservation puis lorsque cette dernière est annulée, il est impossible de supprimer le créneau de réservation.

 "Le créneau 2 octobre 2017 10:00 - 12:00 n'a pu être supprimé car il est déjà réservé par un membre" apparaît alors qu'il n'y a aucune réservation sur ce créneau

**Comment by sylvainbx** [comment]
Oui, c'est normal. Une réservation annulée ne vaut pas suppression, on en garde une trace dans le système pour l'historique. Ainsi, pour des raisons de cohérence des données, il est impossible de supprimer le créneau associé.

**Comment by julienrat** [comment]
Je comprends bien, mais là je suis bloqué, il n'y a vraiment pas de moyen de refaire ce créneau car il affecte une semaine d'activités. 
Via Postgresql ?
Ajouter une fonction "afficher l'historique ou  pas ?"

**Comment by sylvainbx** [comment]
C'est une demande qu'on a déjà eu. On pensais rajouter une fonctionnalité permettant de masquer un créneau dans l'agenda publique mais ce n'est malheureusement pas possible pour nous de réaliser cela rapidement.
Quand avez vous besoin de cela ?

**Comment by julienrat** [comment]
Si c'est possible c'est super ! +1: 
Concernant le besoin de cette option,  j'ai envie de vous répondre dès que possible ! 
Merci encore pour la réactivité !

**Comment by sylvainbx** [comment]
Fonctionnalité ajoutée dans la [release 2.5.11](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.11)
