### ISSUE TITLE
Etat du projet ?

### ISSUE THREAD

**Issue by david-guenault** [sleede/fab-manager#8]
Bonjour, quel est l'état d'activité du projet à l'heure actuelle ? En veille, abandonné, actif ? Cela fait 5 mois qu'il n'y a pas eu de commit sur le dépôt. On peut donc légitimement se poser la question. On aurait bien envie de contribuer, mais si le projet est mort ....

**Comment by lespacedunmatin** [comment]
Mais si tu contribue, le projet n’est plus mort, non ?

**Comment by pmoutet** [comment]
Bonjour @david-guenault . Non le projet n'est pas mort. C'est vrai qu'il n'y a pas eu de commit depuis un certain temps mais nous prévoyons toujours d'alimenter le dépôt dans les temps qui viennent mais je ne peux pas donner de dates exactes pour le moment. Quelques Fab Lab ont installé la version et nous avons déjà amélioré quelques éléments concernant la doc de l'install notamment. Comme dit @lespacedunmatin , c'est encore plus intéressant si d'autres personnes contribuent :)

**Comment by david-guenault** [comment]
Ok, c'est une bonne nouvelle. Afin de faciliter les évaluations j'ai créé (rapidement) un conteneur docker.
Y a t'il un intérêt à faire un PR pour cela dans le sens ou cela faciliterait la mise en place qui est tout sauf triviale ? (@lespacedunmatin : tu vois une nouvelle contrib :-))

**Comment by jarod022** [comment]
Bonjour,

@david-guenault , ce serait parfait ! 
Il est évident que cela facilitera grandement les tests de la version Opensource.
D'autant que nous avions ce besoin dans notre roadmap.
Merci.

**Comment by pmoutet** [comment]
Excellent @david-guenault :)

**Comment by david-guenault** [comment]
Ok je prépare un pr. Le premier sera un peu léger. Pour la suite et avec
votre aide j'integrerai plus de possibilités.
