### ISSUE TITLE
Triage dans le sens chronologique des évenements

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#80]
Bonjour,
Nous venons de remplir les événements de notre fablab pour le premier semestre, mais ceux ci apparaissent de façon anti chronologique [https://fablab.lesusinesnouvelles.com/#!/events] est il possible de modifier l'ordre d'affichage de ceux-ci ?

cela ne se produit qu'en mode administrateur

**Comment by sylvainbx** [comment]
Salut,
En fait, lorsque tu es connecté en admin tu vois les événements dans l'ordre anti-chronologique (le plus lointain en premier), mais lorsque tu n'es pas connecté (ou connecté comme simple utilisateur), les événements apparaissent dans l'ordre chronologique normal et les événements passés sont alors masqués. 
C'était dans les spécifications initiales du projet même si cela perturbe pas mal de monde :-)

**Comment by julienrat** [comment]
OK je viens de m'en apercevoir !
