### ISSUE TITLE
realease 2.5.11 rake db:seed  - No Rakefile found 

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#81]
Bonjour une petite erreur est apparue lors de la mise a jour de la 2.5.11 quand nous faisons les lignes de commande TO DO DEPLOY 

/home/core/fabmanager# rake db:seed 
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
root@vps309910:/home/core/fabmanager# rake fablab:fix:migrate_admins_group
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
root@vps309910:/home/core/fabmanager# rake fablab:fix:recursive_events_over_DST
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

**Comment by sylvainbx** [comment]
Utilisez-vous docker ?

**Comment by julienrat** [comment]
je suis le tuto de mise à jour https://forum.fab-manager.com/t/tuto-mettre-a-jour-fab-manager/152

**Comment by sylvainbx** [comment]
Essayez de préfixer vos commandes par `docker-compose run --rm fabmanager bundle exec`

**Comment by julienrat** [comment]
par exemple ?

`docker-compose run --rm fabmanager bundle exec rake db:seed`

>

**Comment by sylvainbx** [comment]
Exactement

**Comment by julienrat** [comment]
ça fonctionne, mais avec la dernière version tous les événements (formations, espaces etc) du calendrier ont disparus :D

**Comment by jarod022** [comment]
Hello,

Je n'arrive pas à reproduire.
Peux tu préciser le pb ? 
C'est bien sur la vue calendrier /calendar ? 
Tu es connecté en tant que user ? admin ? non connecté ?

**Comment by julienrat** [comment]
voici la sortie de la dernière commande docker-compose` run --rm fabmanager bundle exec rake fablab:fix:recursive_events_over_DST`


Event Load (0.5ms)  SELECT  "events".* FROM "events" WHERE "events"."id" = $1 LIMIT 1  [["id", nil]]
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find Event with 'id'=
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/core.rb:155:in `find'
/usr/src/app/lib/tasks/fablab/fix.rake:65:in `block (4 levels) in <top (required)>'
/usr/src/app/lib/tasks/fablab/fix.rake:64:in `each'
/usr/src/app/lib/tasks/fablab/fix.rake:64:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => fablab:fix:recursive_events_over_DST
(See full trace by running task with --trace)

**Comment by julienrat** [comment]
Bonjour,
Nous avons ré essayé la mise a jour de fabmanager vers la version 2.5.11, le probleme est toujours le même : 
- Aucun Événement, Formation, Espace n'apparait dans notre calendrier
- Les Evenements, Formations, Espaces existent bien et sont exportables
- Lors de la création d'un nouvel événement, celui- ci n'apparait pas non plus dans le calendrier.

Lorsque nous créons un créneau espace ou machine, la validation est inactive.

**Comment by sylvainbx** [comment]
Bonjour @julienrat ,
Concernant le problème que tu vois lors de l'exécution de la commande `fablab:fix:recursive_events_over_DST`, je viens de faire un correctif ce matin sur la branche dev. 
Mais ton autre problème est très bizarre, je ne le reproduit pas du tout. Pourrais-tu nous dire, lorsque cela se produit, ce qui est affiché dans la console du navigateur (Ctrl+Maj+i pour l'afficher) ?

**Comment by julienrat** [comment]
application-ac1a39f….js:199 POST https://fablab.lesusinesnouvelles.com/users/sign_in.json 401 (Unauthorized)
(anonymous) @ application-ac1a39f….js:199
sendReq @ application-ac1a39f….js:199
serverRequest @ application-ac1a39f….js:199
processQueue @ application-ac1a39f….js:200
(anonymous) @ application-ac1a39f….js:200
$eval @ application-ac1a39f….js:200
$digest @ application-ac1a39f….js:200
$apply @ application-ac1a39f….js:200
(anonymous) @ application-ac1a39f….js:200
completeOutstandingRequest @ application-ac1a39f….js:197
(anonymous) @ application-ac1a39f….js:197
application-ac1a39f….js:32 GET https://fablab.lesusinesnouvelles.com/api/availabilities/public?t%5B%5D=10&…ue&start=2017-09-11&end=2017-09-18&timezone=Europe%2FParis&_=1505116600491 500 (Internal Server Error)
send @ application-ac1a39f….js:32
ajax @ application-ac1a39f….js:32
_fetchEventSource @ application-ac1a39f….js:235
fetchEventSource @ application-ac1a39f….js:235
fetchEvents @ application-ac1a39f….js:235
fetchAndRenderEvents @ application-ac1a39f….js:235
getAndRenderEvents @ application-ac1a39f….js:235
renderView @ application-ac1a39f….js:235
initialRender @ application-ac1a39f….js:235
render @ application-ac1a39f….js:235
(anonymous) @ application-ac1a39f….js:236
each @ application-ac1a39f….js:19
each @ application-ac1a39f….js:19
$.fn.fullCalendar @ application-ac1a39f….js:236
scope.init @ application-ac1a39f….js:230
(anonymous) @ application-ac1a39f….js:230
$digest @ application-ac1a39f….js:200
$apply @ application-ac1a39f….js:200
done @ application-ac1a39f….js:199
completeRequest @ application-ac1a39f….js:199
xhr.onload @ application-ac1a39f….js:199
application-ac1a39f….js:32 GET https://fablab.lesusinesnouvelles.com/api/availabilities/public?t%5B%5D=10&…ue&start=2017-09-11&end=2017-09-18&timezone=Europe%2FParis&_=1505116600492 500 (Internal Server Error)
send @ application-ac1a39f….js:32
ajax @ application-ac1a39f….js:32
_fetchEventSource @ application-ac1a39f….js:235
fetchEventSource @ application-ac1a39f….js:235
fetchEvents @ application-ac1a39f….js:235
fetchAndRenderEvents @ application-ac1a39f….js:235
getAndRenderEvents @ application-ac1a39f….js:235
renderView @ application-ac1a39f….js:235
initialRender @ application-ac1a39f….js:235
render @ application-ac1a39f….js:235
(anonymous) @ application-ac1a39f….js:236
each @ application-ac1a39f….js:19
each @ application-ac1a39f….js:19
$.fn.fullCalendar @ application-ac1a39f….js:236
scope.init @ application-ac1a39f….js:230
(anonymous) @ application-ac1a39f….js:230
$digest @ application-ac1a39f….js:200
$apply @ application-ac1a39f….js:200
done @ application-ac1a39f….js:199
completeRequest @ application-ac1a39f….js:199
xhr.onload @ application-ac1a39f….js:199
application-ac1a39f….js:199 GET https://fablab.lesusinesnouvelles.com/api/notifications/polling?last_poll=2017-09-11T08:54:48.956Z 401 (Unauthorized)

**Comment by sylvainbx** [comment]
Ok ... peux-tu nous donner le contenu des logs côté serveur, lorsque le problème se produit ?
Utilise `tail -f log/app-stdout.log` dans le dossier de l'application pour afficher les logs en temps réel. Le fichier `app-stderr.log` peut également présenter un intérêt. Merci !

**Comment by julienrat** [comment]
La sortie du `tail -f log/app-stdout.log`

root@vps309910:/home/core/fabmanager# tail -f log/app-stdout.log
  Parameters: {"last_poll"=>"2017-09-11T08:54:48.956Z"}
Completed 401 Unauthorized in 4ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/api/notifications/polling?last_poll=2017-09-11T08:54:48.956Z" for 78.206.32.41 at 2017-09-11 09:39:48 +0000
Processing by API::NotificationsController#polling as JSON
  Parameters: {"last_poll"=>"2017-09-11T08:54:48.956Z"}
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/api/notifications/polling?last_poll=2017-09-11T08:54:48.956Z" for 78.206.32.41 at 2017-09-11 09:40:18 +0000
Processing by API::NotificationsController#polling as JSON
  Parameters: {"last_poll"=>"2017-09-11T08:54:48.956Z"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/" for 78.206.32.41 at 2017-09-11 09:41:04 +0000
Processing by ApplicationController#index as HTML
  Setting Load (0.5ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1  [["name", "fablab_name"]]
  Stylesheet Load (0.9ms)  SELECT  "stylesheets".* FROM "stylesheets"  ORDER BY "stylesheets"."id" ASC LIMIT 1
  CACHE (0.0ms)  SELECT  "stylesheets".* FROM "stylesheets"  ORDER BY "stylesheets"."id" ASC LIMIT 1
  CACHE (0.0ms)  SELECT  "stylesheets".* FROM "stylesheets"  ORDER BY "stylesheets"."id" ASC LIMIT 1
  CustomAsset Load (0.3ms)  SELECT  "custom_assets".* FROM "custom_assets" WHERE "custom_assets"."name" = $1 LIMIT 1  [["name", "favicon-file"]]
  CustomAssetFile Load (0.5ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('CustomAssetFile') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 4], ["viewable_type", "CustomAsset"]]
  CACHE (0.0ms)  SELECT  "custom_assets".* FROM "custom_assets" WHERE "custom_assets"."name" = $1 LIMIT 1  [["name", "favicon-file"]]
  CACHE (0.0ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('CustomAssetFile') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 4], ["viewable_type", "CustomAsset"]]
  CACHE (0.0ms)  SELECT  "custom_assets".* FROM "custom_assets" WHERE "custom_assets"."name" = $1 LIMIT 1  [["name", "favicon-file"]]
  CACHE (0.0ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('CustomAssetFile') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 4], ["viewable_type", "CustomAsset"]]
  Rendered application/index.html.erb (27.2ms)
Completed 200 OK in 30ms (Views: 26.6ms | ActiveRecord: 2.5ms | Elasticsearch: 0.0ms)
Started POST "/users/sign_in.json" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by SessionsController#create as JSON
  Parameters: {"user"=>{}, "session"=>{"user"=>{}}}
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/api/settings/fablab_name" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::SettingsController#show as JSON
  Parameters: {"name"=>"fablab_name"}
  Setting Load (0.5ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1  [["name", "fablab_name"]]
  Rendered api/settings/_setting.json.jbuilder (0.2ms)
  Rendered api/settings/show.json.jbuilder (1.1ms)
Completed 200 OK in 5ms (Views: 2.4ms | ActiveRecord: 0.5ms | Elasticsearch: 0.0ms)
Started GET "/api/settings/name_genre" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Started POST "/users/sign_in.json" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::SettingsController#show as JSON
  Parameters: {"name"=>"name_genre"}
Processing by SessionsController#create as JSON
  Parameters: {"user"=>{}, "session"=>{"user"=>{}}}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
  Setting Load (4.3ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1  [["name", "name_genre"]]
  Rendered api/settings/_setting.json.jbuilder (0.1ms)
  Rendered api/settings/show.json.jbuilder (0.8ms)
Completed 200 OK in 9ms (Views: 1.9ms | ActiveRecord: 4.3ms | Elasticsearch: 0.0ms)
Started GET "/api/custom_assets/logo-file" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::CustomAssetsController#show as JSON
  Parameters: {"id"=>"logo-file"}
Started GET "/api/custom_assets/logo-black-file" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
  CustomAsset Load (0.9ms)  SELECT  "custom_assets".* FROM "custom_assets" WHERE "custom_assets"."name" = $1 LIMIT 1  [["name", "logo-file"]]
Started GET "/api/translations/fr/app.public.common" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::CustomAssetsController#show as JSON
  Parameters: {"id"=>"logo-black-file"}
  CustomAssetFile Load (0.3ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('CustomAssetFile') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 2], ["viewable_type", "CustomAsset"]]
  Rendered api/custom_assets/show.json.jbuilder (2.3ms)
Processing by API::TranslationsController#show as JSON
  Parameters: {"locale"=>"fr", "state"=>"app.public.common"}
Completed 200 OK in 9ms (Views: 4.6ms | ActiveRecord: 1.2ms | Elasticsearch: 0.0ms)
Started GET "/api/translations/fr/app.shared.buttons" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
  CustomAsset Load (4.4ms)  SELECT  "custom_assets".* FROM "custom_assets" WHERE "custom_assets"."name" = $1 LIMIT 1  [["name", "logo-black-file"]]
Completed 200 OK in 4ms (Views: 2.4ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/api/translations/fr/app.shared.elements" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Started GET "/api/settings/booking_window_start" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::TranslationsController#show as JSON
  CustomAssetFile Load (0.7ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('CustomAssetFile') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 3], ["viewable_type", "CustomAsset"]]
Processing by API::TranslationsController#show as JSON
  Parameters: {"locale"=>"fr", "state"=>"app.shared.elements"}
  Parameters: {"locale"=>"fr", "state"=>"app.shared.buttons"}
  Rendered api/custom_assets/show.json.jbuilder (5.9ms)
Processing by API::SettingsController#show as JSON
Completed 200 OK in 7ms (Views: 1.7ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Completed 200 OK in 29ms (Views: 10.5ms | ActiveRecord: 5.1ms | Elasticsearch: 0.0ms)
Completed 200 OK in 7ms (Views: 1.1ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
  Parameters: {"name"=>"booking_window_start"}
Started GET "/api/settings/booking_window_end" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
  Setting Load (1.8ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1  [["name", "booking_window_start"]]
Started GET "/api/trainings" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::SettingsController#show as JSON
  Rendered api/settings/_setting.json.jbuilder (0.1ms)
Processing by API::TrainingsController#index as JSON
  Parameters: {"name"=>"booking_window_end"}
  Rendered api/settings/show.json.jbuilder (1.7ms)
  Training Load (0.7ms)  SELECT "trainings".* FROM "trainings"
Completed 200 OK in 13ms (Views: 7.0ms | ActiveRecord: 1.8ms | Elasticsearch: 0.0ms)
  Setting Load (0.9ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1  [["name", "booking_window_end"]]
  Rendered api/settings/_setting.json.jbuilder (0.1ms)
Started GET "/api/machines" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Started GET "/api/spaces" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Started GET "/api/translations/fr/app.public.calendar" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::MachinesController#index as JSON
  Rendered api/settings/show.json.jbuilder (1.1ms)
  Machine Load (1.5ms)  SELECT "machines".* FROM "machines"
Processing by API::TranslationsController#show as JSON
  Parameters: {"locale"=>"fr", "state"=>"app.public.calendar"}
  Credit Load (10.3ms)  SELECT "credits".* FROM "credits" WHERE "credits"."creditable_type" = 'Training' AND "credits"."creditable_id" IN (10)
Processing by API::SpacesController#index as JSON
Completed 200 OK in 22ms (Views: 5.6ms | ActiveRecord: 0.9ms | Elasticsearch: 0.0ms)
Completed 200 OK in 5ms (Views: 0.3ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
  Space Load (1.3ms)  SELECT "spaces".* FROM "spaces"
  HABTM_Machines Load (3.1ms)  SELECT "trainings_machines".* FROM "trainings_machines" WHERE "trainings_machines"."training_id" IN (10)
  SpaceImage Load (3.1ms)  SELECT "assets".* FROM "assets" WHERE "assets"."type" IN ('SpaceImage') AND "assets"."viewable_type" = 'Space' AND "assets"."viewable_id" IN (2, 4, 5, 6, 7, 8, 9, 1)
  Rendered api/spaces/index.json.jbuilder (12.7ms)
Completed 200 OK in 18ms (Views: 9.1ms | ActiveRecord: 4.4ms | Elasticsearch: 0.0ms)
  MachineImage Load (7.8ms)  SELECT "assets".* FROM "assets" WHERE "assets"."type" IN ('MachineImage') AND "assets"."viewable_type" = 'Machine' AND "assets"."viewable_id" IN (11, 8, 10, 7, 12, 13, 14, 15)
  TrainingImage Load (11.5ms)  SELECT  "assets".* FROM "assets" WHERE "assets"."type" IN ('TrainingImage') AND "assets"."viewable_id" = $1 AND "assets"."viewable_type" = $2 LIMIT 1  [["viewable_id", 10], ["viewable_type", "Training"]]
  Rendered api/trainings/index.json.jbuilder (46.0ms)
  Credit Load (2.0ms)  SELECT "credits".* FROM "credits" WHERE "credits"."creditable_type" = 'Machine' AND "credits"."creditable_id" IN (11, 8, 10, 7, 12, 13, 14, 15)
Completed 200 OK in 48ms (Views: 21.1ms | ActiveRecord: 25.7ms | Elasticsearch: 0.0ms)
  Rendered api/machines/index.json.jbuilder (41.2ms)
Completed 200 OK in 45ms (Views: 32.2ms | ActiveRecord: 11.3ms | Elasticsearch: 0.0ms)
Started GET "/api/availabilities/public?t%5B%5D=10&m%5B%5D=11&m%5B%5D=8&m%5B%5D=10&m%5B%5D=7&m%5B%5D=12&m%5B%5D=13&m%5B%5D=14&m%5B%5D=15&s%5B%5D=2&s%5B%5D=4&s%5B%5D=5&s%5B%5D=6&s%5B%5D=7&s%5B%5D=8&s%5B%5D=9&s%5B%5D=1&evt=true&dispo=true&start=2017-09-11&end=2017-09-18&timezone=Europe%2FParis&_=1505122865319" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::AvailabilitiesController#public as JSON
  Parameters: {"t"=>["10"], "m"=>["11", "8", "10", "7", "12", "13", "14", "15"], "s"=>["2", "4", "5", "6", "7", "8", "9", "1"], "evt"=>"true", "dispo"=>"true", "start"=>"2017-09-11", "end"=>"2017-09-18", "timezone"=>"Europe/Paris", "_"=>"1505122865319"}
  Availability Load (2.3ms)  SELECT "availabilities".* FROM "availabilities" WHERE (start_at >= '2017-09-10 22:00:00.000000' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabilities"."lock" = 'f'
Completed 500 Internal Server Error in 6ms (ActiveRecord: 2.3ms | Elasticsearch: 0.0ms)

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column availabilities.lock does not exist
LINE 1: ...' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabil...
                                                             ^
: SELECT "availabilities".* FROM "availabilities" WHERE (start_at >= '2017-09-10 22:00:00.000000' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabilities"."lock" = 'f'):
  app/controllers/api/availabilities_controller.rb:91:in `public'


Started GET "/api/availabilities/public?t%5B%5D=10&m%5B%5D=11&m%5B%5D=8&m%5B%5D=10&m%5B%5D=7&m%5B%5D=12&m%5B%5D=13&m%5B%5D=14&m%5B%5D=15&s%5B%5D=2&s%5B%5D=4&s%5B%5D=5&s%5B%5D=6&s%5B%5D=7&s%5B%5D=8&s%5B%5D=9&s%5B%5D=1&evt=true&dispo=true&start=2017-09-11&end=2017-09-18&timezone=Europe%2FParis&_=1505122865320" for 78.206.32.41 at 2017-09-11 09:41:05 +0000
Processing by API::AvailabilitiesController#public as JSON
  Parameters: {"t"=>["10"], "m"=>["11", "8", "10", "7", "12", "13", "14", "15"], "s"=>["2", "4", "5", "6", "7", "8", "9", "1"], "evt"=>"true", "dispo"=>"true", "start"=>"2017-09-11", "end"=>"2017-09-18", "timezone"=>"Europe/Paris", "_"=>"1505122865320"}
  Availability Load (1.2ms)  SELECT "availabilities".* FROM "availabilities" WHERE (start_at >= '2017-09-10 22:00:00.000000' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabilities"."lock" = 'f'
Completed 500 Internal Server Error in 3ms (ActiveRecord: 1.2ms | Elasticsearch: 0.0ms)

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column availabilities.lock does not exist
LINE 1: ...' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabil...
                                                             ^
: SELECT "availabilities".* FROM "availabilities" WHERE (start_at >= '2017-09-10 22:00:00.000000' AND end_at <= '2017-09-18 21:59:59.999999') AND "availabilities"."lock" = 'f'):
  app/controllers/api/availabilities_controller.rb:91:in `public'

**Comment by julienrat** [comment]
et le fichier ￼app-stderr.log est téléchargeable ICI : http://partage.informatique-libre.org/dl/e00071

**Comment by sylvainbx** [comment]
Je crois que j'ai compris ... J'ai oublié de préciser dans les commandes de mise à niveau qu'il fallait exécuter un `rake db:migrate` (étrangement ça fonctionne chez moi, même sans ça). Si tu peux essayer, et me dire si ça résout ton problème ?

**Comment by julienrat** [comment]
Nickel ! 
`docker-compose run --rm fabmanager bundle exec rake db:migrate`

Cette commande a résolu ce petit soucis !
Merci encore pour la rapidité !
++

**Comment by sylvainbx** [comment]
Super, merci pour tes retours.
Je vais mettre à jour la documentation et publier la nouvelle release avec le correctif de ce pas !
Bonne journée

**Comment by sylvainbx** [comment]
Corrigé dans la [release 2.5.12](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.12)
