### ISSUE TITLE
Bug affichage page d'accueil

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#82]
Bonjour !
Un petit bug remarqué sur la première page (entouré en rouge) ça dépasse ;-)
https://img11.hostingpics.net/pics/508971Capturedu20170911123833.png

Bonne journée !

**Comment by sylvainbx** [comment]
OK j'en profite pour corriger ça !

**Comment by sylvainbx** [comment]
Corrigé dans la [release 2.5.12](https://github.com/LaCasemate/fab-manager/releases/tag/v2.5.12)
