### ISSUE TITLE
Gestion des espaces, définition des horaires

### ISSUE THREAD

**Issue by julienrat** [sleede/fab-manager#83]
Lorsque l'on sélectionne plusieurs jours pour fixer l'ouverture des espaces, il nous est impossible de fixer les horaires, 
L'horaire de fin est grisée.

EXEMPLE : comment définir l'ouverture du labo du mardi 10h au jeudi 17h ? Peut être utiliser la même technique que pour les événements récursifs ?

**Comment by sylvainbx** [comment]
Bonjour, je ne saisis pas bien ton problème.
Il faut créer des créneaux différents pour chaque jour : un le mardi de 10h jusqu'à l'heure de fermeture, un le mercredi toute la journée et un le jeudi jusqu'à 17h.
Il n'existe pas, pour le moment, de méthode pour créer automatiquement des disponibilités sur une longue période.

**Comment by jarod022** [comment]
Le comportement de gestion du module des espaces est similaire à celui des machines.
Autrement dit, la récurrence n'est pas possible et l'heure de fin est fonction de l'heure de début, de sorte à toujours créer des créneaux par tranche d'une 1h sur la période choisie. Il est donc préférable de créer les créneaux pour la journée du mardi, puis du mercredi et enfin du jeudi.

Il y a certainement des choses à améliorer, mais cela demande un temps conséquent de développement notamment pour y ajouter le support de la récurrence. Il serait par ailleurs intéressant de discuter des nouvelles fonctionnalités pouvant être utiles avec la communauté (sur le Forum).
