### ISSUE TITLE
Changement de profil administrateurs

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#85]
Bonjour,
Dans mes notifications d'hier tous les profil admin ont été "mis à jour" alors qu'aucuns des admins concernés n'est intervenu sur son profil.

Normal ?
M Debar

**Comment by sylvainbx** [comment]
Bonjour,
Oui cela est normal. C'est lié à la mise à jour vers une version > 2.5.11. Les administrateurs sont désormais dans un groupe séparé des autres utilisateurs.
Bonne journée.
