### ISSUE TITLE
Unable to reserve a machine

### ISSUE THREAD

**Issue by pmauduit** [sleede/fab-manager#86]
Using the master branch on commit 6efb4eb7735264e5c4660ff18cd5f322bdf1ca02, i am no longer able to achieve a timeslot reservation, getting the following trace in the logs:

```
Started POST "/api/reservations" for xx.yy.zz.tt at 2017-09-16 18:44:58 +0200
Processing by API::ReservationsController#create as JSON
  Parameters: {"reservation"=>{"user_id"=>2, "reservable_id"=>"4", "reservable_type"=>"Machine", "slots_attributes"=>[{"start_at"=>"2017-09-17T06:00:00.000Z", "end_at"=>"2017-09-17T07:00:00.000Z", "availability_id"=>32, "offered"=>false}]}}
(Status 400) (Request req_AfufwaHokdrYol) Missing required param: customer.
Completed 422 Unprocessable Entity in 4059ms (Views: 0.2ms | ActiveRecord: 2.4ms | Elasticsearch: 0.0ms)
```

Our fabmanager instance is running Debian stretch, ` ruby 2.3.0p0 (2015-12-25 revision 53290)` (set up via an Ansible RVM role, the whole deploy is managed by a custom ansible recipe), code updated via git onto previously mentioned commit + rake assets:clobber + rake assets:precompile + rake db:seed.

I'm a little rusty about rails development / deployment / best practices, so I might have forgotten something (and probably following master is not a good thing, but our fablab is still in a testing phase).

**Comment by sylvainbx** [comment]
Hi @pmauduit ,
This looks like you have misconfigured something. I tried your scenario but was not able to reproduce the issue. The error logged is linked to stripe. Maybe you have changed your API keys recently? In this case your existing users can't be used anymore.

**Comment by pmauduit** [comment]
> This looks like you have misconfigured something. I tried your scenario but was not able to reproduce the issue. The error logged is linked to stripe. Maybe you have changed your API keys recently? In this case your existing users can't be used anymore.

Oh ok ; we actually do not want to use stripe, so we first left the STRIPE_API_KEY blank in the application.yml, then we configured it to use the integration key advised in their API documentation (we wanted to go further on some features that seemed to need it). Anyway, as far as I remember, it was not useful before, and we already were able to reserve a slot. We will dig in further (try to remove the STRIPE_API_KEY) and see if it solves our problem.

By the way, if we don't want to use stripe, is there a way to force the parameter value ? I know there is a current feature request on the project to unplug stripe, and we are willing to help on this, if we can.

**Comment by sylvainbx** [comment]
Currently, fab-manager is deeply linked to stripe and this is not supported at all to use the platform without configuring stripe. I honestly don't know how it can work without a valid stripe configuration (`STRIPE_API_KEY`, `STRIPE_PUBLISHABLE_KEY` and `STRIPE_CURRENCY`). Every times you create a user, an invoice, a subscription or a reservation, it is remotely created on stripe, so if it worked for you, I don't know how.

The only way I see to use fab-manager without stripe is to configure a test API key so the online payments won't be charged for real. Afterwards, you can install it on a private server and use it as an internal management tool (maybe without publishing the URL, or protecting it with a kind of `.htaccess`) but please, be advised that you will **never** be able to enable online payments on your instance in the future ...

**Comment by pmauduit** [comment]
We finally decided to try with Stripe but with no more luck, after having reconfigured our instance, even creating a new user account led us to have no customer identifier associated with the newly created user (`stp_customer_id: nil`), I guess something went wrong either with stripe or sidekiq.

Our current understanding of the code is that when a user is created, the following method is called:
https://github.com/LaCasemate/fab-manager/blob/master/app/models/user.rb#L371-L373

is `perform_async` calling sidekiq under the hood ? Taking this assumption, this should lead us to the following code:

https://github.com/LaCasemate/fab-manager/blob/master/app/workers/stripe_worker.rb#L9-L16

We tried using the rails console to update the user afterwards, but it did not help either.

**Comment by pmauduit** [comment]
Ok, that was the stripe integration actually. With stripe configured (and sidekiq correctly spawned also), we don't have the issue anymore. Thanks, I'm closing the issue.
