### ISSUE TITLE
Portuguese translations

### ISSUE THREAD

**Issue by sylvainbx** [sleede/fab-manager#91]
In [config/locales](https://github.com/LaCasemate/fab-manager/tree/dev/config/locales), on the [dev](https://github.com/LaCasemate/fab-manager/tree/dev) branch, some portuguese translations are missing.

They are noted with the `#translation_missing` tag.
@alexcvcoelho can you help us with that? This would be very appreciated!

**Comment by jmrodriguesgoncalves** [comment]
I am a software development student looking to contribute to multiple projects on Github. I was born in Portugal, even though I currently live in Canada so I am pretty fluent. I could help out if you'd like?

**Comment by sylvainbx** [comment]
Hi @jmrodriguesgoncalves, welcome to the fab-manager community :) I'va seen you pull request. I'm very glad for your help, thank you!

**Comment by sylvainbx** [comment]
This should be fixed now
