### ISSUE TITLE
Setting up the administrator email. Step no.8 Installing Fab-Manager

### ISSUE THREAD

**Issue by nayebare** [sleede/fab-manager#96]
### -https://github.com/LaCasemate/fab-manager/blob/master/README.md?utf8=%E2%9C%93#software-stack

8.Build the database. You may have to follow the steps described in the PostgreSQL configuration chapter before, if you don't already had done it. Warning: NO NOT run rake db:setup instead of these commands, as this will not run some required raw SQL instructions.

rake db:create
rake db:migrate
ADMIN_EMAIL=youradminemail ADMIN_PASSWORD=youradminpassword rake db:seed changeline to -----> ADMIN_EMAIL='youradminemail' ADMIN_PASSWORD='youradminpassword' rake db:seed

**Comment by sylvainbx** [comment]
Hi @nayebare ,
Thanks for noticing it! 
NB: Pull requests are welcome ;)

**Comment by sylvainbx** [comment]
Fixed in [release 2.6.2](https://github.com/LaCasemate/fab-manager/releases/tag/v2.6.2)
