### ISSUE TITLE
Mail Abonnement et activation de compte

### ISSUE THREAD

**Issue by modulaire** [sleede/fab-manager#99]
Bonjour,

Un usager nous fait remarquer que le mail qui confirme sa souscription d'abonnement affiche une date de fin d'abonnement 3 mois après la date de souscription alors que nous sommes en mode glissant. Sa fiche usager confirme d'ailleurs bien une date de fin 3 mois après la date de la première formation...

Toujours avec le même usager ce dernier a reçu une confirmation d'inscription sans jamais avoir cliqué sur le lien de confirmation. Donc un comportement anormal du système...

**Comment by sylvainbx** [comment]
Impossible de reproduire ce bug ...
Aurais-tu plus d'informations, comme un scénario qui permet de reproduire le problème ?

**Comment by sylvainbx** [comment]
Pas de réponse depuis plus de 2 mois ... Je clôture ce rapport de bug. Sens toi libre de le rouvrir si besoin.
